src/main/java/com/aws/greengrass/componentmanager/plugins/S3Downloader.java

Remove the duplicate S3 `getBucketLocation` call.
The removed lines are duplicated with line 127-129.
All the unit and integration tests pass.
**Checklist:**

fix: remove redundant network call

---

src/main/java/com/aws/greengrass/util/Utils.java

Paths created by Greengrass have been created with 700 permissions which is causing issues because if multiple levels of directories are created, then not all users have permissions to traverse the tree. Specifically, `ggc_user` wouldn't have permission to execute a python script because not all of the directories on the path are readable/executable by ggc_user.
**Checklist:**

fix: set permissions on paths that we create to 755 instead of 700

---

assembly.xml

This change simply includes the README and other static info inside the distribution zip.
- `mvn package -DskipTests`
```
% unzip -l target/aws.greengrass.nucleus.zip
Archive:  target/aws.greengrass.nucleus.zip
Length      Date    Time    Name
---------  ---------- -----   ----
0  12-18-2020 16:04   lib/
53652858  12-18-2020 16:04   lib/Greengrass.jar
0  12-18-2020 16:04   bin/
234  12-18-2020 15:57   bin/greengrass.service.template
2398  12-18-2020 15:57   bin/loader
0  12-18-2020 15:57   conf/
500  12-18-2020 15:57   conf/nucleus-build.properties
121  12-18-2020 15:57   NOTICE
10142  12-18-2020 15:57   LICENSE
76527  12-18-2020 15:57   THIRD-PARTY-LICENSES
3482 …
```

chore: Include the readme and copyright info directly in the zip

---

aws.greengrass.Nucleus.yaml
codestyle/findbugs-exclude.xml
pom.xml
src/main/java/com/aws/greengrass/componentmanager/GreengrassComponentServiceClientFactory.java
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/util/RegionUtils.java
src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java

Makes the Greengrass-ATS endpoint port configurable from 8443 (default) to 443 (optional).
Adds an option in the Nucleus configuration called "greengrassDataPlanePort" which can be configured through a deployment. Needed to copy `SdkTlsSocketFactory` from the SDK and override `prepareSocket` so that we can add ALPN to the socket before it is used by the SDK since the SDK has no such support for this right now.
Note to reviewers: do not review `SdkTlsSocketFactory` except for what is between the "modification markers". The rest of the code is directly from the SDK and should not be changed.
Some customers require that all traffic uses port 443, this change enables that functionality. Default is still …

improvement: Make Greengrass-ATS endpoint configurable

---

DEVELOPING.md
pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/BaseE2ETestCase.java
src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
src/main/java/com/aws/greengrass/util/StsSdkClientFactory.java
src/test/java/com/aws/greengrass/easysetup/DeviceProvisioningHelperTest.java
src/test/java/com/aws/greengrass/easysetup/GreengrassSetupTest.java

https://github.com/aws-greengrass/aws-greengrass-nucleus/issues/802
When `--provision` option is set during setup, it currently creates the token exchange IAM role policy directly. Users may create the role/role alias/policy resources outside the setup in order to scope down the permissions needed on the device for setup even further. In that case, checking for the resource through the GetPolicy API first and creating only if the resource does not exist would be desirable.
Manually tested provisioning and starting nucleus
**Checklist:** …

improvement(easysetup): Do not attempt creating role policy if it exists

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/deployment/DeploymentE2ETest.java

Remove GIVEN_deployment_in_dependency_resolution_stage_WHEN_cancel_event_received_THEN_deployment_should_be_cancelled E2E since it has been replaced by Deployment-4-T4 UAT.
**Checklist:**

test: Remove deployment cancelation E2E test since it is being covered in a UAT.

---

pom.xml
src/main/java/com/aws/greengrass/lifecyclemanager/PluginService.java
src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java
src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java

Catches `NoSuchMethodError` in the ALPN implementation since ALPN did not launch with Java 8, but was only backported from Java 9 in April 2020 with JDK8u252. By catching the exception we will enable users to still use port 8443 without issue, it is just that port 443 won't work for the greengrass-ats endpoint.
**Checklist:**

fix: Catch NoSuchMethodError in ALPN implementation for old JDK8 versions

---

src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java

All plugin services should be singletons. Instead of requiring each plugin to add the singleton annotation, this change simply forces them to be singletons by identifying them as a subclass of `PluginService`. This change prevents unnecessary duplication of injected services.
**Checklist:**

fix(plugins): Require plugins to be singletons

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java

Snow* devices return the region as `"null"`, so this change handles that case and treats it as `null` so that we fallback to a real region.
**Checklist:**

fix(regions): Handle literal "null" region

---

src/integrationtests/java/com/aws/greengrass/integrationtests/componentmanager/ComponentManagerIntegTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/telemetry/TelemetryAgentTest.java
src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/GreengrassComponentServiceClientFactory.java
src/main/java/com/aws/greengrass/componentmanager/plugins/ArtifactDownloader.java
src/main/java/com/aws/greengrass/componentmanager/plugins/GreengrassRepositoryDownloader.java
src/main/java/com/aws/greengrass/componentmanager/plugins/S3Downloader.java
src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/main/java/com/aws/greengrass/telemetry/TelemetryAgent.java
src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java
src/test/java/com/aws/greengrass/componentmanager/ComponentManagerTest.java
src/test/java/com/aws/greengrass/componentmanager/plugins/ArtifactDownloaderTest.java
src/test/java/com/aws/greengrass/deployment/IotJobsHelperTest.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java
src/test/java/com/aws/greengrass/telemetry/TelemetryAgentTest.java

Check if device is configured to run offline, then check and skip cloud calls in:
- IoTJobsHelper
- ShadowDeploymentListener
- MqttClient
- FleetStatusService
- TelemetryAgent
- ComponentManager
Avoid unnecessary cloud communication if device is configured to run offline.
While offline, install Nucleus and CLI, do a local deployment, then shutdown.
Tested with a Hello World recipe with an artifact declared without checksum.
Deployment succeeds. Also, if artifact doesn't exist, fails with expected error.
**Checklist:** …

improvement(various): No cloud calls if configured to run offline

---

src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
src/test/java/com/aws/greengrass/deployment/IotJobsHelperTest.java

Before: `[WARN] (main) com.aws.greengrass.deployment.IotJobsHelper: Device not configured to talk to AWS Iot cloud. IOT job deployment is offline`
After: `[WARN] (main) com.aws.greengrass.deployment.IotJobsHelper: Device not configured to talk to AWS Iot cloud. IOT job deployment is offline: [thingName cannot be empty, certificateFilePath cannot be empty, privateKeyPath cannot be empty, rootCaPath cannot be empty, iotDataEndpoint cannot be empty, iotCredEndpoint cannot be empty]. {}`
Provide some detailed reason for why device is offline.
Manually run nucleus without provisioning.
**Checklist:**
By …

log: provide detailed error message when device not configured to talk to cloud

---

.github/workflows/maven.yml
pom.xml
src/main/java/com/aws/greengrass/componentmanager/plugins/S3Downloader.java
src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java
src/test/java/com/aws/greengrass/easysetup/GreengrassSetupTest.java
src/test/java/com/aws/greengrass/mqttclient/InMemorySpoolTest.java
src/test/java/com/aws/greengrass/util/OrderedExecutorServiceTest.java

Currently if GetBucketLocation fails with any exception, we assume that the bucket is in us-east-1 which is a bad assumption. This change will throw the exception up if GetBucketLocation fails with an unknown exception. 
This change also improves tests which were leaving stray threads running.
This change also fixes the stray processes which we were seeing in GitHub which was due to us not being able to kill the `sudo` processes due to a lack of permissions.
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

improvement(s3): don't fallthrough if GetBucketLocation fails

---

src/main/java/com/aws/greengrass/deployment/DeploymentConfigMerger.java
src/test/java/com/aws/greengrass/deployment/DeploymentConfigMergerTest.java

Currently, it was getting the entire Nucleus namespace topics. This will ensure we get the correct map containing just the configuration for Nucleus based on the new deployment.
We want the deployment to fail on bad configurations for IoT credentials and data endpoints.
Updated unit tests. Added UATs.
**Checklist:**

fix(deployment): Get the correct configuration map from the new deployment configuration

---

src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java
src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java

Add `{[component]:work:path}` to available `systemParamters` in KernelConfigResolver to support recipe variable interpolation of work paths.
Enable recipes to specify work path of dependency components through variable interpolation.
Unit test
**Checklist:**

improvement: add work path interpolation

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/main/java/com/aws/greengrass/mqttclient/spool/Spool.java
src/test/java/com/aws/greengrass/mqttclient/InMemorySpoolTest.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

In the MqttClient, instead of using the  ScheduledExecutorService, executorService is used to control the spooling process. While the mqttClient is online, the spooler always working and waiting for the next available message if the the queue is empty. 
Original, the spooler would sleep for 5 seconds if the queue is empty. The sleeping time would result in the latency of the message publishing. 
test with "mvn verify"
**Checklist:**

fix(spooler): Improving spooler latency

---

src/main/java/com/aws/greengrass/config/PlatformResolver.java
src/main/java/com/aws/greengrass/util/platforms/Platform.java

Closes #837 
Instead of using `uname -a` to determine the platform, switch to using `os.name` from the Java system properties.
`uname -a` contains the hostname in the output, so if the hostname was "darwin" or "macos" we were incorrectly identifying the machine as a mac.
Validate that on macos the os.name property is "Mac OS X"
Verified that we detect macos and linux correctly, and even after setting the hostname to "darwin" it still detects correctly.
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

fix(platform resolver): determine if on macos using os.name instead of uname -a

---

src/integrationtests/java/com/aws/greengrass/integrationtests/telemetry/TelemetryAgentTest.java

Some tests were failing with a NPE because the mock was only setup after calling the `internalEnableTestingFeatureParameters` so this simply flips the order.
https://github.com/aws-greengrass/aws-greengrass-nucleus/runs/1787744563
**Checklist:**

test: fix NPE in test setup when mock isn't initialized first

---

src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java

Add a check for the first shadow doc received since startup. Ignore the deployment if `reported` section exists and the ARN matches desired ARN. Because the deployment had already been processed and reported.
Fix duplicated shadow deployment when nucleus restarts.
Manual tests:
On EC2:
- From cloud console, deploy a component to the device that will run successfully
- Verify shadow status reported as success
- restart
- Verify log has `Deployment result already reported. Ignoring shadow update at startup.` for the previous deployment config ARN. No duplicate deployment queued
- Deploy a component to the device that will take a long time to install
- Verify shadow status …

fix(shadow): prevent duplicated shadow deployment at startup

---

src/main/java/com/aws/greengrass/deployment/DeploymentStatusKeeper.java
src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java

Two types of timeouts are updated in this PR:
1. Subscribing to IoT jobs related topics
2. Waiting for job status to be accepted/rejected by cloud after publishing deployment status
1. The timeout setting is configurable by customers
1. The second timeout is currently 5 min. The timeout happens inside a lock which prevents status updates in config for the next deployment. Shorter timeout should not impact the deployment logic because failures here in status update will be retried.
End to end test cases of regular deployments and OTA where device goes offline after receiving the IoT job deployment. …

refactor(deployment): use user-provided timeout for IoT jobs operations

---

src/integrationtests/resources/com/aws/greengrass/integrationtests/status/onlyMain.yaml
src/main/java/com/aws/greengrass/componentmanager/DependencyResolver.java
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/test/java/com/aws/greengrass/componentmanager/DependencyResolverTest.java
src/test/java/com/aws/greengrass/deployment/DeviceConfigurationTest.java

If a config file is manually provided at startup with certain nucleus component config but no component version config(or other required keys for nucleus component), inferred version from build file or fallback version if even that's not present(which shouldn't happen in real usage) should be used instead of forcing user to include version in manually created config or finding out too late that it's needed
Also adds a null check in dependency resolution which depends on the version config and and fails without proper message if it's missing
See description
Added unit tests
**Checklist:**
By …

fix(startup): ensure nucleus version config is always available

---

CHANGELOG.md
src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/mqttclient/MqttTest.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Greengrass v2 currently tracks the number of subscriptions that each MQTT client made, since IoT Core limits subscriptions to 50 per connection. This has a bit of a conflict when Greengrass restarts because Greengrass no longer knows how many subscriptions the client has; it would assume that the client has 0 subscriptions, even though it connected with a persistent session which may have resubscribe to up to 50 topics.
The behavior of the client which has over-subscribed is that the initial 50 subscriptions work correctly, but subsequent subscriptions, despite not erroring in anyway, simply do not work (no messages come in for them).
When a new mqtt connection is made, the client connects with cleansession = true, then disconnects …

fix(mqtt): Terminate previous mqtt session when creating a new connection

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/test/java/com/aws/greengrass/deployment/DeviceConfigurationTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java
src/test/java/com/aws/greengrass/tes/TokenExchangeServiceTest.java

High throughput operations like mqtt publish checks if the device is configured to talk to cloud. Currently this check is performed every time a message needs to be published.  
This change caches the results of a validate() call on device configuration. The cache is invalidated when the device configuration changes.
Unit tests.
Test Plan:
1. Verified validate() is called if cache is empty
2. Verified validate() is not called when cache is not empty
**Checklist:**
- [ X] Updated or added new unit tests

improvement(DeviceConfiguration): Cache the result of validate operation on device configuration 

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCTestUtils.java
src/main/java/com/aws/greengrass/ipc/IPCEventStreamService.java
src/main/java/com/aws/greengrass/util/platforms/Platform.java
src/main/java/com/aws/greengrass/util/platforms/WindowsPlatform.java
src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java
src/test/java/com/aws/greengrass/ipc/IPCEventStreamServiceTest.java

* Define a few methods in `Platform` for the IPC backing file.
* On Unix, the implementation is to provide a domain socket.
* On Windows, the implementation is to provide a named pipe.
* When providing the name of the named pipe, append an UUID to make the name unique so that multiple instances of Nucleus can be started.
* When running on Windows, RPC server expects the `hostname` in the form of a named pipe.
* Unit tests and integration tests on Linux
* On Windows, manually start Nucleus and observe the following log:
```
2021-02-03T22:49:21.632Z [INFO] (main) com.aws.greengrass.lifecyclemanager.KernelLifecycle: system-start. Launch Nucleus. …
```

feat: handle RPC server initialization on Windows

---

src/main/java/com/aws/greengrass/componentmanager/GreengrassComponentServiceClientFactory.java
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java
src/test/java/com/aws/greengrass/deployment/DeviceConfigurationTest.java

Refactor `isDeviceConfiguredToTalkToCloud` so that it only checks cloud related settings instead of all device settings.
Removes unnecessary calls to the OS to validate users.
**Checklist:**

refactor(deviceconfiguration): isDeviceConfiguredToTalkToCloud validates only cloud related settings

---

src/main/java/com/aws/greengrass/componentmanager/ClientConfigurationUtils.java
src/main/java/com/aws/greengrass/componentmanager/GreengrassComponentServiceClientFactory.java

Creating client configuration utility to set the necessary certificates for calling the data plane api.
This will avoid the duplication of the code in ip detector
Manually 
**Checklist:**

refactor: exposing methods for setting the client certificates to call the data plane api

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/PeriodicFleetStatusServiceTest.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java
src/test/java/com/aws/greengrass/mqttclient/WrapperMqttClientConnectionTest.java
src/test/java/com/aws/greengrass/telemetry/TelemetryAgentTest.java

`AwsIotMqttClient`: Implement MQTT continuous subscription retry upon connection recovery.
Before: when MQTT connection resumed, retry all subscribed topics once only if session persisted.
After: when MQTT connection resumed, retry failed subscriptions. Keep retrying until succeeded or connection interrupted again, with backoff delay.
- Add unit tests for resubscribe logic.
- Add unit tests for `WrapperMqttClientConnection` and `MqttClient` to increase test coverage.
- Fix flaky `TelemetryAgentTest`:
- [Link to failed run](https://github.com/aws-greengrass/aws-greengrass-nucleus/runs/1891190361). Null pointer exception because `TestFeatureParameters.internalEnableTestingFeatureParameters` was called before mock was fully setup. Fixed …

feat(AwsIotMqttClient): resubscribe robust retry

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/deployment/DeploymentE2ETest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/deployment/ShadowDeploymentE2ETest.java
src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java

We update the shadow when a deployment completes which will queue the MQTT message to be delivered eventually. If multiple changes happen, then the messages may be processed out of order, thus causing the shadow to be in an inconsistent state.
Update the shadow using optimistic locking, which adds a version field to the update. The shadow will only be updated in the case that the current shadow version matches the version provided in the update. If a shadow update is rejected, device will fetch the latest shadow and retry the update with the updated shadow version.  This will ensure that the shadow is always in a consistent state and will eventually show the current state.
E2E tests.
Tests:
When a …

fix(shadowdeployment): handle out of order shadow updates

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

If the subscribe topic is not valid, the MqttClient is impossible to finish the operation successfully.
For the details,  please refer to ***topic size***  and ***Maximum number of slashes in topic and topic filter*** at https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot
check the request topic before doing the operation of subscription.
**Checklist:**

fix(mqttclient): validate subscribe request

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/PluginComponentTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/UnloadableServiceIntegTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/unloadable_plugin.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/unloadable_service_missing_config.yaml
src/main/java/com/aws/greengrass/deployment/DeploymentConfigMerger.java
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/KernelUpdateDeploymentTask.java
src/main/java/com/aws/greengrass/deployment/activator/DefaultActivator.java
src/main/java/com/aws/greengrass/lifecyclemanager/GreengrassService.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
src/main/java/com/aws/greengrass/lifecyclemanager/UnloadableService.java
src/test/java/com/aws/greengrass/deployment/DeploymentConfigMergerTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/GenericExternalServiceTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/GreengrassServiceTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelLifecycleTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/SetupDependencyTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/UnloadableServiceTest.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java

Handle service load exception on Nucleus launch
1. Refactor `public GreengrassService locate(String name)` to `locate` which surface exceptions and `locateIgnoreError` which proceeds exceptions using surrogates.
1. `locateIgnoreError` are used during Nucleus launch, loading new services in deployments, and service setting up dependencies.
1. Deployments are required to fix unloadable services. 
1. Fixes to plugin services will trigger Nucleus restart. 
1. Non-plugin services will not restart Nucleus, but old instance will be closed and new one created with new config. When closing unloadable service, its depending services will not block the shutdown.
Minor improvements
1. Track group to root components information if deployment is …

fix(startup): don't crash nucleus on service load exceptions

---

.github/workflows/maven.yml
src/main/java/com/aws/greengrass/lifecyclemanager/KernelAlternatives.java
src/main/java/com/aws/greengrass/util/Permissions.java

Set the loader script to be executable immediately when the Nucleus starts up if it isn't already set as executable. This is required so that we can `exec` the loader when restarting the Nucleus.
**Checklist:**

fix(loader): make loader script executable immediately on startup

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Currently, the spooler could only use singe thread for message publishing and result in publish tps as 13-15. Right now, re-introduce the parameter of "maxInFlightPublishes" to increase the tps. 
Because IoT has restriction of Inbound/Outbound publish requests per second per account as 100, "maxInFlightPublishes" will limit to 100. 
**Checklist:**

improvement(spooler): reintroduce the parameter of maxInFlightPublishes

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/ComponentWithCircularDependency-1.0.0.yaml
src/main/java/com/aws/greengrass/componentmanager/DependencyResolver.java
src/test/java/com/aws/greengrass/componentmanager/DependencyResolverTest.java

1.  Circular dependencies causes deployment to go into an infinite loop.
2. During dependency resolution, if the resolved version of a component changes. Say during the initial stage of dependency resolution B got resolved to version 1.0.0 and at a later stage  B got resolved to 2.0.0. Current implementation does not remove the dependencies of B=1.0.0.
1. Dependency resolver will detect circular dependency during dependency resolution and fail the deployment. The detailed deployment status will mention circular dependency as the reason.
2. When the version of a component is bumped from v1 to v2. Dependency resolver will remove dependencies of v1. All version constraints placed by the removed components will also be removed.
**How was …

fix(dependencyresolver): fail fast when circular dependency is detected

---

src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
src/test/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloaderTest.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java
src/test/java/com/aws/greengrass/telemetry/TelemetryAgentTest.java

Add proxy support while downloading 1P component artifact with pre-signed URL.
Without this change, customer running Nucleus behind a proxy cannot deploy 1P components.
Tested end-to-end deploying 1P public components to Nucleus.
**Checklist:**

fix(proxy): support 1p component artifact download with proxy

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java

Remove usage of `CompletableFuture.anyOf` in order to resolve memory leak due to JDK-8160402. This JDK bug, which has been fixed in Java 9, results in extraneous futures which never complete if any of the future inside of the `anyOf` don't complete.
Without this change, after approximately 1 hour we had ~400MB of CompletableFutures which could not be garbage collected.
Verified with jprofiler that memory no longer increases over time and the number of CompletableFuture objects stays reasonable.
**Checklist:** …

fix(spooler): fix memory leak due to CompletableFuture.anyOf

---

README_CONFIG_SCHEMA.md
src/integrationtests/java/com/aws/greengrass/integrationtests/status/PeriodicFleetStatusServiceTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/telemetry/TelemetryAgentTest.java
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

If the configured value is less than the default (84600 seconds), then it is set to the default.
If the configured value is more than the default, then the periodic update interval for FSS is set to that configured value.
To ensure that the customers have the ability to increase the cadence at which the status of the device is sent periodically.
Added unit tests.
**Checklist:**

feat(fleetstatusservice): make periodic update interval for Fleet Status Service configurable

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java

There was a deadlock in `reconnect()` due to the synchronized block there and in the `whenComplete` callback of `disconnect()`. Removed the synchronized block so that we don't deadlock and modified the reconnect test to fail if it does deadlock.
**Checklist:**

fix(mqttclient): remove synchronization deadlock in reconnect

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
src/test/java/com/aws/greengrass/deployment/DeviceConfigurationTest.java
src/test/java/com/aws/greengrass/easysetup/GreengrassSetupTest.java

Properly validate AWS region.
Currently we are letting bad region through and causing NullPointerException later on.
Added new unit tests.
**Checklist:**

fix: region validation avoid NPE

---

THIRD-PARTY-LICENSES
codestyle/findbugs-exclude.xml
pom.xml
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/main/java/vendored/com/google/common/base/Stopwatch.java
src/main/java/vendored/com/google/common/base/Ticker.java
src/main/java/vendored/com/google/common/util/concurrent/RateLimiter.java
src/main/java/vendored/com/google/common/util/concurrent/SmoothRateLimiter.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java
src/test/java/com/aws/greengrass/util/RateLimiterTest.java

Manually including `RateLimiter` from Guava instead of taking a dependency on all of Guava. Implementing rate limiting at 100TPS to avoid IoT Core throttling at 100TPS. Also rate limiting based on bandwidth used since IoT Core limits us to 512 KBPS. Tested that publishing at 100TPS did not trigger IoT Core's throttling at all.
**Checklist:**

fix(mqttclient): add rate limiting for publish request at 100TPS/512KBPS

---

src/integrationtests/java/com/aws/greengrass/integrationtests/componentmanager/plugins/docker/DockerImageArtifactDownloadTest.java
src/test/java/com/aws/greengrass/componentmanager/plugins/docker/EcrAccessorTest.java

This internal Base64 class was giving me trouble so I switched to the java.util.Base64 version available in Java 8+.

Switched com.sun.org.apache.xerces.internal.impl.dv.util.Base64 to java.util.Base64

---

pom.xml
src/main/java/com/aws/greengrass/config/Configuration.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java
src/test/greengrass-nucleus-benchmark/pom.xml
src/test/java/com/aws/greengrass/authorization/AuthorizationPolicyParserTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/LifecycleTest.java

Drop jackson-jr and cbor since we use full jackson anyway and we do not use cbor at all.
**Checklist:**

chore: remove jackson-jr

---

.github/workflows/maven.yml

Enable Github Action to run on Windows.
Github Action is not being run on Windows. As we ports to Windows, having it run on Windows can help us to write tests specific for Windows as well as to make sure new developments do not break the Windows build.
Github Action itself. 
Note that the tests are not passing 100% on Windows yet. Once the Action runs on Windows, the next step is to investigate the failing tests.
We also need to update branch protection to check on `Build on ubuntu-latest` before we merge this PR. Since tests running on Windows do not pass 100% yet, so do not check `Build on …

feat(windows): enable github action to run on Windows

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/status/IotJobsFleetStatusServiceTest.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java

Do not attempt to create a new MQTT client when we have one which isn't null. This prevents a reconnect storm due to duplicate client IDs. Since the IoT SDK will reconnect on its own, we leave it to the SDK to get us reconnected. Previously we were triggering based on if we were connected or not, but that doesn't matter. If we're not connected that doesn't mean that we need a new connection instance.
**Checklist:**

fix(mqttclient): stop creating new MQTT client when one exists

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java

MQTT max message size was using `>=` instead of `>` which meant that we could not publish 128KB exactly, only 128KB-1.
Verified in UAT that we're able to publish and receive with 128KB size.
**Checklist:**

fix(mqtt): max message size validation should be >

---

src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java

New error: `Duplicate policy ID "Id1" for principal "[compB, compA]"`
Old error: `Malformed policy with duplicate policy Id's`
Also removing call to `onConnectionInterrupt` in the MQTT connection cleanup as it isn't needed and is called by the IoT SDK anyway.
**Checklist:**

fix: auth policy parser duplicate policy error message

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java

When establishing a new mqtt connection the following steps are taken
1. connect with session=false to kill previous session
2. disconnect
3. connect with session=true
AWS IoT Core restricts MQTT CONNECT requests from the same accountId and clientId to 1 MQTT CONNECT operation per second. Added a rate limiter for connect operation to prevent the client from being throttled when establishing a new connection.
**Checklist:**

fix(mqtt): added rate limiter for MQTT connect operation

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
src/test/java/com/aws/greengrass/lifecyclemanager/GenericExternalServiceTest.java

1. Update timestamp of initial `jvmOptions` config.
During deployments, default config values from recipes are loaded with timestamp `1` [here](https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/003f19ee79627f5a0e281beee285c26aaa311ef6/src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java#L310-L315), and during the config merge, config values with the same timestamp will override current value in [withNewerValue](https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/8a9bd022c7a1da82012eec4a006839d7b7e36f70/src/main/java/com/aws/greengrass/config/Topic.java#L210-L213).
As a result, `jvmOptions` will be reset to default value from recipe, i.e. `""`, incorrectly during deployments.
The timestamp …

fix: timestamp of initial jvmOptions; bootstrap config comparison

---

src/main/java/com/aws/greengrass/config/ConfigurationWriter.java

File descriptor leak when rotating tlog file.  
Tested on dev box. Tested by reducing the frequency at which tlogs are rotated. Without the fix, the kernel FD count goes up by 1 after each rotation. 
The fix can also be verified by checking the metrics in deployment performance tests.
**Checklist:**

fix(tlog): close tlog writer to prevent fd leak

---

src/main/java/com/aws/greengrass/lifecyclemanager/KernelCommandLine.java
src/main/java/com/aws/greengrass/util/Exec.java

The root work path is not writable, so instead of setting HOME to a non-writable path we just won't set it at all. The shell will be setting HOME for us to the user's home directory.
```
unset HOME
sudo -H -u $(whoami) -- sh -c "echo \$HOME"
```
This shows that when launched without $HOME set, sudo and the child shell will still set the HOME correctly.
**Checklist:**

fix: remove default environment variable for HOME which is non-writable

---

src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
src/test/java/com/aws/greengrass/easysetup/GreengrassSetupTest.java

If both ggc_user and ggc_group already exist assume they are set up
correctly so there is no need to add ggc_user to the ggc_group.
This is important if the system has a readonly root partition.
Copy of #919 
If both ggc_user and ggc_group already exist assume they are set up
correctly so there is no need to add ggc_user to the ggc_group.
This is important if the system has a readonly root partition or is missing usermod
**Checklist:**

fix: during setup only add the user to the group if we just created it

---

src/main/java/com/aws/greengrass/iot/IotCloudHelper.java
src/main/java/com/aws/greengrass/iot/IotConnectionManager.java
src/test/java/com/aws/greengrass/tes/IotCloudHelperTest.java

Rewrites the IoT Cloud helper to use the standard AWS SDK client instead of the CRT's client. This is to avoid native issues which are difficult to debug and reproduce. We are already using the AWS SDK client for TLS mutual auth operations such as the Greengrass repository downloader.
Tested by running the TESTest locally in a loop so that it pulls credentials from the cloud every 500ms. It is able to get credentials every time.
**Checklist:**

refactor: rewrite IoT cloud helper to use AWS SDK client instead of CRT

---

.github/scripts/binaryCompatibility.py
.github/workflows/externalPR.yml
.github/workflows/maven.yml

Move steps which require the github secret for commenting into a separate workflow which is triggered by the pull request workflow completing.
This will enable us to test code from forks.
**Checklist:**

build(ci): separate commenting steps to allow forks to run

---

.github/workflows/maven.yml

Fix for issue: https://github.com/aws-greengrass/aws-greengrass-nucleus/runs/2326996814
**Checklist:**

fix(build): only upload PR info when the event is a pull request

---

src/main/java/com/aws/greengrass/lifecyclemanager/KernelCommandLine.java

The `main` method in `KernelCommandLine` is not used. The `main` method being used is in `GreengrassSetup`. This PR removes the one in `KernelCommandLine` to reduce confusion.
**Checklist:**

chore: remove unused main method

---

src/main/java/com/aws/greengrass/builtin/services/mqttproxy/MqttProxyIPCAgent.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/main/java/com/aws/greengrass/mqttclient/PublishRequest.java

Use [String.intern()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#intern()) in order to save strings into Java's string pool to avoid string duplication in memory. For MQTT messages with the same topic, which is a fairly common use case, we'd normally end up using quite a bit more memory than just the payload size due to duplicating the topic names.
Additionally, using `String.length()` instead of getting the bytes since getting the bytes requires actually re-encoding the value which is expensive and unnecessary.
**Checklist:**
By submitting this pull request, …

perf: use interned strings for MQTT topics for lower memory usage

---

scripts/loader

When Greengrass is running in Docker or elsewhere, it will attempt to restart when receiving a SIGTERM. 
Added a new variable `sigterm_received` to track this via a `trap` and stop restart attempts.
Also added `set +m` to the loader script.
`docker run --init -d -e "TINI_KILL_PROCESS_GROUP=1" -e "TINI_VERBOSITY=3" --entrypoint /greengrass-entrypoint.sh <image ID>`
`docker stop` (to send SIGTERM)
`docker logs <container ID>` to verify output :
```
Launched Nucleus successfully.
++ echo Received SIGTERM
++ sigterm_received=1
+ kernel_exit_code=143
+ echo 'Nucleus exit at code: 143'
+ case ${kernel_exit_code} in
Received SIGTERM
Nucleus exit at code: 143
+ echo 'Nucleus exited 143. Retrying 1 times' …
```

fix(loader): catch SIGTERM to shutdown nicely in docker

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/FleetConfigWithRequiredCapability.json
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverter.java
src/main/java/com/aws/greengrass/deployment/exceptions/MissingRequiredCapabilitiesException.java
src/main/java/com/aws/greengrass/deployment/model/DeploymentDocument.java
src/main/java/com/aws/greengrass/deployment/model/LocalOverrideRequest.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java
src/test/greengrass-nucleus-benchmark/src/main/java/com/aws/greengrass/jmh/packagemanager/DependencyResolverBenchmark.java
src/test/java/com/aws/greengrass/componentmanager/DependencyResolverTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java
src/test/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverterTest.java
src/test/resources/com/aws/greengrass/deployment/converter/FcsDeploymentConfig_Full.json

In order to support controllable errors, the GGC will support a requiredCapabilities element in the deployment document that describes capabilities needed to execute the deployment. If the required capability is not found, Nucleus will fail the deployment.
Test Plan:
1.  When required capabilities field in deployment document is not present/empty THEN deployment succeeds
2. When one of the required capabilities in deployment document is not supported by GGC THEN deployment fails. Deployment failure cause contains the missing required capability.
3. When all required capabilities in deployment document is supported by GGC THEN deployment succeeds. 
Tested using integration tests.
**Any additional information or context required to …

feat(deployment): add required capabilities feature

---

pom.xml
src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java

…shadowManager to authorizationHandler
Shadow-1 
- Taking updated smithy model changes and copying them over to the Nucleus (only shadow related code)
- `GreengrassCoreIPCService.java`
- Adding ShadowManager to AuhtorizationHandler preset operations map
- Changing iotdevicesdk version to use `1.3.0-SNAPSHOT` which has shadow changes 
These changes are necessary to support ShadowManager component by adding ipc support for `GetThingShadow`, `UpdateThingShadow`, `DeleteThingShadow`, and `ListNamedShadowsForThing`
Currently tested locally with Shadow UAT's using a local nucleus kernel and a local ShadowManager component
**Any additional information or context required to …

feat(shadowmanager): add shadowmanager ipc support

---

src/main/java/com/aws/greengrass/util/platforms/windows/WindowsPlatform.java

Implement the no-op case for `RunasDecorator` when the requested user is the same as the current user.
`RunasDecorator` is not implemented on Windows. With this change, it is easier to identify from the integration tests what are the gaps between Windows and Linux Nucleus.
Before this change, integration tests have 55 failures/errors.
```
Tests run: 101, Failures: 40, Errors: 15, Skipped: 15
```
After this change, the integration tests only have 5 failures/errors
```
Tests run: 123, Failures: 3, Errors: 2, Skipped: 16
```
**Checklist:** …

feat(windows): no-op runas when requested user is the current user

---

.license/style.xml
assembly.xml
pom.xml
scripts/loader.cmd

New File: **loader.cmd**
Excluded **loader.cmd** from maven license plugin (it wasn't recognizing comment style of _@REM_)
Included **loader.cmd** in zip package
**Known issue:**
If the symlink **target** contains brackets in the name, then the function to flip the symlinks will not correctly set the symlink target.
The existing **loader** shell script does NOT work on Windows platforms. This new **loader.cmd** replicates the behavior in the existing **loader** shell script but for Windows platforms.
1 .Created a zip via the following command:
`mvn -DskipTests clean package`
I had to skip tests because there are existing tests that do not pass on Windows.
2. Deployed …

feat(windows): add loader.cmd batch script

---

pom.xml
src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/ComponentServiceHelper.java
src/main/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloaderFactory.java
src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java
src/test/java/com/aws/greengrass/componentmanager/ComponentManagerTest.java
src/test/java/com/aws/greengrass/componentmanager/ComponentServiceHelperTest.java
src/test/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloaderFactoryTest.java
src/test/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloaderTest.java

Use new pre-release data plane SDK which contains two existing component service APIs and three new client device APIs
client device management components need to integrate with greengrass cloud
existing tests pass
**Checklist:**

chore: use new pre-released data plane SDK

---

src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/service_error_recovery_step_fixes_service.yaml

Fix `GenericExternalServiceTest.GIVEN_service_has_recovery_step_WHEN_recovery_logic_fixes_issue_THEN_service_recovers`
on Windows.
Tested locally with Intellij
**Checklist:**

fix(windows): fix GenericExternalServiceTest

---

pom.xml
src/main/java/com/aws/greengrass/componentmanager/plugins/docker/EcrAccessor.java
src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/util/EncryptionUtils.java

Removing netty client and the `.a` files from the IoT Device SDK which aren't needed.
Saves ~7MB in our jar.
**Checklist:**

build: remove netty client from dependency closure

---

src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java

Be more lazy about initializing the DeviceProvisioningHelper which creates many AWS SDK clients leading to increased memory usage. This change saves approximately 10MB at runtime.
**Checklist:**

perf: only initialize DeviceProvisioningHelper if we are provisioning

---

src/test/java/com/aws/greengrass/easysetup/GreengrassSetupTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/GenericExternalServiceTest.java

Currently Github Action is running on Linux as well as on Windows. However we are not enforcing unit tests and integration tests to pass on Windows yet.
One functionality not implemented on Windows yet is RunWith. Tests that use RunWith as well as creating user/group for RunWith is expected to fail. I want to disable these tests for now so that we can check the result of the tests. There are tickets to followup with these tests.
The tests that need to be disabled are all unit tests. We are fixing failing integration tests in separate PRs and there is no plan to disable any integration tests.
To enable checking Github action result on Windows.
All unit tests should pass …

fix(windows): disable unit tests that requires user/group on Windows

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/IotJobsFleetStatusServiceTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/FleetConfigSimpleApp.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/FleetConfigSimpleApp2.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/local_store_content/recipes/SimpleApp-1.0.0.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/local_store_content/recipes/SimpleApp-2.0.0.yaml
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

**1: list Installed components returns components that got removed from the device**
The contract between the device and cloud is that when a component is removed from the device, the FSS local agent will update cloud of the removal by reporting status for the components with the fleetConfigArns field as empty. There is a bug in FSS local agent which causes it not send this update. The bug is hit when three events happen in the following order:
i. Kernel restarts
ii. Any Component moves to BROKEN state
iii. A deployment removes a component in BROKEN or FINISHED state.
Root cause:
FSS local agent keeps tracks of components running on the device in two ways.
i. FSS agent keeps track of all components added by a deployment. [STATE 1]
ii. FSS agent keeps track of …

fix(fss): make fss local agent more robust

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
src/main/java/com/aws/greengrass/lifecyclemanager/LogManagerHelper.java
src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java

Requires the following logging package change. Expecting workflow to fail for now.
https://github.com/aws-greengrass/aws-greengrass-logging-java/pull/103
- Fix bug: config not applying to component log.
- Support RESET logging topics to revert to default.
- This allows customers to configure greengrass logging as desired
- Added unit tests
- Added UATs
**Checklist:**

fix(logging): config not applied to component logger. support reset

---

.github/workflows/maven.yml
pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/UnloadableServiceIntegTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/unloadable_plugin.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/unloadable_service_missing_config.yaml
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
src/main/java/com/aws/greengrass/lifecyclemanager/GreengrassService.java
src/main/java/com/aws/greengrass/util/Exec.java
src/main/java/com/aws/greengrass/util/platforms/Platform.java
src/main/java/com/aws/greengrass/util/platforms/StubResourceController.java
src/main/java/com/aws/greengrass/util/platforms/SystemResourceController.java
src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java
src/main/java/com/aws/greengrass/util/platforms/unix/linux/Cgroup.java
src/main/java/com/aws/greengrass/util/platforms/unix/linux/LinuxPlatform.java
src/main/java/com/aws/greengrass/util/platforms/unix/linux/LinuxSystemResourceController.java
src/main/java/com/aws/greengrass/util/platforms/windows/WindowsPlatform.java

This change adds a `systemResourceLimits` under `RunWith` configuration, which allows users to configure the resource limits (only memory and cpu for now) for each external service component on Linux. 
This is useful for scenarios where customers want to set a resource limit for components.
Add an integration test 
**Checklist:**

feat(lifecycle): implement resource limit management on Linux using cgroup

---

pom.xml
src/main/java/com/aws/greengrass/componentmanager/ClientConfigurationUtils.java
src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/util/ProxyUtils.java

Remove .a files again, also updates proxy http client provider so that it always provides a client so that we can remove all the nullchecks all over the place.
**Checklist:**

build: remove .a files from jar

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCHibernateTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/hibernate_init_config.yaml
src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
src/main/java/com/aws/greengrass/util/Exec.java
src/main/java/com/aws/greengrass/util/platforms/StubResourceController.java
src/main/java/com/aws/greengrass/util/platforms/SystemResourceController.java
src/main/java/com/aws/greengrass/util/platforms/unix/linux/Cgroup.java
src/main/java/com/aws/greengrass/util/platforms/unix/linux/LinuxSystemResourceController.java
src/test/java/com/aws/greengrass/lifecyclemanager/GenericExternalServiceTest.java

Component lifecycle implementation of component hibernation using linux cgroup freezer subsystem. IPC interface changes in separate earlier PR. 
Adding a change to run the linux maven github workflow as root since some of the tests for resource management require that
New feature for hibernate(pause/resume) components to save consumed resources
New unit and integ tests
**Checklist:**

feat(lifecycle): hibernate implementation using cgroup freezer subsystem

---

src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java
src/test/greengrass-nucleus-benchmark/pom.xml

Added one more check when processing shadow update.
Currently, if a shadow deployment requires restart (aka kernel update workflow), ShadowDeploymentListener will create the same deployment again after restart.
Before the restart, the deployment will have been reported as IN_PROGRESS, which is a non-terminal state. Because it could be due to power off or other unexpected failure, we decided to allow it to create the deployment if the reported status was non-terminal (IN_PROGRESS). But if we're restarting normally, we're still adding the deployment which is duplicated.
If we persist the lastConfigurationArn through restart, then this will be caught by existing logic and won't create duplicated …

fix(deployment): duplicated shadow deployment if restart required

---

src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageArtifactParser.java
src/test/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageArtifactParserTest.java

-
Simplifying image parsing code by moving away from an overly large regex which in certain environment cannot handle an edge case when both tag and digest or their starting identifiers (i.e. `:` or `@`) are present. 
Above mentioned case needs to be handled correctly.
Existing unit tests pass so there is no regression, newly added tests for previously unhandled case pass as well
**Checklist:**

fix(docker): simplify image specification parsing

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/PeriodicFleetStatusServiceTest.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/main/java/com/aws/greengrass/telemetry/TelemetryAgent.java

Description of changes:
Update PeriodicFleetStatusServceTest to use TestFeatureParameterInterface to set the FleetStatusService period.
Why is this change necessary:
The test is failing on Windows Github Actions when the entire test suite is ran. This is because the FleetStatusService period was being reset to the initial value of 86,400 seconds because of the way Runnables were being Dequeued from LinkedBlockingDeque in Context.java.
How was this change tested:
Observing the Github Action results.
**Checklist:**

fix(windows): fix PeriodicFleetStatusServiceTest

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/SampleJobDocumentWithUser_1.json
src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java
src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java

Need to convert `SystemResourceLimits` object to map before merging it to the config.
Update an existing test case to cover this
**Checklist:**

fix: correct the system resource limit merge

---

src/main/java/com/aws/greengrass/componentmanager/plugins/docker/EcrAccessor.java
src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java

ignore some config change events to prevent us from creating new clients when not needed
Greengrass has been creating new SDK clients whenever a configuration changes, however we were not closing the client due to worries about closing a client that someone might be using. This causes an issue because the SDK http clients must be closed in order to remove them from the idle connection reaper thread's mapping. If they are not closed, then they will be referenced by the idle connection reaper forever and leak ~1MB/hr when doing continuous deployments.
An alternative solution would be to disable the idle connection reaper in our SDK clients. …

fix(sdk-clients): close AWS SDK clients when creating new copies

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java

There appears to be a race condition in the integration test that two different threads are trying to remove the cgroup folder simutaneously and causes inconsistent test result. 
Improve test stability
ran the test locally
**Checklist:**

fix(resource-limit): fix the race condition in test

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/deployment/ShadowDeploymentE2ETest.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java

When a connect request hits the same host in IoT Core's fleet, the throttle limit is actually 0.1 TPS and not the stated 1 TPS. This discrepancy causes us to fail to connect and then backoff for 2 minutes. This slows down some of our UATs significantly and it is a negative customer experience. To avoid the issue, limit connect calls to 0.1 TPS per client ID instead of 0.25 as before.
**Checklist:**

fix(mqtt): decrease connect rate limit to adjust for IoT Core's limits

---

src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java
src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java

This change adds `{iot:thingName}` variable into recipe resolution. To be clear, this does not get interpolated into default configuration, only the lifecycle section of the recipe (as with all other recipe variables that we support). The purpose is to allow easy access to the thing name.
We should consider following up and allowing a similar variable replacement in our access control policies, especially for MQTT topic pub/sub where thing name is in the topic.
Updated existing config resolver test to use the new variable.
**Checklist:** …

feat(recipe-interp): add {iot:thingName} variable for recipes

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCMqttProxyTest.java
src/main/java/com/aws/greengrass/util/platforms/unix/linux/LinuxSystemResourceController.java

Validate only positive memory/cpu limits are accepted
Since memory/cpu are stored as primitive type, a missing memory/cpu field passed by the customer is default to 0 in our cloud service. 
**Checklist:**

fix(resource-limit): validate positive memory/cpu limits

---

src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java
src/main/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverter.java

1. For local deployments, the input from the CLI is thing group name (ex FirstGroup) while kernel uses  thing group resource name (ex thinggroup/FirstGroup) to track packages to thing group.
2. Components deployed via local deployments without a group name are excluded from the thing group removal check. 

fix: local deployment use thing group name

---

src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java
src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java

…oning
1. Validation for paths was not correct in GreengrassV2Client factory
2. S3 client does not get initialized if device is provisioned after kernel start.
Fixes
**Checklist:**

fix: fix path validation in gg client factory. reset error message in s3 client factory

---

src/main/java/com/aws/greengrass/deployment/DeploymentService.java

1. Components deployed via local deployments without a group name are excluded from the thing group removal check.
**Checklist:**

fix: exclude local deployment group from thing group removal logic

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/FleetConfigWithResourceLimits.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/SampleJobDocumentWithUser_1.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/config_run_with_user.yaml
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverter.java
src/main/java/com/aws/greengrass/deployment/model/SystemResourceLimits.java
src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java
src/test/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverterTest.java
src/test/java/com/aws/greengrass/deployment/model/RunWithTest.java
src/test/resources/com/aws/greengrass/deployment/converter/FcsDeploymentConfig_Full.json

Remove the `linux` key under `systemResourceLimits` to simplify the interface
The team had a discussion and decided the `linux` key is not necessary.
Updated the existing tests
**Checklist:**

fix(resource-limit): remove the linux key in the resource limit

---

scripts/loader

Wait for the child PID to be killed once we `trap` the SIGTERM.
This is needed for Docker because otherwise when we issue SIGTERM to a container, it does not wait for the child PID and simply kills the process without exiting gracefully.
`docker stop` with the changes added
Observed the following output:
```
Launched Nucleus successfully.
++ echo Received SIGTERM
++ sigterm_received=1
++ kill -TERM 12
++ wait 12
Received SIGTERM
++ echo Killed child PID
+ kernel_exit_code=143
+ echo 'Nucleus exit at code: 143'
+ case ${kernel_exit_code} in
+ echo 'Nucleus exited 143. Retrying 1 times'
+ j=2
Killed child PID
+ '[' 2 -le 3 ']'
Nucleus exit at code: 143
+ '[' 1 -eq 0 ']'
Nucleus exited 143. Retrying …
```

fix(loader): wait for child PID

---

src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
src/main/java/com/aws/greengrass/easysetup/README.md
src/test/java/com/aws/greengrass/easysetup/GreengrassSetupTest.java

#1015
Have added the --thing-name-policy to the installer argument options. This argument has a default value of GreengrassV2IoTThingPolicy and is passed by parameter to the createThing method. No changes have been made to the process of creating or attaching policies. Updated appropriate README and help message.
Addresses the feature request in Issue #1015 for providing a policy name to apply to the provisinoed IoT Thing.
Unit tests run. Manually provisioned inside an ubuntu vm and on a raspberry pi, testing for creation of custom named resource and correctly attaching an existing policy. …

feat(easysetup): added an optional thing-policy-name flag for device provisioning

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelAlternatives.java
src/test/java/com/aws/greengrass/deployment/DeviceConfigurationTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelAlternativesTest.java

Currently our installation copies the artifacts into the proper artifact storage, however the KernelAlternatives are not moved to symlink to that location, instead they point to the initial location. This is error prone as customers may delete these files, thus breaking their installation.
Only the `init` path will be changed. The `init` path is only ever used during the setup, and `current` will point to init or whichever is the proper place for it to be pointing. This change ensures that `current` will never be redirected to point to `init` except during the very first setup which is how it works prior to this change.
Manually tested that the symlink points to the …

fix(install): relink KernelAlternatives to component store during first install

---

conf/recipe.yaml

Adding Windows OS to recipe.yaml as a platform. No Bootstrap definition yet until we have a separate feature for it.
If Windows isn't in the recipe, then the recipe will exist but a definition for Windows will be missing.
Specifically, the error is [here](https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/d047ceeeb6c468bde7a545c7d6733f7fe28800c7/src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java#L372)
Tested via `verify`
**Checklist:** …

fix(windows): add windows os to recipe.yaml

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java

Closes https://github.com/aws-greengrass/aws-greengrass-cli/issues/133
Fix logging configuration initialization which was not updating the logger on startup, only upon changes.
Regression introduced in #959.
**Checklist:**

fix(log-config): update log config on startup, not only on changes

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java

Add *loader.cmd* to list of files for copying.
*loader.cmd* is currently left out and Windows platforms require that file.
Ran `mvn -U -ntp clean install` without the change and saw that *loader.cmd* was missing from **bin** folder.
Ran `mvn -U -ntp clean install` with the change and saw that *loader.cmd* was included in **bin** folder.
**Checklist:**

fix(windows): add loader.cmd to copy files

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/main/java/com/aws/greengrass/builtin/services/lifecycle/LifecycleIPCEventStreamAgent.java
src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
src/main/java/com/aws/greengrass/lifecyclemanager/Lifecycle.java

-
- Change error message for pause/resume requests for non generic components.
- Reconfigure system resource limits on startup/run script execution in case limits got cleaned up during last shutdown
- Add another case in resource limit update test
- Include a fix from mainline in handling names for pooled threads
**Checklist:**

fix(resource-mgt): Fixing a few cases for resource limits and hibernation

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java

Increase CONNECT throttling to avoid IoT Core throttling. 
**Checklist:**

fix(mqtt): increase connect throttling to 11 seconds from 10 seconds

---

src/integrationtests/java/com/aws/greengrass/integrationtests/BaseITCase.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/FileLoggerTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/IotJobsFleetStatusServiceTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java

Provisioning integ test sets logger to DEBUG level logs which ends up flooding our logs for subsequent tests. This change resets the logger for each integ test so that we start with a known state.
**Checklist:**

test: reset logging config for all integ tests

---

src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloaderFactory.java
src/test/java/com/aws/greengrass/componentmanager/ComponentManagerTest.java
src/test/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloaderFactoryTest.java

Artifact Uri in component recipe was not being validated leading to NPE if the URI did not have a scheme.
Adding the validation
**Checklist:**

fix: validate artifact uri from component recipe

---

src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/ComponentServiceHelper.java
src/main/java/com/aws/greengrass/componentmanager/exceptions/NoAvailableComponentVersionException.java
src/test/java/com/aws/greengrass/componentmanager/ComponentServiceHelperTest.java

Improving error message for NoAvailableComponentVersionException to be more understandable by our users.
Now looks like 
```NoAvailableComponentVersionException: No cloud component satisfies the requirements. Check whether the version constraints conflict and that the component exists in your AWS account with a version that matches the version constraints. If the version constraints conflict, revise deployments to resolve the conflict. Component myComponent version constraints: compC requires <1.0.0, someOtherComponent requires >1.0.0, thinggroup/abc requires =1.1.0.```
**Checklist:**
By submitting …

fix(message): improve NoAvailableComponentVersionException messaging

---

scripts/loader

Exit immediately after calling `sudo reboot`. Otherwise the script continues to run until the end. It'll create the `alts/broken` symlink and makes nucleus think it failed.
Without the fix, deployment with any component that requests reboot will fail.
Manual.
**Checklist:**

fix: loader script reboot

---

src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java

`IOException: Broken pipe` is logged by TES when a TES client hangs up before TES has a chance to get the credentials and respond. This change stops us from logging a big error message when there isn't anything we can do about it.
**Checklist:**

fix(message): do not log broken pipe in TES

---

scripts/loader.cmd

Loader.cmd handles the nucleus exit codes properly. 
Tested manually on windows dev desktop
**Checklist:**

fix(loader): handle exit codes correctly

---

src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DefaultDockerClient.java
src/main/java/com/aws/greengrass/util/Exec.java

Switches Exec to use ProcessBuilder to have nicer access to `environment` as a map instead of string array. Fixes the PATH environment variable to use the correct separator to ensure that environment is properly passed down to child processes.
**Checklist:**

fix(exec): switch to ProcessBuilder, fix environment for Windows commands

---

conf/recipe.yaml

-
Adding bootstrap script for Windows to nucleus recipe
Required for OTA to work on Windows
Related acceptance test on Windows passes
**Checklist:**

feat(windows): add nucleus bootstrap script

---

src/integrationtests/java/com/aws/greengrass/integrationtests/provisioning/ProvisionFromTestPlugin.java
src/main/java/com/aws/greengrass/util/Utils.java
src/test/java/com/aws/greengrass/ipc/IPCEventStreamServiceTest.java

Use Paths to get the file name.
Tested on dev machine and windows ws
**Checklist:**

fix(windows): handle paths correctly

---

src/integrationtests/java/com/aws/greengrass/integrationtests/BaseITCase.java
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/provisioning/ProvisionFromTestPlugin.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
src/main/java/com/aws/greengrass/util/platforms/windows/WindowsExec.java
src/main/java/vendored/com/microsoft/alm/storage/windows/internal/WindowsCredUtils.java
src/test/java/com/aws/greengrass/telemetry/TelemetryAgentTest.java
src/test/java/com/aws/greengrass/testcommons/testutilities/ExceptionLogProtector.java
src/test/java/com/aws/greengrass/util/platforms/windows/WindowsCredUtilsTest.java

When using cmdkey to insert credentials on the command line, Windows stores it using UTF-16LE. This change now accounts for that by getting the proper charset based on the system.
**Checklist:**

fix(windows): get proper utf-16 charset for Windows credentials

---

src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
src/main/java/com/aws/greengrass/util/platforms/windows/WindowsExec.java
src/main/java/com/aws/greengrass/util/platforms/windows/WindowsPlatform.java
src/test/java/com/aws/greengrass/util/platforms/windows/WindowsPlatformTest.java

In a previous pull request, I added full control to the SYSTEM account assuming that Greengrass would always run as SYSTEM. This pull request changes it so we give permissions to the Administrators group instead. SYSTEM is a member of Administrators, but importantly so are our accounts we use for testing in our workspace. 
Also updated the needToSwitch user logic so that it will use the privileges of Greengrass if the user has set the requiresPrivilege flag.
Without this change, Runtime-1-T8 fails running in my workspace. With the change it is able to pass.
**Checklist:**
By submitting this pull …

fix(windows): use Administrators group instead of SYSTEM account for default permissions

---

src/main/java/com/aws/greengrass/util/RetryUtils.java

RetryUtill only logs errors at info level only the first time. This can be confusing to the customer as the error is not logged but the issue still persists.
From 2.5  IotPolicy needs to include ListThingGroupsForCoreDevice for deployments to succeed. If that is not the case, device will retry indefinitely to call ListThingGroupsForCoreDevice API and fail, but the error will only be logged once at info level.
**Checklist:**

fix: improve logging in retryUtil

---

src/main/java/com/aws/greengrass/lifecyclemanager/KernelMetricsEmitter.java
src/main/java/com/aws/greengrass/telemetry/PeriodicMetricsEmitter.java
src/main/java/com/aws/greengrass/telemetry/SystemMetricsEmitter.java

* Split up telemetry metric collection from metric emission
* This is needed in order to make metrics available to plugins in Greengrass v2.5.0 onwards
**Checklist:**

feat: decouple metric collection from emission

---

src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
src/main/java/com/aws/greengrass/util/orchestration/SystemServiceUtils.java
src/main/java/com/aws/greengrass/util/platforms/windows/WindowsPlatform.java

Add the privileged user and group to the system service utility runner so that we run as the privileged user and not the default user. Fixed GenericExternalService on windows to allow for requiresPrivilege. Verified that I'm able to install with WinSW.
**Checklist:**

fix(windows): fix requiresPrivilege for Windows, ensure WinSW runs with privileges

---

src/main/java/com/aws/greengrass/security/CryptoKeySpi.java
src/main/java/com/aws/greengrass/security/SecurityService.java
src/main/java/com/aws/greengrass/security/exceptions/KeyLoadingException.java
src/main/java/com/aws/greengrass/security/exceptions/ServiceProviderConflictException.java
src/main/java/com/aws/greengrass/security/exceptions/ServiceUnavailableException.java
src/test/java/com/aws/greengrass/security/SecurityServiceTest.java

Define CryptoKeySpi and security service interface.
Basic structure of register/deregister crypto key provider with security service.
Define the interface for implementing Greengrass v2 TPM support.
complete unit tests
**Checklist:**

feat: define CryptoKeySpi and security service interface

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java

Speedup AwsIotMqttClientTest from 175 seconds to 7 seconds.
Total time for github CI: 21:13 --> 17:48
**Checklist:**

test: disable rate limiting in AwsIotMqttClientTest

---

src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/main/java/com/aws/greengrass/util/EncryptionUtils.java
src/main/java/com/aws/greengrass/util/ProxyUtils.java
src/test/java/com/aws/greengrass/util/ProxyUtilsTest.java

**Issue #, if available:** N/A
Adds support for HTTPS proxies. Simply add the certificate of the CA that issued the proxy TLS certificate to the file specified in rootCaPath and make sure the networkProxy url config value uses the https scheme.
Code updates:
- Make sure the root CA truststore system property is used in the CRT SDK's HttpProxyOptions.
- Make sure the root CA truststore is combined with the JVM default truststore and used in the AWS SDK's SdkHttpClient.
- Modify device provisioning helper to preserve contents of truststore if it exists and remove duplicates.
This is required in case customers operate in an environment where remote calls must traverse an HTTPS proxy
Manually tested …

feat(proxy): add support for https proxies

---

src/main/java/com/aws/greengrass/componentmanager/ClientConfigurationUtils.java
src/main/java/com/aws/greengrass/security/CryptoKeySpi.java
src/main/java/com/aws/greengrass/security/SecurityService.java
src/main/java/com/aws/greengrass/util/EncryptionUtils.java
src/main/java/com/aws/greengrass/util/ProxyUtils.java
src/test/java/com/aws/greengrass/security/SecurityServiceTest.java
src/test/java/com/aws/greengrass/util/EncryptionUtilsTest.java

Implement default file based crypto key service provider.
register it with SecurityService at the construction time so it's always available.
Default file based crypto key provider will keep the existing key loading process same.
Added unit test. The code is not added to use case code path yet.
**Checklist:**

feat: implement default file based crypto key service provider

---

src/integrationtests/java/com/aws/greengrass/integrationtests/BaseITCase.java
src/integrationtests/java/com/aws/greengrass/integrationtests/componentmanager/ComponentManagerIntegTest.java
src/main/java/com/aws/greengrass/util/Permissions.java
src/main/java/com/aws/greengrass/util/platforms/windows/WindowsPlatform.java
src/main/java/com/aws/greengrass/util/platforms/windows/WindowsUserAttributes.java
src/test/java/com/aws/greengrass/util/PermissionsTest.java
src/test/java/com/aws/greengrass/util/platforms/windows/WindowsPlatformTest.java

On Windows, a file/directory's owner does not intrinsically have any permissions. Their permissions still must be granted through an ACL just like any other user. We have code to set the owner of files which we use on Unix to quickly change permissions without knowing what the permissions ought to be (we only know that the new owner should retain the old owner's rights). 
In this change, I implement setowner on Windows to copy the ACL from the old owner over to the new owner so that it effectively works in the same way as it would on unix.
**Checklist:**
By submitting this pull request, I confirm …

fix(windows): move file permissions from old owner to new owner

---

src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java

Recipe variable regex did not allow for `-` in component names and namespace. This change adds `-` to the supported list.
**Checklist:**

fix(recipe): support hyphen in recipe variable regex

---

src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java
src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java

Make KernelConfigResolver#updateRunWith handle `windowsUser` as well.
Otherwise the `windowsUser` config is never applied.
**Checklist:**

fix: windowsUser config not resolved

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCAuthorizationTest.java
src/main/java/com/aws/greengrass/ipc/AuthenticationHandler.java

On-demand lambdas append an instance number to their name so that we can tell them apart. Authorization, however, must know the name of the service so that we can lookup the correct accessControl block for the component. This change fixes on-demand lambda authorization by switching registerAuthenticationToken to storing the service's real name via getServiceName.
Added new test.
**Checklist:**

fix(authz): use getServiceName instead of getName to allow for on-demand lambdas

---

pom.xml
src/main/java/com/aws/greengrass/security/CryptoKeySpi.java
src/main/java/com/aws/greengrass/security/SecurityService.java
src/main/java/com/aws/greengrass/util/EncryptionUtils.java
src/test/java/com/aws/greengrass/security/SecurityServiceTest.java
src/test/java/com/aws/greengrass/util/EncryptionUtilsTest.java

Add support to load EC keys for AWS SDK APIs. Also adding `getKeyPair` into the security service and CryptoKeySPI so that it can be used by Secret Manager.
AWS IoT supports EC keys, but Greengrass has not supported them until this change due to us needing to parse the PEM encoded file and properly create the RSA/EC key in memory.
Updated existing tests for RSA keys to add EC key generation and read-back.
**Checklist:**

feat: add EC key support and getKeyPair API to security service

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/SampleJobDocumentRemovingUser.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/SampleJobDocumentWithUser_1.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/SampleJobDocumentWithUser_2.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/CustomerAppStartupShutdown-1.0.0.yaml
src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
src/test/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverterTest.java

- GenericExternalService also requests reinstall if windowsUser config changes, which is same behavior as posixUser
- Update tests
- Fix component not reinstalling on windows when windowsUser config changes.
CI
**Checklist:**

fix: service listen to windowsUser topic

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/BaseE2ETestCase.java
src/main/java/com/aws/greengrass/componentmanager/ClientConfigurationUtils.java
src/main/java/com/aws/greengrass/security/CryptoKeySpi.java
src/main/java/com/aws/greengrass/security/SecurityService.java
src/test/java/com/aws/greengrass/componentmanager/ClientConfigurationUtilsTest.java
src/test/java/com/aws/greengrass/security/SecurityServiceTest.java

Using URI instead of a String since we would just convert it to URI anyway in the implementation.
**Checklist:**

refactor: change security API to accept URI instead of String

---

src/main/java/com/aws/greengrass/componentmanager/ClientConfigurationUtils.java
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/iot/IotConnectionManager.java
src/main/java/com/aws/greengrass/security/SecurityService.java
src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java
src/test/java/com/aws/greengrass/componentmanager/ClientConfigurationUtilsTest.java
src/test/java/com/aws/greengrass/iot/IotConnectionManagerTest.java

609b42fb7178d2a9f7ccebde9fb844317ab635e3 changed static methods into instance methods which broke plugin users that depended on it.
**Checklist:**

fix(compat): partially revert 609b42, keep compatibility

---

src/main/java/com/aws/greengrass/util/platforms/windows/WindowsExec.java

Add a synchronized block in windows createProcess() to remove race condition.
When two processes are created at the same time in windows, they might inherit handles they are not supposed to inherit.
https://www.betaarchive.com/wiki/index.php/Microsoft_KB_Archive/315939
**Checklist:**

fix(windows): prevent race condition in windows createProcess

---

src/main/java/com/aws/greengrass/security/CryptoKeySpi.java
src/main/java/com/aws/greengrass/security/SecurityService.java
src/test/java/com/aws/greengrass/security/SecurityServiceTest.java
src/test/java/com/aws/greengrass/util/EncryptionUtilsTest.java

For PKCS#11, it is difficult or impossible to get the public key for a given private key, so this change adds the certificateUri as an input to `getKeyPair`. This then allows us to implement getKeyPair such that the public key will be extracted from the certificate since the certificate will have been signed by the public key and all the public key information exists in the cert.
Tested with a new test in Secret manager (https://github.com/aws-greengrass/aws-greengrass-secret-manager/pull/60) which verifies that we can encrypt and decrypt secrets using PKCS11.
**Checklist:**
By submitting this pull …

fix: add certificate URI input to getKeyPair in CryptoKeySpi

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java

E2E tests somehow got a NPE when calling `get` on the atomic reference on L715. To help avoiding that, return the boolean we just set.
**Checklist:**

fix: remove potential race condition resulting in NPE

---

src/main/java/vendored/org/apache/dolphinscheduler/common/utils/process/ProcessImplForWin32.java

Trying `getLong(0)` on 32 bit Java installations will fail because the pointer size is only 4 bytes and not 8 bytes. This change adds a check and conversion to use `getInt(0)` when needed.
Tested on windows workspace which previously failed using a 32 bit JVM.
**Checklist:**

fix: make reading pointer value work for 32bit Java

---

src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java

Permission was thought to be needed for GGAD, but after GGAD redesign it is not required.
**Checklist:**

fix(easysetup): remove DescribeCertificate permission that isn't needed

---

.github/workflows/externalPR.yml
src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java

- No retry on top of SDK standard retry when getting thing group info during local deployment
**Checklist:**

fix: reduce retry when getting group info for local deployment

---

conf/recipe.yaml
src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/util/platforms/unix/linux/LinuxSystemResourceController.java
src/test/java/com/aws/greengrass/easysetup/DeviceProvisioningHelperTest.java

-
1. Fix easysetup to not fail on unauthorized error in iam::getPolicy since we have fallback steps in case the IAM getPolicy permissions are not available for provisioning 
2. Make resource limit not enabled log at debug level to reduce noise in logging
3. Fix race condition in adding pid to cgroup, i.e. sometimes a child process is created right when existing pids are being added to the resource limit cgroups, so the child pid is never added to the cgroup by greengrass lifecycle or by linux
4. Nucleus bootstrap command currently uses powershell introducing a hard dependency on it, moving to cmd to avoid that. It includes the same set of steps as linux/earlier powershell script i.e. on bootstrap, remove contents of …

Minor fixes - Provisioning IAM:GetPolicy fallback, Resource limits race condition, Windows bootstrap script dependency on powershell

---

pom.xml

Bumping the device sdk to latest public release version of 1.5.3
To move away from private build of device sdk
mvn package -DskipTests locally
**Checklist:**

build: update device sdk dependency to latest version: 1.5.3

---

src/main/java/com/aws/greengrass/lifecyclemanager/Lifecycle.java
src/main/java/com/aws/greengrass/lifecyclemanager/StateTransitionAllowerService.java
src/test/greengrass-nucleus-benchmark/pom.xml
src/test/java/com/aws/greengrass/lifecyclemanager/LifecycleTest.java
src/test/java/com/aws/greengrass/testcommons/testutilities/GGServiceTestUtil.java

Add an interface to allow a plugin to prevent the state transition of Greengrass services. If any registered allower disallows the state transition, then the state transition will not be allowed to proceed.
**Checklist:**

feat: add interface to enable blocking service state transitions by a plugin

---

src/main/java/vendored/org/apache/dolphinscheduler/common/utils/process/ProcessImplForWin32.java

Properly set the invalid handle value on 32 bit Windows systems. Based on https://github.com/java-native-access/jna/blob/master/contrib/platform/src/com/sun/jna/platform/win32/WinBase.java#L51-L53
Without this change, our code believes that it does not need to create the standard out/error pipes because it thinks that we're passing in a valid handle already, meaning that the process will write to a file which exists instead of pipes that we need to create first.
Verified that logs are provided on both 32 and 64 bit JVMs. Without this change only 64 bit JVMs work properly.
**Checklist:**
By …

fix(win32): set invalid handle value properly on 32 bit systems

---

src/integrationtests/java/com/aws/greengrass/integrationtests/util/ExecIntegTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/util/ExecTest.java
src/main/java/com/aws/greengrass/util/platforms/windows/WindowsExec.java
src/main/java/vendored/org/apache/dolphinscheduler/common/utils/process/ProcessBuilderForWin32.java
src/main/java/vendored/org/apache/dolphinscheduler/common/utils/process/ProcessImplForWin32.java

- Add a new field `defaultEnvironment` to ProcessBuilderForWin32 and accessible via setter.
- In ProcessImplForWin32, apply default env before the env returned by CreateEnvironmentBlock, so that the default does not override user's env.
- Fix default PATH always overriding PATH in user's env
- If we have more default env vars in the future, it'll be handled correctly as well.
- Added a new integ test
**Checklist:**

fix(WindowsExec): env var loading order

---

src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java
src/main/java/com/aws/greengrass/tes/LazyCredentialProvider.java
src/main/java/com/aws/greengrass/tes/TokenExchangeService.java
src/test/java/com/aws/greengrass/tes/CredentialRequestHandlerTest.java
src/test/java/com/aws/greengrass/tes/TokenExchangeServiceTest.java

LazyCredentialProvider was using TokenExchangeService directly which caused TES to be created and stored in the Context. However, since TES wasn't depended on by anything, it was not known by the Nucleus to be a component which shouldn't be removed. Therefore, when a deployment came it, that deployment would remove the config namespace for TES, however TES still had pointers to that now-removed namespace. Because of this, the in-memory representation that TES had about itself differed from the representation of any component outside of TES. In this case, TES believed that it was version 0.0.0, while anyone outside of TES (not going through TES's outdated pointers) would see that the version was properly set to 2.0.3. 
The fix in this …

fix: credential provider should not use TES service directly

---

conf/recipe.yaml

Update the windows bootstrap to copy any existing greengrass.xml file into the new distro location. Without this change, the service will fail to start after updating the Nucleus version on Windows.
@tilo-chen manually verified the fix using a cloud deployment with the new recipe.
**Checklist:**

fix(windows): update bootstrap to copy service XML file

---

src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/main/java/com/aws/greengrass/builtin/services/configstore/ConfigStoreIPCEventStreamAgent.java

Adding `AuthorizationHandler` support for a couple of the cluster operations, namely:
- `UpdateClusterState`
- `SubscribeToClusterStateEvents`
Ideally, a plugin can control the authorization for the IPC operations they provide. For now, without this change, the plugin cannot authorize the operations it supports.
```
mvn test
```
**Checklist:**

chore: adding cluster operation authz

---

src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java
src/test/java/com/aws/greengrass/deployment/DeploymentTaskTest.java

* Given: Deployment Document
* When: `thingGroupHelper.ListThingGroupsForCoreDevice` throws 403 exception
* Then: deployment succeed
Adding test for quick fix done [here](https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1137). Behavior for the test explained above (GIVEN-WHEN-THEN). In the test, `thingGroupHelper.ListThingGroupsForCoreDevice` mocked to throw `GreengrassV2DataException` with status code 403.
The test covers the case where `greengrass:ListThingGroupsForCoreDevice` not granted the deployment will still succeed.
* Manual test by using debugger to double check code run as expected
* `mvn -U -ntp verify` passed …

test: deployment will succeed if `listThingGroupsForDevice` throws 403

---

README_CONFIG_SCHEMA.md
src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java

N/A
Added a new setting, `interpolateConfiguration` to nucleus config that allows configuration to be interpolated during a deployment. Extended interpolation to handle lists.
We want to be able to deploy the LegacySubscriptionRouter in a thinggroup deployment, but have it create subscriptions to device specific topics. For example, we may wish to create a subscription to the thing's shadow topics which currently would either require subscribing all greengrass devices to all thing's shadow changes (through a wildcard subscription) which is obviously untenable, or deploy the LegacySubscriptionRouter component individually to each device. The latter option however means that we have to build up a …

feat: add optional setting to enable interpolation in configuration during deployments

---

pom.xml

Add Add-Opens into the jar manifest in order to allow us to use reflection on Windows to set the FileDescriptor handle field.
Without this change, JDK 17 users on Windows are unable to use Greengrass without adding `--add-opens ...` to their Java command.
**Checklist:**

build: use add-opens in jar to prevent error on JDK 17

---

src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java

Add unit test for config interpolation with nested namespace. Test that for nested variable namespace, the most inner level can still be interpolated. 
Configurations such as `{artifacts:{randomNameSpace:{artifacts:path}}}` will be resolved to `{artifacts:{randomNameSpace:<artifacts-path>}}`
In cross component configuration, `{randomName:{{{PackageB:work:path}:{PackageC:work:path}}:randomVal}}` will be resolved to `{randomName:{{/work/PackageB:/work/PackageC}:randomVal}}`
More test coverage.
Note that self referential configs are only resolved one level; for configs `a=artifacts`, `b= {{configuration:/a}:path}`, b will only …

chore: add unit test for nested namespace in config interpolation

---

src/main/java/com/aws/greengrass/util/platforms/windows/WindowsPlatform.java
src/test/java/com/aws/greengrass/util/platforms/windows/WindowsPlatformTest.java

`WindowsPlatform.java`: Lookup Windows group name "Everyone" and "Administrators" by SID instead of the hard-coded English string.
Non-English Windows versions can have localized name for groups such as "Everyone" and "Administrators". On those Windows versions, nucleus won't be able to install or function.
Manual test with German language Windows EC2 (AMI: `Windows_Server-2019-German-Full-Base-2021.09.15`)
Without this fix the test will fail:
```
[ERROR] Failures:
[ERROR]   WindowsPlatformTest.GIVEN_a_well_known_group_sid_WHEN_lookupGroupByIdentifier_THEN_succeed:292
Expected: "Everyone"
but: was "Jeder"
```
**Any additional information or context required to review …

fix: windows hard coded well-known group name

---

.github/workflows/maven.yml
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

Enable FSS to react to DeviceConfig updates and bring itself online
Currently if device provisioning isn't finished, when FSS starts up, FSS will not be able to start and the device won't be picked up by greengrass cloud. Customers have to restart greengrass to have FSS startup.
This fix enables FSS to watch for changes and bring itself up when provisioning completes.
Manually installed greengrass with a delay in fleet provisioning. Confirmed that device shows up in greengrass cloud after some time. 
**Checklist:** …

fix: enable FSS to react to DeviceConfig updates and bring itself online

---

src/test/java/com/aws/greengrass/telemetry/TelemetryAgentTest.java

Increasing timeout during test in TelemetryAgentTest
Needed to make test more reliable. Currently it has intermittent failures when it hits the timeout. 
**Checklist:**

fix: increase timeout in TelemetryAgentTest to make test more robust

---

src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java

Paths are allowed to be `file://` URIs ever since the PKCS#11 changes, however, those URIs are not acceptable by `Paths.get`. Therefore, the validation in the Greengrass service client is incorrect and will fail when using file URIs.
**Checklist:**

fix: do not try to validate paths in gg service client

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/FleetStatusServiceSetupTest.java

Adding integration tests verifying that FSS reacts to DeviceConfig updates and brings itself online
**Checklist:**

test: integration test verifying that FSS reacts to DeviceConfig updates

---

src/integrationtests/java/com/aws/greengrass/integrationtests/util/ExecTest.java
src/main/java/com/aws/greengrass/util/Exec.java

In console applications `\r` is commonly used to overwrite the previous message and update it, such as when downloading with wget. This can be an issue for Greengrass as we wait for `\n` to trigger the end of line and flush the string builder to the log. This change updates our stdout/stderr reader to treat `\r` more like `\n`. `\r\n` is treated as a single newline as would be expected.
**Checklist:**

fix: process output reader treat \r as \n

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCPubSubTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/pubsub.yaml
src/main/java/com/aws/greengrass/builtin/services/pubsub/PubSubIPCEventStreamAgent.java
src/main/java/com/aws/greengrass/builtin/services/pubsub/SubscriptionTrie.java
src/test/java/com/aws/greengrass/builtin/services/pubsub/PubSubIPCEventStreamAgentTest.java
src/test/java/com/aws/greengrass/builtin/services/pubsub/SubscriptionTrieTest.java

Support MQTT style wildcard in PubSub subscriptions (using + and #) 
Implement a SubscriptionTrie to manage topic insert/search
Update device sdk to 1.6.0-PUBSUB-SNAPSHOT that includes model change for `JsonMessage` and `BinaryMessage` to include `eventTopic`
Now we can only subscribe to some specific topic which does not scale well. With the change we can subscribe to a set of topics using + and # wildcards. e.g. to subscribe to a set of shadow topics for different shadows and operations
mvn -U -ntp verify
Referenced [POC](https://github.com/aws-greengrass/aws-greengrass-nucleus/commit/492407c4972a …

feat: pubsub wildcard support

---

.github/workflows/maven.yml
pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentConfigMergingTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/MultiGroupDeploymentTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/KernelTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/ServiceDependencyLifecycleTest.java

Updates device SDK version to a new snapshot for 1.7.0 which is backward compatible with 1.5.0 (our update to 1.6.0 was rolledback due to test failures due to ABI incompatibility).
Ran this version of the Nucleus which has the newer device SDK with the CLI server that was built against the old version of the Nucleus with the old device SDK. This was previously incompatible due to the changing of the data model setters to return `this`. They no longer return `this` in 1.7.0 which keeps us compatible with 1.5.0.
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, …

chore(deps): update device SDK version

---

src/main/java/com/aws/greengrass/builtin/services/pubsub/PubSubIPCEventStreamAgent.java
src/test/java/com/aws/greengrass/builtin/services/pubsub/PubSubIPCEventStreamAgentTest.java

Set `eventTopic` in `JsonMessage` and `BinaryMessage` for `SubscriptionResponseMessage`
For a pubsub pulish request`SubscriptionResponseMessage` needs to include the exact topic
Complete TODO in https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1148 since SDK is updated
**Checklist:**

feat: set eventTopic in pubsub

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
src/main/java/com/aws/greengrass/componentmanager/DependencyResolver.java
src/main/java/com/aws/greengrass/componentmanager/models/ComponentRequirementIdentifier.java
src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java
src/test/java/com/aws/greengrass/componentmanager/DependencyResolverTest.java

A local deployment allows you to specify version requirements for root components such as ">0.0.0". This works fine, but subsequent non-local deployments failed in `getNonTargetGroupToRootPackagesMap` due to trying to parse `>0.0.0` as a version instead of a version requirement. We ultimately built a requirement from the version in DependencyResolver, so now we just properly construct the version requirement earlier on.
**Checklist:**

fix(deployment): parse non-target group component requirements as requirements, not version

---

src/main/java/com/aws/greengrass/lifecyclemanager/ShellRunner.java

Add the `rootCaPath` config value as environment variable.
We will need the variable to provide connector components the path to proxy certificate bundle in case customer is running behind a proxy.
**Checklist:**

feat: add GG Root CA Path as env variable

---

src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java
src/test/java/com/aws/greengrass/componentmanager/builtins/S3DownloaderTest.java
src/test/java/com/aws/greengrass/util/S3SdkClientFactoryTest.java

Don't construct an S3 client until it is requested. Removes S3 client from cache if region changes.
The HTTP client initialization for the S3 client takes ~5s on rpi3.
It is not necessary to pre-construct an S3 client as that just increase the
service initialization time.
Tested load time on rpi3
This changes behavior of the `getS3Client` to also throw a `DeviceConfigurationException` if the config is invalid.
Previously this getter would always return the last valid client, or null if there never was one.
S3Downloader appears to be the only place that uses this factory.
**Checklist:**
By …

fix: don't initialize S3 client on startup

---

src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
src/test/java/com/aws/greengrass/easysetup/GreengrassSetupTest.java

Closes #1181
- Option is true when an option is supplied with nothing after. ex: --deploy-dev-tools.
- Option is true when an option is supplied with another option after. ex: --deploy-dev-tools --provision
Updated existing test to use the new scheme where a boolean argument is missing.
**Checklist:**

fix: better command line boolean parsing

---

src/main/java/com/aws/greengrass/util/BatchedSubscriber.java
src/test/java/com/aws/greengrass/util/BatchedSubscriberTest.java

Adds a `BatchedSubscriber` utility that allows callers to run a callback *after* a batch of changes have fired, rather than executing potentially expensive work per each change.
Thanks @MikeDombo for suggesting this feature
One use case is in mqtt bridge, where we wish to restart the bridge if a config change is detected. If multiple config changes happen in quick succession, we only want to trigger the restart once.  (development effort is in progress, and this change is intended to be used in mqtt bridge)
Unit tests
**Checklist:** …

feat: batched subscriber

---

src/main/java/com/aws/greengrass/config/PlatformResolver.java
src/main/java/com/aws/greengrass/util/platforms/unix/UnixExec.java
src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java

Decrease startup time ~2 seconds on mac by not using the `id` and `uname` commands on startup. `id` is replaced by JNA `geteuid()/getegid()` and `uname` is not replaced, but is lazy-loaded when it is first needed.
This is where the 2 second gain comes from:
Removes the static block in `UnixExec` which was supposedly a hack to get a good $PATH, but on my mac it just exited 1 so we end up waiting 2 seconds no matter what for no benefit.
**Checklist:**

perf: get Unix username/group using JNA, lazy initialize platform

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/KernelTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/provisioning/ProvisionFromPluginTest.java
src/main/java/com/aws/greengrass/dependency/EZPlugins.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelAlternatives.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
src/test/java/com/aws/greengrass/dependency/EZPluginsTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelLifecycleTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelTest.java
src/test/java/com/aws/greengrass/util/BatchedSubscriberTest.java

Stops scanning the classloader of Nucleus for `@ImplementsService`, rather we have a static list of builtin services. This is useful for performance as scanning the classloader can take a while. It is also useful for static builds (Graal, JamaicaVM) and Android. 
Also falls back to reading the `java.home` system property if we cannot find the Jar path by finding the code location from the classloader. This is to support JamaicaVM.
**Checklist:**

perf: static list of service implementors

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCPubSubTest.java
src/main/java/com/aws/greengrass/builtin/services/pubsub/PubSubIPCEventStreamAgent.java
src/main/java/com/aws/greengrass/builtin/services/pubsub/SubscribeRequest.java
src/main/java/com/aws/greengrass/builtin/services/pubsub/SubscriptionCallback.java
src/main/java/com/aws/greengrass/builtin/services/pubsub/SubscriptionTrie.java
src/test/java/com/aws/greengrass/builtin/services/pubsub/PubSubIPCEventStreamAgentTest.java
src/test/java/com/aws/greengrass/builtin/services/pubsub/SubscriptionTrieTest.java

- Implement the new `ReceiveMode` flag for `SubscribeToTopicRequest` in PubSub agent. 
- Refactor SubscriptionTrie to store the new SubscriptionCallback. 
- Update device SDK snapshot. (which also removes eventTopic from `JsonMessage/BinaryMessage` and adds `MessageContext`)
`ReceiveMode` currently has two modes: 
- `RECEIVE_ALL_MESSAGES`: current behavior, all messages will be received by any subscriber.
- `RECEIVE_MESSAGES_FROM_OTHERS`: messaged will not be sent back to the same component that publishes it.
If ReceiveMode is NOT specified, RECEIVE_MESSAGES_FROM_OTHERS will be used if the subscription topic uses wildcard, and RECEIVE_ALL_MESSAGES will be used otherwise.
The new …

feat: implement receive mode in pubsub

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/mqttclient/MqttTest.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

https://github.com/aws-greengrass/aws-greengrass-shadow-manager/issues/120
`MqttClient` checks the number of subscriptions on a connection as well as any ongoing subscriptions on that connection before closing it.
`AwsIotMqttClient` does not send a connection interrupted callback if the connection was closed on purpose (like on an initial connect for a new connection).
Whenever a subscribing thread gets interrupted in the middle of a subscription, there is a possibility that a newly created MQTT connection gets closed before the original subscription even finishes. This change makes sure that a subscriber will always get a MQTT connection and the `MqttClient` does not close any open connection which …

fix: handle subscription close on purposeful connection interruption

---

assembly.xml
scripts/greengrass.service.procd.template
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/util/orchestration/ProcdUtils.java
src/main/java/com/aws/greengrass/util/orchestration/SystemServiceUtilsFactory.java

Support configuring `procd` system service for OpenWRT.
OpenWRT does not use `systemd` to manage its system services. Instead, it uses `procd`. To support that, we need to add another implementation of `SystemServiceUtils`.
UT passed.
It's also tested by configuring Greengrass as a system service on a device with OpenWRT OS. Checked if Nucleus is still running after reboot or updating configuration.
**Checklist:**

feat: support configuring procd system service for OpenWRT

---

.github/workflows/maven.yml
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/PluginComponentTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/FleetStatusServiceSetupTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/Failure3RollbackDeployment.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/ComponentWithBrokenInstall-1.0.0.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/noMain.yaml
src/main/java/com/aws/greengrass/lifecyclemanager/GreengrassService.java
src/test/java/com/aws/greengrass/builtin/services/pubsub/PubSubIPCEventStreamAgentTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/GreengrassServiceTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/LifecycleTest.java
src/test/java/com/aws/greengrass/testcommons/testutilities/ThreadProtector.java

https://github.com/aws-greengrass/aws-greengrass-nucleus/issues/1168
1. Fixes a bug in which deployment of component with broken install script stuck indefinitely, if the device has no deployment history. Rollback's truncate tlog could not update main's dependency because its modtime was default 1; main was still waiting for the broken component to be ready, and yet the broken component was waiting for main to exit, so rollback was stuck.
2. Fixes a deadlock between `GreengrassService::setupDependencies` & `UpdateSystemPolicyService::runUpdateActions` during deployment. Specific conditions as below. It was not discovered earlier because with `node.getModtime() <= 1` the dependency subscription returns instantly.
>`Nucleus running -> …

fix: allow dependency update with default timestamp

---

pom.xml
src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractSubscribeToCertificateUpdatesOperationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java

Adds initial implementation of CDA integration with IPC. This change authorizes and register CDA component with IPC and  adds handlers to `SubscribeToCertificateUpdates` operation. 
This change exposes a new API over IPC for the server (any mqtt broker) to subscribe to its certificate updates such as generation and rotation from the Greengrass V2 CDA component (aws.greengrass.clientdevices.Auth).
**Checklist:**

feat: add IPC operation for subscribing to cert updates

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCServicesTest.java
src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/main/java/com/aws/greengrass/dependency/Context.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java

Switches to using BatchedSubscriber for authorization policy changes to deduplicate effort when multiple changes occur. Saves method references and lambdas as fields of the class to prevent duplicate subscriptions. There are many cases where I did not change to using a field because the subscription is only added once, in a constructor or in postInject.
**Checklist:**

perf: use BatchedSubscriber for authZ changes

---

THIRD-PARTY-LICENSES
src/main/java/com/aws/greengrass/util/EncryptionUtils.java
src/test/java/com/aws/greengrass/util/EncryptionUtilsTest.java

This change adds a new util function to convert an encoded object (key) to a PEM String using a generic PEM writer, based on RFC 1421. 
Avoids adding bouncy castle as a dependency to perform the same. 
**Checklist:**

feat: add PEM writer util function

---

src/integrationtests/java/com/aws/greengrass/integrationtests/BaseITCase.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java

Add an option to scan our own classpath which was removed by an earlier PR (#1187). This is needed for integration testing of plugins which are in tested from the same classpath as Nucleus.
**Checklist:**

test: scan our own classpath for plugins during integration tests

---

pom.xml
src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractVerifyClientDeviceIdentityOperationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java

Add IPC operation handlers for client device auth calls. 
Needed for mqtt5/BYOB integration. 

  feat: add IPC interface for verifying client device identity 

---

src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandler.java

This change adds a new method `handleRequestAsync` to the `OperationContinuationHandler` of our IPC server. This method returns a completable future which ultimately returns the result. It is optional to implement this method. The reason to use it, is that the IPC request can be handled by a different thread, and thus unblock the SDK's main thread, allowing it to process other requests.
This change enables us to not block the main SDK thread while doing something which would otherwise block. This is needed for our CDA APIs which perform cloud calls which we want to return a result from during the initial IPC request (non-streaming).
Manually updated PubSub server to use …

feat: add handleRequestAsync to IPC OperationContinuationHandler

---

src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractGetClientDeviceAuthTokenOperationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java

Add IPC interface to get client device auth token from CDA. Any authorized non-plugin broker (MQTT5 or BYOB) can use this API to the auth token for the client device by presenting a credential. 
Needed to support MQTT5 and BYOB.

feat: add IPC interface to get client device auth token

---

src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractAuthorizeClientDeviceActionOperationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java

Add IPC interface to authorize client device action using client device auth component.
Needed for integrating MQTT5/BYOB over IPC. 

feat: add IPC interface to authz client device action

---

src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandler.java

Required and tested by https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/68.
This change pulls out the cause from `CompletionException` in our error handler. `CompletionException` is what is returned by `CompletableFuture.handle` or .`exceptionally` rather than the actual cause. …

fix: pull out cause of CompletionException in OperationContinuationHandler

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/util/Utils.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentTaskTest.java

We currently only send last error message from deployment workflow to FSS. This does not give customers enough meaningful information. This change will enable customers to see the chain of error messages instead.

fix: bubble up chain of error messages from deployment workflow

---

src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java

1. Adds subscription to iot data and credential endpoints in `GreengrassServiceClientFactory` so that it re-validates cloud connection when any cloud-related configs change.
2. Validate configs when getting v2 data client or config validation error, instead of whenever a config node change, to  reduce duplicate callbacks.
`GreengrassServiceClientFactory` has incomplete subscription to device configuration on cloud-related configs, so that it may miss the updates from `ProvisioningConfigUpdateHelper::updateNucleusConfiguration` at the end of fleet provisioning and still considers device in an offline state even though it's online.
**Any additional information or context …

fix: avoid NPE in getting v2 data client

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/IotJobsFleetStatusServiceTest.java
src/main/java/com/aws/greengrass/componentmanager/ComponentServiceHelper.java
src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
src/main/java/com/aws/greengrass/deployment/DeploymentDocumentDownloader.java
src/main/java/com/aws/greengrass/deployment/ThingGroupHelper.java
src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java
src/test/java/com/aws/greengrass/componentmanager/ComponentServiceHelperTest.java
src/test/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloaderTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentDocumentDownloaderTest.java

Updating users of GreengrassV2DataClient getGreengrassV2DataClient() to handle a null response.
We've seen NPEs when the client is not retrieved.
- [X ] I confirm that the change is backwards compatible.

fix: handle null ggv2dataclient

---

src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java

Change return type of getConfigValidationError back to String
Return type of getConfigValidationError was recently changed from String to Optional<String>.  This was a regression and means that outside callers need to expect a different return type based on which version of Nucleus is being used. We want to avoid this when possible. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix: change return type of getConfigValidationError back to original

---

pom.xml

chore(deps): update device sdk to 1.8.5

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java

- 
Deduplicate deployments of type SHADOW when it triggers nucleus restart due to bootstrap task/nucleus version update etc, but the deployment resumes after restart when it's put in the deployment queue during launch.
To fix a race condition where deployment finishes and is removed from the queue and the current deployment task tracker and the status has not reached the cloud yet, but the shadow subscriptions are setup and the latest shadow is requested, which does not include the finished status, leading to duplicate deployment workflow execution.
Draft PR waiting for tests. 
**Documentation …

fix(deployment): dedupe shadow deployment that resumes after restart

---

pom.xml

chore(deps): bump device sdk to 1.8.6-SNAPSHOT with JVM shutdown fix

---

pom.xml

Bumping device SDK version to pull in Fix for aws-crt-jni.dll files filling up Windows temp dir. 
https://github.com/aws/aws-iot-device-sdk-java-v2/releases/tag/v1.9.2

chore(deps): update device sdk to 1.9.2

---

src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java

Register CLI operations in the AuthZ handler to support https://github.com/aws-greengrass/aws-greengrass-cli/pull/157

feat: add authZ operations for CLI

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java

1. Reduce default `AwsIotMqttClient` disconnection timeout at close from 30 seconds to 2 seconds;
2. Do not wait for event loop group shutdown.
To reduce the shutdown time of Nucleus.

fix: reduce timeout when closing mqtt client

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/IotJobsFleetStatusServiceTest.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

adding FSS trigger for local deployments and deployments with no component state changes
With this change, local deployments will be reflected in the cloud. 
Cloud team is planning subsequent changes to make local deployment information available to customers through their APIs.
These changes are part of our ongoing improvements to FSS and device health notifications.
UATs will be added separately
Tested locally by temporarily adding logs and confirming that FSS updates were published for local deployments and deployments with no component state changes
**Compatibility …

feat: FSS update triggered by local deployments

---

src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java

Reduce shutdown time by omitting MQTT unsubscribe in DeploymentService.shutdown().
Update unit testing accordingly.
There appears to be an issue in the most recent version of aws-iot-device-sdk (observed after upgrading from 1.8.5 -> 1.9.2), which causes our MQTT unsubscribe to block for the full DEFAULT_MQTT_OPERATION_TIMEOUT=30 seconds under certain conditions.
To work around this issue, this PR removes the MQTT unsubscribe step during service shutdown.
Refer to [Compatibility Guidelines](/COMPATIBILITY.md) …

fix: reduce shutdown time by omitting mqtt unsubscribe

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/PeriodicFleetStatusServiceTest.java

adding integ tests for fss triggered by local deployment

test: adding integ tests for fss triggered by local deployment

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/PeriodicFleetStatusServiceTest.java
src/main/java/com/aws/greengrass/status/FleetStatusDetails.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/main/java/com/aws/greengrass/status/MessageType.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

1. Added `MessageType` enum to represent the trigger of FSS update.
2. Added `messageType` and `timestamps` in `FleetStatusDetails`.
3. Updated relevant tests.
To help service gain better visibility of events on device.
These changes are part of our ongoing improvements to FSS and device health notifications.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

feat: add message type and timestamp in FleetStatusDetails

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentConfigMergingTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/KernelShutdownTest.java
src/main/java/com/aws/greengrass/lifecyclemanager/GreengrassService.java
src/test/java/com/aws/greengrass/lifecyclemanager/SetupDependencyTest.java

-
Handle race condition in reacting to state changes of dependencies
Leads to dependent components sometimes not restarting when hard dependencies restart, or not waiting for hard dependencies to finish required state transition before proceeding with their own state transition.

fix(deps): fix race condition in reacting to state changes for dependencies

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/deployment/MultipleGroupsDeploymentE2ETest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/deployment/ShadowDeploymentE2ETest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/FleetStatusServiceSetupTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/PeriodicFleetStatusServiceTest.java
src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/main/java/com/aws/greengrass/status/model/ChunkInfo.java
src/main/java/com/aws/greengrass/status/model/ComponentStatusDetails.java
src/main/java/com/aws/greengrass/status/model/DeploymentInformation.java
src/main/java/com/aws/greengrass/status/model/FleetStatusDetails.java
src/main/java/com/aws/greengrass/status/model/MessageType.java
src/main/java/com/aws/greengrass/status/model/OverallStatus.java
src/main/java/com/aws/greengrass/status/model/StatusDetails.java
src/main/java/com/aws/greengrass/status/model/Trigger.java
src/main/java/com/aws/greengrass/telemetry/MetricsPayload.java
src/main/java/com/aws/greengrass/util/Chunkable.java
src/main/java/com/aws/greengrass/util/MqttChunkedPayloadPublisher.java
src/test/java/com/aws/greengrass/deployment/IotJobsHelperTest.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

1. Moved all model definitions in FSS to `com.aws.greengrass.status.model`
2. Added chunk info to `FleetStatusDetails`, which is non-null if and only if a FSS complete update message exceeds 128KB size limit 
3. Refactored previous enum `MessageType` into `Trigger` and replaced it with `COMPLETE` or `PARTIAL`
4. Updated tests.
To help service gain better visibility of events on device.
These changes are part of our ongoing improvements to FSS and device health notifications.
Some tests in `EventFleetStatusServiceTest` were flaky because there were also cadence-based updates going on and tests …

feat: add chunk info and reformat message type in FleetStatusDetails

---

src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
src/main/java/com/aws/greengrass/util/orchestration/InitUtils.java
src/main/java/com/aws/greengrass/util/orchestration/ProcdUtils.java
src/main/java/com/aws/greengrass/util/orchestration/SystemServiceUtils.java
src/main/java/com/aws/greengrass/util/orchestration/SystemdUtils.java
src/main/java/com/aws/greengrass/util/orchestration/WinswUtils.java

#1239
This change makes it so that if `--start false` is set with `--setup-system-service true` then the system service is only installed, but not enabled or started.
Current behavior is unintuitive and doesn't really match the help printout for setup which doesn't call out that `--start false` currently doesn't do anything if `--setup-system-service true` is set. I have a usecase where a system reboot happens right after installing greengrass so I want to avoid starting up greengrass until afterwards.
As far as I can tell there weren't existing tests for easysetup, and I don't really have the expertise for creating those kinds of tests from scratch (esp. for handling …

feat: respect --start false when using --setup-system-service true

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/telemetry/TelemetryAgentTest.java
src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/main/java/com/aws/greengrass/builtin/services/telemetry/ComponentMetricIPCEventStreamAgent.java
src/main/java/com/aws/greengrass/ipc/modules/ComponentMetricIPCService.java
src/main/java/com/aws/greengrass/telemetry/MetricsPayload.java
src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractPutComponentMetricOperationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java
src/test/java/com/aws/greengrass/builtin/services/telemetry/ComponentMetricIPCEventStreamAgentTest.java

Add IPC operation handlers for publishing component metrics 
Edit Telemetry metrics payload schema
To allow 1P component to publish metrics

feat: add IPC interface and agent for publishing component metrics

---

conf/recipe.yaml
pom.xml
src/test/greengrass-nucleus-benchmark/pom.xml

chore: bump version to 2.7.0

---

src/main/java/com/aws/greengrass/componentmanager/ClientConfigurationUtils.java
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java

feat: allow Greengrass data endpoint to be configured

---

src/main/java/com/aws/greengrass/lifecyclemanager/KernelCommandLine.java

Do not recreate bootstrap manager on root path changes since it does not interact with root path.
If the loader script is running on a different root path from target config, bootstrap manager is created once when kernel parses arguments, and another time when kernel initializes config from target config that changes the root path. On the second time, bootstrap manager does not load from disk and the list of `BootstrapTaskStatus` is lost; kernel would consider all bootstrap steps finished, request restart, and stuck in an infinite restart loop.
Hence deployment with multiple bootstrap steps to a nucleus that runs loader script on a different path than desired root path would result in infinite restart …

fix: do not recreate bootstrap manager on root path changes

---

src/main/java/com/aws/greengrass/builtin/services/telemetry/ComponentMetricIPCEventStreamAgent.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
src/main/java/com/aws/greengrass/telemetry/MetricsAggregator.java
src/test/java/com/aws/greengrass/builtin/services/telemetry/ComponentMetricIPCEventStreamAgentTest.java

Add resource validation to authorization checks in PutComponentMetric handler.
Add ComponentMetricIPCService to kernel lifecycle. 

feat: PutComponentMetric access control policy validation

---

src/main/java/com/aws/greengrass/componentmanager/ClientConfigurationUtils.java

fix: accept only exactly iotdata rather than something containing

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/PeriodicFleetStatusServiceTest.java

FSS periodic integration test checks if all `GreengrassService` is in the periodic update message. Test is failing intermittently because sometimes an update is triggered and asserted before all services are started. Skipping periodic updates when main is not finished.

test: fix FSS periodic integration test

---

src/main/java/com/aws/greengrass/status/FleetStatusService.java

Removing  duplicate fss messages at nucleus launch

fix: remove duplicate fss messages at nucleus launch

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCComponentMetricsTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/PutComponentMetricsTestUtils.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/putComponentMetric-SM.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/putComponentMetric-invalid-service.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/putComponentMetric-no-acl.yaml
src/test/java/com/aws/greengrass/builtin/services/telemetry/ComponentMetricIPCEventStreamAgentTest.java

Adding integration tests for Business metrics

test: integ tests of putComponentMetric IPC API

---

src/main/java/com/aws/greengrass/lifecyclemanager/UpdateSystemPolicyService.java

Add nullcheck in UpdateSystemPolicyService.discardPendingUpdateAction(...) when using the result of pendingActions.get(...).
Without this change, cancellation deployments can fail, in certain scenarios, due to an internal NullPointerException.
- [x ] I confirm that the change is backwards compatible. …

fix: add nullcheck when discarding action in UpdateSystemPolicyService

---

src/main/java/com/aws/greengrass/telemetry/TelemetryAgent.java
src/test/java/com/aws/greengrass/telemetry/TelemetryAgentTest.java

Add additional check to see if the aggregated metrics map has the current timestamp or not.
Do not publish telemetry if no metrics exist. 

fix: add check in Telemetry agent for timestamp during publish

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/ShadowDeploymentForMosquitto.json
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/DeploymentStatusKeeper.java
src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/main/java/com/aws/greengrass/status/model/DeploymentInformation.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentStatusKeeperTest.java

-
Deployment information in FSS gets inconsistent values for `fleetConfigurationArnForStatus` - deployment(job) id for IoT Jobs and config arn for Shadow deployments. We have both deployment id and config arn available for either type of deployments. This change adds a new key for deployment id and correctly sets id and arn in respective fields.
To make FSS messages more accurate 
By submitting this pull request, I confirm that you can …

fix(fss): correct config arn and add deployment id

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

During context shutdown and Mqtt client closing, do not wait for `AwsIotMqttClient::disconnect`.
Since SDK v1.9.2, once the SDK/CRT has been told to shutdown, we cannot guarantee that the SDK/CRT code will complete as expected because of our JVM access being taken away. However, since the program is shutting down, there should not be a need to wait on the code to finish since it will be terminated and all processes stopped. 
By …

fix: do not wait for mqtt client disconnect on context shutdown

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
src/main/java/com/aws/greengrass/deployment/DeploymentQueue.java
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/model/Deployment.java
src/main/java/com/aws/greengrass/deployment/model/DeploymentTaskMetadata.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
src/test/java/com/aws/greengrass/deployment/DeploymentQueueTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelTest.java

This PR does three things, primarily:
1) modify shutdown logic in KernelLifecycle so the config transaction log is not closed until after service shutdown
2) since the config transaction log is now available during shutdown, update DeploymentService so that the deployment queue is saved to the config during shutdown, and then loaded from the config during startup.
3) re-implement DeploymentService so it handles de-duplication of deployments in the queue.
Without 1 & 2, it is possible to "lose" deployments in the queue because of a kernel shutdown (queued local deployments, in general; or, queued cloud deployments that were received while online, but where the kernel restarts in an offline state).
3 …

fix: save deployment queue during nucleus shutdown; re-implement DeploymentQueue to handle de-duplication

---

src/main/java/com/aws/greengrass/security/SecurityService.java
src/main/java/com/aws/greengrass/security/exceptions/CertificateChainLoadingException.java
src/test/java/com/aws/greengrass/security/SecurityServiceTest.java

- CryptoKey provider interface is updated with the addition of a new API for getting the certificate chain. 
- Adds a new API in SecurityService to get certificate chain using private key and certificate URIs by using the newly updated interface. However, this change is also compatible with older implementations of the providers as certificate chain is obtained by using key manager from the existing APIs. 
- This change is needed for enabling BYOCA feature where customers can provide private key and cert of the CA through file system or HSM. 
**Compatibility …

feat: add a new API for getting the cert chain using security service

---

scripts/loader
scripts/loader.cmd

Resolves #1279 
Loader scripts for Unix and Windows now read $GG_JAVA_EXE (if provided) and will use this as the path for the java executable file. If it is not provided, then it falls back to the existing behavior to try calling "java" which will use the PATH resolution to find java.
This change allows customers to more easily set which Java will be used to run Greengrass itself, without needing to modify $PATH.
Manually tested on Windows and Unix that both defaults (no GG_JAVA_EXE) and custom paths (including with spaces in the exe path for Windows) do work as expected.
**Documentation …

feat(loader): use customer-provided java path (if any)

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/BaseE2ETestCase.java

Ignores: https://github.com/awslabs/aws-c-mqtt/blame/0a70bf814845e487b7e4862af7ad9e4a1199b5f4/source/mqtt.c#L150-L152 which can happen when the MQTT session is restarted as clean (which cancels pending requests).
I have posed a question to the SDK team why we're only seeing this now that we've updated to SDK 1.10.2 though the error code hasn't changed in 2 years.
Manually ran E2E test suite locally and verified no failures.
```
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
``` …

test(e2e): ignore newly seen MQTT error in e2e test

---

src/integrationtests/java/com/aws/greengrass/integrationtests/telemetry/TelemetryAgentTest.java

Newer fixes in Telemetry Agent cause integ tests to be flaky. Attempt to Telemetry Integration test. 

fix: flaky telemetry integ test

---

src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/main/java/com/aws/greengrass/status/model/ChunkInfo.java
src/main/java/com/aws/greengrass/status/model/FleetStatusDetails.java
src/main/java/com/aws/greengrass/util/MqttChunkedPayloadPublisher.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java
src/test/java/com/aws/greengrass/util/MqttChunkedPayloadPublisherTest.java

1. Fixes chunking algorithm in `MqttChunkedPayloadPublisher`. 
2. Adds unit tests.
Previously the chunking algorithm was functionally incorrect because it just distributed payloads evenly into chunks. If there were a single very long payload, the publish request would breach the size limit.

fix: correct mqtt chunking publisher algorithm

---

src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/main/java/com/aws/greengrass/status/model/Trigger.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

1. Attempt to publish fss data triggered by cloud deployment when MQTT connection is interrupted, hence spooling the message.
2. Synchronize all event-triggered FSS update on `updatedServiceSet` so that the tracking set is not modified while an update is ongoing.
Note that a lot of line changes are just indentations, so split view is recommended when reviewing the changes.
To provide better accurate information of deployment result via FSS and improve customer experience of deployment notification on cloud. …

feat: spool fss publish requests triggered by cloud deployment

---

pom.xml

https://github.com/aws/aws-iot-device-sdk-java-v2/releases/tag/v1.10.3
Includes important fix for MQTT disconnection handling.

chore(deps): update device SDK

---

src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java

Reverts #1273 
Manually reverts #1273 to use the ARN as the deployment ID for shadow deployments. `git revert` caused too many conflicts to undo due to all the recent error code changes.
This revert is necessary because the previous PR changed the format of FSS updates in an incompatible way. The `GetDeployment` cloud API always returned "in progress" instead of "completed" for completed shadow deployments.
By submitting this pull …

revert: fix(fss): correct config arn and add deployment id

---

src/main/java/com/aws/greengrass/builtin/services/configstore/ConfigStoreIPCEventStreamAgent.java
src/test/java/com/aws/greengrass/builtin/services/configstore/ConfigStoreIPCEventStreamAgentTest.java

Fixes a race condition which causes this failure: https://github.com/aws-greengrass/aws-greengrass-nucleus/runs/8234655490?check_suite_focus=true.
```
software.amazon.awssdk.eventstreamrpc.UnmappedDataException: Found model-type {aws.greengrass#ConfigurationUpdateEvents} which does not map into Java class: software.amazon.awssdk.aws.greengrass.model.SubscribeToConfigurationUpdateResponse
```
Fixes it by using an atomicboolean which is set to true once the IPC subscription response has been sent to the client. Only when this flag is `true` will a configuration update cause the data to actually send. …

fix(config): race condition when subscribing to changing configuration

---

src/main/java/com/aws/greengrass/deployment/KernelUpdateDeploymentTask.java
src/main/java/com/aws/greengrass/deployment/activator/KernelUpdateActivator.java
src/main/java/com/aws/greengrass/deployment/exceptions/DeploymentException.java
src/main/java/com/aws/greengrass/deployment/model/Deployment.java
src/test/java/com/aws/greengrass/deployment/activator/KernelUpdateActivatorTest.java

1. Save deployment error types across restart.
2. Update unit tests.
Sometimes deployment error type for a given error is generated from runtime context (for example, if a component is broken, we check recipe metadata to see if it's an AWS component). The deployment error type would be lost if nucleus restarts during deployment failure(bootstrap or rollback).
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix: save deployment error type across kernel restart

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/SimpleAppAndCustomerApp.json
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/DeploymentStatusKeeper.java
src/main/java/com/aws/greengrass/deployment/model/DeploymentTaskMetadata.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/main/java/com/aws/greengrass/status/model/DeploymentInformation.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentStatusKeeperTest.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

1. Persist root components of a deployment in kernel config via `DeploymentStatusKeeper`
2. Add a new list `unchangedRootComponents` in deployment FSS update to track root components without state change since last update in the deployment FSS update:
* If a deployment fails, then `unchangedRootComponents` is null;
* if a deployment succeeds, 
* if all root components observed state changes during the deployment, and no component errors during deployment, then `unchangedRootComponents` is an empty list;
* if any root component version is already installed prior to the deployment and in running/finished state, then adds its  name to `unchangedRootComponents`
* if component observes transient errors during a deployment, while another root components are already …

feat: track unchanged components across status updates

---

src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java

-
Fix for reporting config arn correctly for shadow deployments which https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1273/files broke in an attempt to consistently send deployment id and config arn in FSS, this change had to be reverted https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1296/files
Changing the values tracked for deployment id and config arn in deployment metadata also flips the value for config arn in persisted deployment status which is used to populate the reported section of deployment shadow - the key used was 'DeploymentId' but the value used to be the config arn before the commit linked above. In order for that change to work without breaking the …

fix: set and report config arn correctly for shadow deployments

---

src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java
src/test/java/com/aws/greengrass/deployment/activator/KernelUpdateActivatorTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelTest.java

Save deployment error code and error type when a bootstrap step fails.
To persist deployment error codes and error types when a deployment contains multiple bootstrap tasks. It's a follow-up to https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1299.

fix: save deployment error code across bootstrap

---

scripts/loader.cmd
src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/pubsub.yaml
src/main/java/com/aws/greengrass/util/orchestration/WinswUtils.java
src/test/java/com/aws/greengrass/ipc/IPCEventStreamServiceTest.java
src/test/java/com/aws/greengrass/testcommons/testutilities/ThreadProtector.java

#1301.
Fixes `loader.cmd` and service installation when the Greengrass root directory has spaces, such as `C:\Program Files\greengrass`. There are possibly other edge cases where spaces in the path will not work, but this is the initial blocker now removed.
Manually tested on windows by installing Greengrass to program files and validated the Greengrass was able to run. …

fix(windows): fixes for root path with spaces

---

scripts/loader

1. Do not modify launch directory if `SIGTERM` is received.
Before this change, if nucleus is finishing bootstrap steps of a deployment when a SIGTERM is received, the loader script would assume that the nucleus restart failed and roll back launch directory, resulting in deployment failure.
After this change, nucleus would pick up from where it's left in deployment after restart, if a SIGTERM is received.
Windows loader.cmd is handling this scenario correctly and exiting on 130 or -1073741510 without modifying launch directory.
Refer to …

fix: do not modify launch directory if sigterm is received

---

src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java

1. Force built-in services to be singleton.
1. Avoid creating multiple instances of built-in services if any of them is injected.

fix: do not create duplicate builtin services

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java
src/main/java/com/aws/greengrass/lifecyclemanager/Lifecycle.java
src/main/java/com/aws/greengrass/status/model/ComponentStatusDetails.java
src/test/java/com/aws/greengrass/lifecyclemanager/LifecycleTest.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

1. Clean up shadow failure details on deployment success, by setting failure cause to empty string and error stack/type to empty list.
2. Rename `ComponentStatusDetails.statusCode` to `ComponentStatusDetails.statusCodes`
1. Before this change, if a failed shadow deployment is followed by a successful shadow deployment, the device would report `null` for failure detail fields and the updated shadow document would still contain the failure reasons from past deployments. After this change, these fields would be cleaned up on deployment success.
2. Rename `statusCode` to `statusCodes` since it's a list and it conforms to cloud naming.
**Any additional information or context …

fix: clean up shadow failure details on deployment success

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/FleetStatusServiceSetupTest.java
src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/test/java/com/aws/greengrass/deployment/IotJobsHelperTest.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

1. Always initialize overall status to healthy instead of null;
2. Avoid spamming FSS updates when mqtt client disconnects and reconnects without component state change by adding a 60 second time window;
3. Send nucleus launch message at the end of `KernelLifecycle::launch` instead of when setting up iot job communication.
Improve the robustness of FSS. …

fix: FSS robustness improvements

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java

Making this change as a result of discussion with the cloud team.
Before: for a failed deployment, the FSS update field `unchangedRootComponents` is always `null`.
After: `unchangedRootComponents` is populated regardless of deployment failure/success; that way, cloud logic can decide what to do with this information.
There are scenarios where we'd like to update the last-reported-timestamp for unchanged components, even though the deployment failed.  This change provides the necessary information to the cloud. …

fix: send unchangedRootComponents to FSS even when deployment fails

---

src/main/java/com/aws/greengrass/dependency/ComponentStatusCode.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

avoid sending component error codes for states other than ERRORED and BROKEN
Fix typo in status messages

fix: send error code only on errored and broken, fix typo

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentConfigMergingTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/FleetConfigSimpleApp.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/ShadowDeploymentForMosquitto.json
src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java
src/main/java/com/aws/greengrass/deployment/DeploymentConfigMerger.java
src/main/java/com/aws/greengrass/deployment/DeploymentDirectoryManager.java
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/DeploymentStatusKeeper.java
src/main/java/com/aws/greengrass/deployment/DynamicComponentConfigurationValidator.java
src/main/java/com/aws/greengrass/deployment/KernelUpdateDeploymentTask.java
src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java
src/main/java/com/aws/greengrass/deployment/activator/KernelUpdateActivator.java
src/main/java/com/aws/greengrass/deployment/model/Deployment.java
src/main/java/com/aws/greengrass/deployment/model/DeploymentTaskMetadata.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/test/java/com/aws/greengrass/componentmanager/plugins/docker/EcrAccessorTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentStatusKeeperTest.java
src/test/java/com/aws/greengrass/deployment/KernelUpdateDeploymentTaskTest.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

1. Add method `getGreengrassDeploymentId` to retrieve gg deployment id directly from deployment doc;
2. Report gg deployment id in FSS while keeping compatibility with other nucleus functionalities.
3. Updated relevant testings.
FSS would like to report greengrass deployment id on deployment finish events for all deployment types.
Previously FSS is reporting `id` field in `Deployment`, which hosts job id for job deployment and config arn for shadow deployment. However, the `id` field should not be changed since iot job helper uses this field to report job execution status. Creating a new field in deployment details to track greengrass deployment id instead.
Unfortunately `id` field cannot be …

fix: report correct value of deployment id

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java

-
Version env should be set up on launch but with preloaded config.tlog config value does not get updated due to the use of `lookup` then `dflt`
In order to correctly update the ggc_version env var for component processes when they're restarted after version update

fix: update ggc version env on version update

---

src/main/java/com/aws/greengrass/deployment/DeploymentQueue.java
src/main/java/com/aws/greengrass/deployment/model/Deployment.java
src/test/java/com/aws/greengrass/deployment/DeploymentQueueTest.java

1. Updated the replacement criteria in deployment queue to not replace any non-DEFAULT stage deployments.
To avoid offering duplicate shadow deployments if it contains bootstrap components.
For a shadow deployment with bootstrap steps, after bootstrap finishes and kernel launches, kernel initializes the deployment queue with the `KERNEL_ACTIVATION` stage deployment. After `DeploymentService` starts up, it loads from config and replaces the deployment with `DEFAULT` stage deployment, causing `ShadowDeploymentListener` to initialize with a null `lastConfigurationArn` and resubmitting a duplicate deployment.
This change would avoid such replacement.
**Any additional …

fix: do not replace non-default stage deployments in deployment queue

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/config_run_with_user_shell.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/service_with_dynamic_config.yaml
src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java

Currently, a deployment simply updates the configuration of a component, and the component itself is responsible for updating itself appropriately in reaction to that change. What this means is that if a component is updated from v1 to v2, the component will have v2's lifecycle configuration immediately. The component reacts by reinstalling since the version changed. As part of reinstallation, the component will first shutdown. However, the shutdown command that it will use is the shutdown command for v2 because the configuration has already been changed. This means that the process of v1 will try to be stopped by the v2 shutdown script; this may or may not work.
This change fixes this problem by caching the correct shutdown script at …

fix: shutdown external services with the old version of the shutdown command

---

src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/deployment/DeploymentDocumentDownloader.java
src/main/java/com/aws/greengrass/deployment/errorcode/DeploymentErrorCodeUtils.java

1. Parse status codes from greengrass exceptions instead of relying on its type.
Sometimes when a cloud api call fails due to missing permissions, a generic `GreengrassV2DataException` is thrown instead of a specific `AccessDeniedException`, which causes the error code logic to handle it incorrectly.

fix: parse status codes from greengrass cloud exceptions

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/local_store_content/recipes/CustomerApp-1.0.0.yaml
src/main/java/com/aws/greengrass/status/FleetStatusService.java

1. Restrict FSS updates triggered by errored component to only send info of the errored component itself.
2. Updated relevant testing.
If a deployment is in progress, other components in the errored component update would not have the updated fleet config arn. If these other components did not observe state change after the update, the cloud would not display them in console table, due to missing fleet config arn value.
By submitting this pull request, I confirm …

fix: restrict fss errored component triggered update

---

conf/recipe.yaml
pom.xml
src/test/greengrass-nucleus-benchmark/pom.xml

chore: bump version to 2.9.0

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCTestUtils.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/KernelTest.java

Windows tests have been failing sometimes on GitHub runner again. This change aims to resolve 2 common failures which both appear to simply be timeouts that are too short, and not indicative of any true problem.
Fixed non-windows test issue in `GIVEN_service_starts_up_WHEN_startup_times_out_THEN_timeout_error_code_persisted` which got a NPE when reading the status because the countdown happened before the atomicreference was set.
Running GIVEN_expected_state_transitions_WHEN_services_error_out_THEN_all_expectations_should_be_seen in a loop on my workspace shows no errors (ran 100 times). I'll ensure the GitHub runner also passes at least 3 times.
Passes
1. …

test(windows): deflake windows testing, increasing timeouts

---

src/main/java/com/aws/greengrass/util/Utils.java

`Throwable.getMessage()` can return null, specifically it always returns null for NullPointerException. Ironically, this causes a NPE to be thrown from the StringBuilder's constructor. This change protects this method from null messages and will add the exception classname instead of the message when there is no message.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

fix: protect generateFailureMessage from null messages

---

src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java

Remove deployment queue persistence.
Not necessary.

fix: remove deployment queue persistence feature

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/SubGroupDeploymentIntegrationTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/FleetConfigWithSimpleAppv1AndGreenSignal.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/FleetConfigWithSimpleAppv3.json
src/main/java/com/aws/greengrass/deployment/DeploymentDirectoryManager.java
src/main/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverter.java
src/main/java/com/aws/greengrass/deployment/model/DeploymentDocument.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java
src/test/greengrass-nucleus-benchmark/src/main/java/com/aws/greengrass/jmh/packagemanager/DependencyResolverBenchmark.java
src/test/java/com/aws/greengrass/componentmanager/DependencyResolverTest.java

1. Allow subgroup deployment to override parent group components.
2. Enforce deployments to be processed based on creation time sequence. All stale deployments would be rejected.
3. Fleet status update for rejection status would have detailed status.
4. Maintain last rejected deployment record similar to success and failed deployments.
5. Update unit tests for group to last deployment topic lookup in deployment config.
6. Add integration tests for subgroup deployments covering siblings, hierarchical, nested and out-of-order deployment scenarios.
To enable customers troubleshoot and help them reduce their time to recover by empowering them with tools like sub-group deployments. Sub-group deployments …

feat(sub-group deploy): add sub-group deployment feature

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/SubGroupDeploymentIntegrationTest.java
src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
src/main/java/com/aws/greengrass/deployment/errorcode/DeploymentErrorCode.java
src/main/java/com/aws/greengrass/deployment/errorcode/DeploymentErrorCodeUtils.java
src/main/java/com/aws/greengrass/deployment/exceptions/DeploymentRejectedException.java
src/main/java/com/aws/greengrass/deployment/model/DeploymentResult.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentTaskTest.java

1. Enforce deployments to be processed based on creation time sequence. All stale deployments would be rejected.
2. Fleet status update for rejection status would have detailed status.
3. Update unit tests for group to last deployment topic lookup in deployment config.
4. Add integration tests for subgroup deployments out-of-order deployment scenarios.
With the new sub-group deployment feature, a device could receive deployments which override components for one group but these could arrive in different order. The mechanism added in the PR enforce only new deployments to be processed and all stale deployments would get rejected.
**Any additional information or context …

feat(reject deployment): reject stale deployments

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/SubGroupDeploymentIntegrationTest.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java

Rename SUBGROUP_DEPLOYMENTS after terminology alignment to SUB_DEPLOYMENTS.
We are changing the terminology.

feat: use SUB_DEPLOYMENTS term

---

src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java
src/test/java/com/aws/greengrass/telemetry/TelemetryAgentTest.java

Windows tests have been failing sometimes on GitHub runner again. This change aims to resolve 1 failures in TelemetryAgentTest.GIVEN_Telemetry_Agent_WHEN_mqtt_is_interrupted_THEN_aggregation_continues_but_publishing_stops.
Running GIVEN_Telemetry_Agent_WHEN_mqtt_is_interrupted_THEN_aggregation_continues_but_publishing_stops by making a breakpoint to reproduce the problem on both windows and linux. Then adding a countdown latch can fix it. (Due to size limit of a file, I've sent all records on mail. Please check with Chen, Junfu and Kuchibhotla, Navya )
fail test on ubuntu/windows:
https://user-images.githubusercontent.com/112076181/197667970-531d441e-ec24-437e-966e-1b870 …

test: deflake testing, adding a countdown latch

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/UnloadableServiceIntegTest.java
src/main/java/com/aws/greengrass/componentmanager/ComponentStore.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java
src/test/java/com/aws/greengrass/componentmanager/ComponentStoreTest.java

1. Handle empty(corrupted) recipe file correctly when calculating recipe digest while loading plugin components at kernel launch.
Before this change, if a deployed plugin component's locally stored recipe is corrupted and emptied, then kernel launch would fail due to an IllegalArgumentException thrown at `Digest::calculate` and stuck in a restart loop.
After this change, a ServiceLoadException would be thrown and kernel would create a new instance of UnloadableService.
Manually tested the fix. …

fix: handle empty recipe content correctly when calculating digest

---

pom.xml
src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java

updating warning log
bumping awssdk + ggv2-data version
Description of changes:
1. Display a warning in the logs if a discontinued component is deployed
2. Bump version of artifact GreengrassV2-Data to access vendorGuidance field from ResolvedComponentVersion api response
3. Bump version of AWSSDK BOM as a dependency of the GreengrassV2-Data version bump
Previous attempts to bump SDK version led to failure in UATs due to a `Unable to marshall request to JSON: Can not write a field name, expecting a value` [(ref)](https://github.com/aws/aws-sdk-java-v2/issues/3127)
It looks like bumping the GGV2-Data version to 2.17 resolves that issue and UATs for transitive dependencies of Nucleus pass.
Why is this change necessary:
Customers need to be made aware if their …

feat: warning log for discontinued component

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/PluginComponentTest.java
src/main/java/com/aws/greengrass/deployment/bootstrap/BootstrapManager.java
src/test/java/com/aws/greengrass/deployment/bootstrap/BootstrapManagerTest.java

-
If a deployment is about to remove a plugin component, force nucleus restart to unload the plugin's code
Draft PR for discussion and early feedback, fix and test are a little silly, will improve if we decide to take this route
Without this, subsequent deployment of the same plugin can cause unexpected behavior when nucleus hasn't restarted between the the two deployments …

fix: restart nucleus if deployment removes a plugin

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Immediately reject MQTT operations once `close()` has been called on the MQTT client. This should prevent issues when Nucleus is shutting down and applications are calling `unsubscribe` for example.

fix(mqtt): reject MQTT operations once the client is closed

---

src/main/java/com/aws/greengrass/deployment/bootstrap/BootstrapManager.java

#1362 adds a bootstrap when removing plugins, however this is not necessary or desirable when there isn't any plugin actually being removed because the plugin is "builtin" meaning that it is in the plugin directory. This impacts our testing which installs the CLI into the plugin directory, so now all our tests are restarting the Nucleus unnecessarily. …

fix: ignore builtin plugins when bootstrapping

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentConfigMergingTest.java

Updating OSHI, JNA, and device SDK versions. I reviewed all the changes to OSHI, none of the breaking changes should impact us and the fixes that they've made may fix some things that we have seen, such os CPU usage over 100%.

chore(deps): update dependency versions

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentConfigMergingTest.java
src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java

This change updates the `UnixPlatform` implementation for finding child processes so that it does not find processes using `ps`, instead we will use the oshi library that we already depend on to list all child processes.
Resolves #910.
**Checklist:**

fix: read procfs (via oshi) instead of ps to find process tree

---

src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java
src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java

Currently, deployments that want to use config interpolation need to be in 2 stages, 1 to enable interpolation and 2 to use the interpolation. This is a terrible experience.
This change fixes this by looking at the value of the interpolate option in the updated Nucleus configuration if it exists. …

feat: get interpolate config value from new nucleus config when able

---

src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
src/main/java/com/aws/greengrass/componentmanager/plugins/docker/EcrAccessor.java
src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/network/HttpClientProvider.java
src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java
src/main/java/com/aws/greengrass/util/IamSdkClientFactory.java
src/main/java/com/aws/greengrass/util/IotSdkClientFactory.java
src/main/java/com/aws/greengrass/util/ProxyUtils.java
src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java
src/main/java/com/aws/greengrass/util/StsSdkClientFactory.java

Address same memory leak situations as in https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/201.
- Searched for all usages of `.httpClient`and switched to `.httpClientBuilder`
- Deprecated `ProxyUtils::getSdkHttpClient`

fix(sdk-clients): use http client builder to avoid leaks

---

src/main/java/com/aws/greengrass/config/Topics.java
src/test/java/com/aws/greengrass/config/ConfigurationTest.java

Previous error example
```
java.lang.IllegalArgumentException: configuration in services.aws.greengrass.crypto.Pkcs11Provider:{version=services.aws.greengrass.crypto.Pkcs11Provider.version:0.0.0, library=services.aws.greengrass.crypto.Pkcs11Provider.library:/lib64/libsofthsm2.so, _private=services.aws.greengrass.crypto.Pkcs11Provider._private:{_State=services.aws.greengrass.crypto.Pkcs11Provider._private._State:1}, configuration=services.aws.greengrass.crypto.Pkcs11Provider.configuration:null, slot=services.aws.greengrass.crypto.Pkcs11Provider.slot:0, name=services.aws.greengrass.crypto.Pkcs11Provider.name:softhsm_pkcs11, dependencies=services.aws.greengrass.crypto.Pkcs11Provider.dependencies:[]} is already a leaf, cannot become a …
```

fix: do not log full data, only key path in config error

---

src/main/java/com/aws/greengrass/dependency/EZPlugins.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java

Adds a fast path to EZPlugins to load the class based on a Jar manifest entry `GG-Plugin-Class`. Keeps full backward compatibility with existing plugins because we'll try to find the class using this method, but if it fails for any reason at all we will go back to the classpath scanner method.
This saves us quite a lot of time. On my M1 Mac, loading the CLI server from the trusted plugins directory took 190ms without the change and only 27ms with this change. This is an approximate 7x speedup. Real world speedup would be very dependent on the number of plugins, disk speed, and CPU speed.
Plugins must be updated to support this fast path by adding an entry to their manifest like so:
```xml
<plugin> …
```

perf(plugins): add a fast path to load plugins without scanning

---

pom.xml
src/main/java/com/aws/greengrass/dependency/EZPlugins.java

Flip the `isAssignableFrom` to correctly find subclasses/interface implementors. This code is only used for the provisioning plugin which is why it was not found previously. I have now manually tested this with the fleet provisioning by claim plugin so that it now supports the fast loading procedure.
Manually tested loading the fleet provisioning plugin with the GG-Plugin-Class option included in the manifest and observed that the plugin is loaded and starts trying to provision.
Updated integration test plugin jar file to include the GG-Plugin-Class specification so this code path is exercised during testing.
**Any additional information or context required to review …

fix(plugins): flip isAssignableFrom to correctly find implementing classes

---

src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java

Add more logging around the path to "No active component version satisfies the requirements of non-target groups" because it could be caused by many different causes.

fix: add logging around installed component not found

---

src/integrationtests/java/com/aws/greengrass/integrationtests/telemetry/TelemetryAgentTest.java

1. increase timeout on point of failure

test: fix telemetry integ test on windows

---

pom.xml
src/main/java/com/aws/greengrass/dependency/EZPlugins.java

When we load plugins from the trusted plugin directory, we create a single classloader that contains all the Jars. This breaks the new plugin loading logic which assumed there could be only 1 plugin per classloader. This change now properly iterates through all possible entries in order to discover all plugins within a classloader.
Verified locally using fleet provisioning and the CLI and verified that both were loaded at the same time.
Refer to [Compatibility Guidelines](/COMPATIBILITY.md) for more …

fix(plugins): allow multiple GG plugins per classloader

---

src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java
src/test/java/com/aws/greengrass/tes/CredentialRequestHandlerTest.java

Adjust the response TES gives upon encountering expired credentials, such that the response does not contain the expired credentials.  This prevents expired credentials from being logged [later on](https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/4bb96750c21bc02de3fd3fd6182afb8ecba41b46/src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java#L357). …

chore(TES): adjust expired credential response

---

src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java

1. suppress `oshi.util.FileUtil` log level to INFO.
https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/913 switched to oshi library which prints very verbose DEBUG-level logs while reading process info:
```
2022-12-15T00:26:11.975Z [DEBUG] (pool-2-thread-7) oshi.util.FileUtil: Reading file /proc/1129/stat. {}
2022-12-15T00:26:11.975Z [DEBUG] (pool-2-thread-7) oshi.util.FileUtil: Reading file /proc/1129/stat. {}
2022-12-15T00:26:11.975Z [DEBUG] (pool-2-thread-7) oshi.util.FileUtil: Reading file /proc/1130/stat. {}
2022-12-15T00:26:11.975Z [DEBUG] (pool-2-thread-7) oshi.util.FileUtil: Reading file /proc/1130/stat. {}
2022-12-15T00:26:11.975Z [DEBUG] (pool-2-thread-7) oshi.util.FileUtil: Reading file /proc/1131/stat. {} …
```

fix: suppress oshi logs when reading process info

---

src/main/java/com/aws/greengrass/dependency/EZPlugins.java

Trusted plugins are all loaded from the same classloader, rather than having one classloader per plugin. This means that we may fail to find all trusted plugins if the trusted plugins has a mix of plugins with and without GG-Plugin-Class manifest entry. This change has us fallback to classpath scanning if the number of classes found with the fast path does not match the number of jars loaded. This way we can still be fast, but only when all trusted plugins can use the fast path and ensure that we aren't missing any trusted plugins either.
Manually verified with fleet provisioning build that has the manifest entry and CLI which does not have the manifest entry. And …

fix(plugins): safer fallback when missing GG-Plugin-Class

---

src/main/java/com/aws/greengrass/util/ProxyUtils.java

https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1368 disabled idle connection reaper for http clients as a preventive measure against leaking http clients. However, it seems to introduce a new FD leak in long-running deployment tests. Since the original memory leak issue can be resolved without disabling idle connection reaper, putting it back on.
By submitting this pull request, I confirm that you can use, modify, copy, …

fix: use idle connection reaper for http clients

---

pom.xml
src/main/java/com/aws/greengrass/mqttclient/v5/Publish.java
src/main/java/com/aws/greengrass/mqttclient/v5/QOS.java
src/main/java/com/aws/greengrass/mqttclient/v5/Subscribe.java
src/main/java/com/aws/greengrass/mqttclient/v5/Unsubscribe.java
src/main/java/com/aws/greengrass/mqttclient/v5/UserProperty.java

This PR adds classes for publish/subscribe/unsubscribe into the Nucleus so that we will be able to update the MQTT client to support MQTT5 and utilize these models for the public interface. I chose not to extend the existing interfaces and instead create new interfaces because the currently existing interfaces depend on objects that are in the CRT's MQTT 3 implementation such as `QualityOfService` and `MqttMessage`. In order to maintain compatibility with MQTT 3, the MQTT client in Nucleus can be updated to support both `Publish` (v5) and `PublishRequest` (v3) using translation code to copy the common fields. The same will also apply for subscriptions and message receipt events.
**How was this change …

feat(mqtt5): add MQTT 5 publish/subscribe models

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Currently, our MQTT client spawns new connections as needed when each individual connection reaches 50 subscriptions. As subscriptions are then removed, the connections will be closed. Connections will not be closed in a deterministic order. Since connections are not necessarily closed in the reverse order, when we try to spawn a new connection, it determines the next client ID to use by looking only the size of the connection list. This may result in us choosing a client ID which we're already using, thus making the old and new connection unusable due to duplicate client IDs.
**Documentation …

fix(mqtt): ensure new clients are created with unused client IDs

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java

Parenthesis matter.
Validated by running GIVEN_mqttClient_WHEN_subscribe_interrupted_THEN_does_not_close_connection. We had client 11 instead of client 1.

fix(mqtt): add 1 to client ID numerically instead of textually

---

src/main/java/com/aws/greengrass/componentmanager/Unarchiver.java
src/main/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloader.java
src/main/java/com/aws/greengrass/config/ConfigurationWriter.java
src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java

All usages of `newOutputStream` now use `SYNC` write mode so that all writes will be synced to disk as much as we are able to guarantee that.

fix: write files with SYNC in unarchive and download

---

src/main/java/com/aws/greengrass/deployment/errorcode/DeploymentErrorCode.java
src/test/java/com/aws/greengrass/deployment/errorcode/DeploymentErrorCodeUtilsTest.java

- correct the error type of `MULTIPLE_NUCLEUS_RESOLVED_ERROR` 
Previously we wrongly assumed that a deployment can never request two components of Nucleus type.

fix: correct error type of multiple nucleus resolved error

---

src/main/java/com/aws/greengrass/componentmanager/Unarchiver.java
src/main/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloader.java

Increase download/write buffer size to 64K from 1K. 1K is too small to be efficient. Particularly since we're writing to disk with SYNC, we want each write to be as efficient as possible and using 64K blocks should be closer to ideal.
Writing 1GB on mac with 1K buffer size takes 28s. Writing using 8KB buffer takes 4s. Using 64KB takes us to ~1.5s.
Writing 1GB on mac without SYNC using a 1K buffer size takes 2.6s.
By submitting this …

fix: increase file download buffer size

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCMqttProxyTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/telemetry/TelemetryAgentTest.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/IndividualMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/main/java/com/aws/greengrass/mqttclient/PublishRequest.java
src/main/java/com/aws/greengrass/mqttclient/spool/Spool.java
src/main/java/com/aws/greengrass/mqttclient/spool/SpoolMessage.java
src/main/java/com/aws/greengrass/mqttclient/v5/PubAck.java
src/main/java/com/aws/greengrass/mqttclient/v5/PublishResponse.java
src/main/java/com/aws/greengrass/mqttclient/v5/QOS.java
src/main/java/com/aws/greengrass/mqttclient/v5/Subscribe.java
src/main/java/com/aws/greengrass/mqttclient/v5/SubscribeResponse.java
src/main/java/com/aws/greengrass/mqttclient/v5/Unsubscribe.java
src/main/java/com/aws/greengrass/mqttclient/v5/UnsubscribeResponse.java
src/test/java/com/aws/greengrass/builtin/services/mqttproxy/MqttProxyIPCAgentTest.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java
src/test/java/com/aws/greengrass/mqttclient/InMemorySpoolTest.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java
src/test/java/com/aws/greengrass/telemetry/TelemetryAgentTest.java
src/test/java/com/aws/greengrass/util/MqttChunkedPayloadPublisherTest.java

Refactor MQTT client, adding new methods for publish/subscribe/unsubscribe using the new MQTT 5 models. Forward the old interface for those to use the new interface. Functionality should not be any different, we're still only using MQTT 3, just changing the interface.

refactor: initial refactor to support MQTT 5 client

---

README.md

**Description of changes:** Removing an errant apostrophe. This should be the possessive "its", not the contraction "it's."

docs: fix grammar in readme

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/spool/Spool.java

Fix a NPE in the spooler where we get message by ID which could be null. Also adds synchronization when we change the connection object in `establishConnection` to try and resolve a possible race.

fix(spool): check for null message before dropping qos 0

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/mqttclient/MqttTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/mqttclient/MqttClientPublishTest.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/IndividualMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/main/java/com/aws/greengrass/mqttclient/v5/PubAck.java
src/main/java/com/aws/greengrass/mqttclient/v5/Publish.java
src/main/java/com/aws/greengrass/mqttclient/v5/Subscribe.java
src/main/java/com/aws/greengrass/mqttclient/v5/SubscribeResponse.java
src/main/java/com/aws/greengrass/mqttclient/v5/UnsubscribeResponse.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Implements MQTT 5 client and uses it in _all_ cases. Future PR will put the MQTT 5 client behind a flag.
more description to come...
MQTTClient unit and e2e tests are passing.

feat(mqtt5): implement mqtt 5 client

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/BaseE2ETestCase.java
src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/deployment/MultipleDeploymentsTest.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java

Adding new ignore rule for an exception which is thrown by the MQTT 5 client when the client shutsdown while some work is still pending.
Also fixes a possible NPE for a SubscribeResponse found when running the E2E tests.
Ran e2e tests locally to verify this error doesn't cause the tests to fail.

test: ignore MQTT 5 exception when closing connection in test

---

src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
src/main/java/com/aws/greengrass/util/Utils.java
src/test/java/com/aws/greengrass/util/UtilsTest.java

-
Job status detail values have a limit of 1024 chars https://docs.aws.amazon.com/general/latest/gr/iot_device_management.html#iot_device_management_quotas which is currently not respected, can lead to failures in publishing deployment status back. Only truncating these values for Jobs because full messages can still be helpful, and hence are retained for other deployment types and FSS
To avoid failures publishing job status due to large failure messages that exceed the limit. …

fix: truncate job status detail values if over limit

---

conf/recipe.yaml

Fix nucleus bootstrap script for windows to work when there can be spaces in greengrass root path
Published a private component with the following bootstrap script and verified that deployment to update nucleus version passes when there is space in root path. 
{
"bootstrap": {
"requiresPrivilege": "true",
"script": "copy \"{kernel:rootPath}\\alts\\current\\distro\\bin\\greengrass.xml\" \"{artifacts:decompressedPath}\\aws.greengrass.nucleus\\bin\\greengrass.xml\"& del /q \"{kernel:rootPath}\\alts\\current\\*\"&& for /d %x in (\"{kernel:rootPath}\\alts\\current\\*\") do @rd /s /q \"%x\"&& echo {configuration:/jvmOptions} > \"{kernel:rootPath}\\alts\\current\\launch.params\"&& mklink /d \"{kernel:rootPath}\\alts\\current\\distro\" …

fix(windows): bootstrap script works with spaces in root path

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCMqttProxyTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/mqttclient/MqttClientPublishTest.java
src/main/java/com/aws/greengrass/builtin/services/mqttproxy/MqttProxyIPCAgent.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/v5/SubscribeResponse.java
src/test/java/com/aws/greengrass/builtin/services/mqttproxy/MqttProxyIPCAgentTest.java

Updates the IPC MQTT proxy implementation to use MQTT 5 client and models. Makes the subscribe API async so that we don't block the IPC event loop while waiting for the subscription to complete.

feat(mqtt-ipc): mqtt IPC use mqtt 5

---

src/main/java/com/aws/greengrass/builtin/services/mqttproxy/MqttProxyIPCAgent.java
src/test/java/com/aws/greengrass/builtin/services/mqttproxy/MqttProxyIPCAgentTest.java

Fix for https://repost.aws/questions/QU_iodOvRxTSGFKdh45Zle6A#ANpI---mlOTAmOoMEavYqJJQ.
If we call `sendStreamEvent` before we've sent the response to the initial request, the client will throw an error. This change has us drop messages until after the initial response is sent which will then be safe. …

fix(mqtt-ipc): drop messages if the subscription response isn't sent yet

---

src/main/java/com/aws/greengrass/util/ProxyUtils.java

Set http proxy to tunneling mode which is what it would be doing behind the scenes anyway. This is required for MQTT 5 now.

fix(mqtt5): use proxy tunneling mode

---

src/main/java/com/aws/greengrass/config/Configuration.java
src/main/java/com/aws/greengrass/config/ConfigurationReader.java
src/main/java/com/aws/greengrass/config/ConfigurationWriter.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
src/test/java/com/aws/greengrass/config/ConfigurationReaderTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelLifecycleTest.java

1. Refactor config loading logic.
2. Call tlog recovery logic when `config.tlog` file does not exist.
3. Check the existence of `config.tlog.old` before loading `config.tlog`. If the old tlog exists, then last tlog truncation was interrupted and we should overwrite the `config.tlog`.
4. Add `tlog~` in config read supported extension.
5. Improvements to logging.
To fix a bug in current config recovery logic. Today, if `config.tlog` file does not at nucleus start, no backup files are read into the config and kernel launches with an empty config.
Furthermore, the condition of `config.tlog` missing may be triggered if nucleus is terminated during tlog truncation. Specifically, `config.tlog` is moved to `config.tlog.old` and new …

fix: improvements to config loading logic

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/IndividualMqttClient.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqttClientTest.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Implement the basic reconnection logic for the MQTT 5 client for when the configuration changes.

feat(mqtt5): implement reconnect for mqtt 5 client

---

src/main/java/com/aws/greengrass/config/ConfigurationReader.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java

1. Improve logging for recent config loading changes.
Prior to this change, customer will see a series of error logs while running manual installation:
```
2023-02-22T21:59:40.852Z [ERROR] (main) com.aws.greengrass.config.ConfigurationReader: validate-tlog. Transaction log file does not exist at given path. {path=/greengrass/v2/config/config.tlog}
2023-02-22T21:59:40.852Z [ERROR] (main) com.aws.greengrass.config.ConfigurationReader: validate-tlog. Transaction log file does not exist at given path. {path=/greengrass/v2/config/config.tlog~}
2023-02-22T21:59:40.852Z [ERROR] (main) com.aws.greengrass.config.ConfigurationReader: validate-tlog. Transaction log file does not exist at given path. …
```

fix(logging): improve loggings for config loading

---

src/main/java/com/aws/greengrass/deployment/bootstrap/BootstrapManager.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/deployment/bootstrap/BootstrapManagerTest.java

Put MQTT 5 client behind a version flag. Defaulting to MQTT 5 client for now, we will switch to MQTT 3 as the default before releasing publicly. Eventually we will remove the MQTT 3 client and just use the MQTT 5 client.
Switching the version will cause Nucleus to restart as tearing down the old version client and then using the new client (and re-subscribing) is a bit tricky. Customers should very very rarely change their MQTT version, if ever.
Refer to [Compatibility Guidelines](/COMPATIBILITY.md) for more …

feat(mqtt5): make mqtt 5 client optional, default to mqtt 5

---

src/main/java/com/aws/greengrass/util/platforms/windows/WindowsPlatform.java

Lookup SYSTEM username from SID just like we did for the EVERYONE group previously.
Manually verified the lookup works.

fix(windows): lookup SYSTEM username from SID

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java

Fixes possible null pointer exception if we can't find the callback for a given subscription.

fix(mqtt5): prevent npe in unsubscribe

---

src/main/java/com/aws/greengrass/componentmanager/ComponentServiceHelper.java
src/main/java/com/aws/greengrass/componentmanager/exceptions/IncompatiblePlatformClaimByComponentException.java
src/test/java/com/aws/greengrass/componentmanager/ComponentServiceHelperTest.java

Use substring matching to handle the incompatible platform claim and unavailable component exceptions differently, added a new exception class and message to be emitted to console in case of an incompatible platform claim exception
Cloud throws an ItemNotFoundException when resolveComponentCandidates API request is called with an incompatible platform claim. The message which needs to be emitted to the console should different from NoAvailableComponentVersionException in this case …

chore: exception and logging for incompatible platform claim

---

.github/workflows/externalPR.yml

Our integ/unit test comments just stopped working. This PR fixes the workflow to comment again.

ci: fix external PR

---

src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/ComponentStore.java
src/test/java/com/aws/greengrass/componentmanager/ComponentManagerTest.java
src/test/java/com/aws/greengrass/componentmanager/ComponentStoreTest.java
src/test/resources/com/aws/greengrass/componentmanager/test_recipe_metadata_files/MockAWSService@1.0.0-bad-region.metadata.json
src/test/resources/com/aws/greengrass/componentmanager/test_recipe_metadata_files/MockAWSService@1.0.0-invalid-arn.metadata.json
src/test/resources/com/aws/greengrass/componentmanager/test_recipe_metadata_files/MockAWSService@1.0.0.metadata.json

- validate the region of component version arn stored in recipe metadata of local candidate; if it doesn't match, then renegotiate with cloud.
- added unit test
We are seeing on rare occasions when customer launches nucleus in region A whereas the local recipe metadata of a 1p component is pointing to a different region B for local deployment. This changes allows deployment to renegotiate with cloud and get the correct recipe metadata.
By submitting this pull …

fix: re-negotiate with cloud if local recipe metadata contains a mismatched region

---

src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/DependencyResolver.java
src/main/java/com/aws/greengrass/componentmanager/exceptions/NoAvailableComponentVersionException.java
src/test/java/com/aws/greengrass/componentmanager/DependencyResolverTest.java

Change the multi-group dependency resolution to re-resolve all group dependencies by asking the cloud instead of trying to lock to the active version. This change completely removes the INSTALLED_COMPONENT_NOT_FOUND root cause.

fix: change multi-group dependency resolution

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Remove the mqtt message from the spooler when we run out of retries.

fix(spool): remove message when retries run out

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/main/java/com/aws/greengrass/mqttclient/v5/PubAck.java
src/main/java/com/aws/greengrass/mqttclient/v5/SubscribeResponse.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Do not retry certain MQTT 5 publish errors. Also includes #1427 to remove messages from the spooler when we drop a message.

feat(mqtt5): smarter publish retries with reason code

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java

fix: validate mqtt topic is not empty

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java

Pass in the customer keepalive value to the MQTT 5 client which was missed earlier. Without this, we're getting disconnected from IoT Core every 20 minutes; this seems like an issue with either the CRT or IoT Core.
Ran connected for more than 20 minutes without getting disconnected.

fix(mqtt5): pass in keepalive to mqtt 5 client

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/test/java/com/aws/greengrass/deployment/DeviceConfigurationTest.java

**Description of changes:** Do not validate credential and data endpoints if domain is not an Amazon domain
**Why is this change necessary:** Currently, if a customer wants to configure device with custom domain (not amazonaws.com) endpoints then Nucleus throws a device configuration exception

chore: do not validate device config for custom domain endpoints

---

src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/ComponentServiceHelper.java
src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
src/main/java/com/aws/greengrass/componentmanager/builtins/S3Downloader.java
src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java
src/main/java/com/aws/greengrass/deployment/DeploymentDocumentDownloader.java
src/main/java/com/aws/greengrass/deployment/ThingGroupHelper.java
src/main/java/com/aws/greengrass/deployment/exceptions/RetryableServerErrorException.java
src/main/java/com/aws/greengrass/util/RetryUtils.java
src/test/java/com/aws/greengrass/componentmanager/ComponentManagerTest.java
src/test/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloaderTest.java
src/test/java/com/aws/greengrass/componentmanager/builtins/S3DownloaderTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentDocumentDownloaderTest.java
src/test/java/com/aws/greengrass/deployment/ThingGroupHelperTest.java

1. Add simple util for checking 500 errors
2. Add new exception type to catch 500 erros
3. Throw new exception type to retry

fix: retry on 5xx errors

---

src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java
src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java

`{configuration:}` should interpolate configuration from the root config object. Right now our regex doesn't allow it, which means you would have to put your config under some key, like `{configuration:/abc}`.

fix: update config interpolation regex to allow empty pointer

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java

chore(deps): bump device sdk

---

pom.xml

update snapshot to be `1.12.0-CLI-SNAPSHOT` for `aws-iot-device-sdk`
1.12.0-CLI-SNAPSHOT contains cli option for failure handling policy

chore(cli): update snapshot

---

pom.xml
uat/pom.xml

Add maven central repo into the pom explicitly so that maven can fetch public dependencies.

fix: add maven central explicitly

---

src/test/greengrass-nucleus-benchmark/pom.xml
uat/pom.xml

repo.maven.apache.org's DNS is messed up, so changing over to the preferred repo1.maven.org which is working.

build: add maven repo in more places

---

src/main/java/com/aws/greengrass/config/Configuration.java
src/main/java/com/aws/greengrass/config/ConfigurationReader.java
src/main/java/com/aws/greengrass/config/Node.java
src/main/java/com/aws/greengrass/config/Topic.java
src/main/java/com/aws/greengrass/config/Topics.java
src/main/java/com/aws/greengrass/deployment/activator/DeploymentActivator.java
src/test/java/com/aws/greengrass/config/ConfigurationReaderTest.java
src/test/resources/com/aws/greengrass/config/testSkeleton.tlog
src/test/resources/com/aws/greengrass/config/updateFromTlogTest.tlog

-
If deployment added configuration that is expected to follow the 'Replace' behavior, upon rollback it should be removed, but since rollback is done by performing a merge of the old snapshot, nothing gets removed. This change removes everything from the current Configuration object that is not in the rollback snapshot but its parent node has 'Replace' behavior 
To ensure rollbacks don't leave behind nodes that were newly added by the deployment and prevent scenarios like a faulty lifecycle script left behind still executes after rollback and produces erroneous results 
Tested with unit and user acceptance tests
**Any additional information or context required to review …

fix: remove extra config during deployment rollback

---

src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/util/Permissions.java

Set permission on the private key when we create it to be 600. Remove usage of CommitableFile which isn't necessary and creates a "backup" file that we do not want.
Ran provisioning steps to create the key and validated permission on disk is set to 600.

fix: set private key permission on provisioning

---

src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java
src/main/java/com/aws/greengrass/deployment/ThingGroupHelper.java
src/main/java/com/aws/greengrass/util/RetryUtils.java

1. In `runWithRetry`, remove unnecessary sleep after final retry attempt if it throws a retryable exception.
2. Rename `retryCount` to `maxAttemptCount` in ThingGroupHelper to be more accurate and remove unused function.
Remove unnecessary sleeps in retry util.  
Specifically, if a local deployment is offline, it's always unnecessarily waiting 1 min for listThingGroupsForDevice.
Tested manually. …

fix(retry-util): do not sleep after final retry attempt

---

src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/ComponentStore.java
src/main/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloader.java
src/main/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloaderFactory.java
src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
src/main/java/com/aws/greengrass/componentmanager/builtins/S3Downloader.java
src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DefaultDockerClient.java
src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageDownloader.java
src/main/java/com/aws/greengrass/componentmanager/plugins/docker/exceptions/DockerImageDeleteException.java
src/test/java/com/aws/greengrass/componentmanager/ComponentManagerTest.java
src/test/java/com/aws/greengrass/componentmanager/ComponentStoreTest.java
src/test/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloaderTest.java
src/test/java/com/aws/greengrass/componentmanager/builtins/S3DownloaderTest.java
src/test/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageDownloaderTest.java
src/test/resources/com/aws/greengrass/componentmanager/recipes/Component_recipe_content.yaml

Copied from PR #1352:
When a component which use docker image has been removed, check whether this image being used by other running components，if not, delete this image with docker cli commend rmi.
Before this change, unused images would be left and take lots of space.

feat: remove docker image when component deleted

---

src/main/java/com/aws/greengrass/util/Exec.java

docker compose may ask interactive questions, the only way to prevent this is to close stdin. Closing stdin for all processes since we do not need it and it will avoid interactivity issues in future.

fix: close stdin on launched processes to prevent interactive questions

---

scripts/loader

…loader (#1445)"
This reverts commit 75a5fa27b6b860bfc572d7fd44ac344341fd4c23.
#1445 breaks the loader, reverting it.
```
/home/ec2-user/testResults/fdf350aad81d92b9d9014347357a459392c1dcb7/alts/current/distro/bin/loader: line 10: GG_ROOT:=/home/ec2-user/testResults/fdf350aad81d92b9d9014347357a459392c1dcb7: No such file or directory
/home/ec2-user/testResults/fdf350aad81d92b9d9014347357a459392c1dcb7/alts/current/distro/bin/loader: line 14: LAUNCH_DIR:=/alts/current: No such file or directory
/home/ec2-user/testResults/fdf350aad81d92b9d9014347357a459392c1dcb7/alts/current/distro/bin/loader: line 15: CONFIG_FILE:=: command not found
``` …

revert: #1445 environment variable override in loader script

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java

1. when mqtt5 client reconnect, reuse the old future if it's not completed.
We are observing cloud deployments not reaching test devices on multiple test reports, especially slower device such as rpi3. This is because test device has a configuration change in private key path during initial installation, which triggers a reconnection/reconfiguration of mqtt client. It seems that upon successful reconfiguration of mqtt5 client, the spooler is still blocked waiting for an old/discarded future to complete.
Tested with a local e2e test
Refer …

fix(mqtt5): keep old reference of connectFuture on reconnect

---

pom.xml
src/main/java/com/aws/greengrass/deployment/model/LocalOverrideRequest.java

Reverts #1439 from release branch. Update SDK to 1.12.1-MQTT-SNAPSHOT which fixes the maxReconnectDelay setting (https://github.com/aws/aws-iot-device-sdk-java-v2/pull/417).

chore(deps): update device sdk to 1.12.1-MQTT-SNAPSHOT

---

pom.xml
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractCancelLocalDeploymentOperationHandler.java
src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java

- necessary nucleus changes to support local deployment cancellation.
- update device sdk snapshot
Will be covered by tests in CLI repo. Nucleus changes here are minimal and do not require additional testings.
CLI will offer a deployment object with `isCancelled = true`. When DeploymentService processes the deployment it calls `cancelCurrentDeployment` which handles deployment cancellation regardless of deployment type. The only change required is making sure the deployment status is persisted after cancellation takes effect.
Refer to …

feat: allow local deployment cancellation

---

src/main/java/com/aws/greengrass/util/Exec.java

Nucleus 2.10 closes stdin by default, unfortunately this turns out to be backward incompatible for run scripts which require stdin to stay open but with no data.
This change makes us keep stdin open by default, but it can be closed by setting the java system property `gg.closeStdIn`

fix: do not close stdin except with system property

---

pom.xml

Device SDK version bump to accommodate Cli status and list command APIs
Cli server imports the CRT SDK from Nucleus, so this change is necessary to allow Cli to fetch the correct SDK and API models

chore: device sdk version bump

---

src/main/java/com/aws/greengrass/config/Node.java

Config is supposed to be case insensitive, but childOf was using equals which will care about the case.

fix(config): childOf needs to use equalsIgnoreCase as config is supposed to be case-insensitive

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Add validation that `pingTimeoutMs` is less than `keepAliveMs`
To provide users with a more friendly error message for validation errors

chore: validate pingTimeoutMs and keepAliveMs configuration

---

src/main/java/com/aws/greengrass/mqttclient/spool/Spool.java
src/test/java/com/aws/greengrass/mqttclient/InMemorySpoolTest.java

Modify Spool to only perform a sync of message IDs when called by the Disk Spooler implementation. This is because we don't know if the database for the Disk Spooler implementation would be ready by the time we start with the sync in our initialization. 
Corresponding change needs to be made in aws-greengrass-DiskSpooler to call `executeSync` in it's `startup()`.
By submitting this pull request, I confirm that you can use, modify, …

feat: execute sync when called by disk spooler implementation

---

src/integrationtests/java/com/aws/greengrass/integrationtests/util/ExecTest.java
src/main/java/com/aws/greengrass/util/Exec.java

In `Exec` we read `PATH`, split it up, possibly modify it, then combine it again to pass into subprocesses. In this process we were checking for length>5 before adding the path separator character for some reason... this is not correct and results in the first path entry getting munged if it is less than 5 characters. This change simply starts adding the path separator after the first entry.
Added new test which fails without the change and passes with the change. …

fix: properly recreate PATH environment

---

src/main/java/com/aws/greengrass/util/ProxyUtils.java
src/test/java/com/aws/greengrass/util/ProxyUtilsTest.java

Use URIBuilder instead of manual string manipulation in order to properly encode the userinfo in the proxy environment variable. Add tests for the same, verifying we properly pass down usernames including `@`

fix: use URI builder for proxy, test for @ in username

---

src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelLifecycleTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelTest.java
src/test/resources/com/aws/greengrass/lifecyclemanager/spooler_config.yaml

MQTT Spool fails to locate the specified DiskSpooler Implementation as a Plugin Service, as the logic to find and load Plugins is after we start all the startable services. Startables include the MqttProxyIPCService which needs the Spooler implementation plugin. This behavior is only observed in Integration testing as we look for plugin service in Class path.
Split the startable services and start everything except MqttProxyIPCService before plugins and start MQTT service after the plugins.
Refer to …

feat: split startable services

---

src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java

If the region is changed before iot data endpoint, then validation will fail and the S3 client will cache that failure forever because the region won't be changed again. To fix this, just subscribe to all changes.

fix: s3 client re-validate on change

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Setup change subscriber from the publish queue so that all pending events are cleared before we subscribe
We add validators which turn the paths (example private key path) from relative to absolute paths. This changes the value immediately but it fires a change notification asynchronously. This notification forces a reconfigure which is not required. …

fix: add mqtt change subscribe from publish queue

---

src/main/java/com/aws/greengrass/deployment/bootstrap/BootstrapManager.java
src/main/java/com/aws/greengrass/mqttclient/spool/CloudMessageSpool.java
src/main/java/com/aws/greengrass/mqttclient/spool/InMemorySpool.java
src/main/java/com/aws/greengrass/mqttclient/spool/Spool.java
src/test/java/com/aws/greengrass/deployment/bootstrap/BootstrapManagerTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelTest.java
src/test/java/com/aws/greengrass/mqttclient/InMemorySpoolTest.java

1. Having the sync queue run from Persistent spooler can cause some edge cases which would result in some unwanted scenarios like adding 2 same message IDs into the queue, or failure to add message in DB. These are difficult to debug and would cause unnecessary complexity. Already saw a couple instances while running UATs, like the FSS message is added to spooler when kernel is launched, and this happens even before we complete the sync. This results in failure to add a message with message ID 0, as there's already a message in DB with that ID which was not synced. We can remove this complexity by doing the sync during initialization before any spool message is added/removed from queue. 
2. We need to restart nucleus if Spooler configuration changes include a …

fix: sync spool message queue during initialization

---

src/main/java/com/aws/greengrass/deployment/bootstrap/BootstrapManager.java
src/test/java/com/aws/greengrass/deployment/bootstrap/BootstrapManagerTest.java

We were checking Spooler namespace directly which will always give value null as Spooler Namespace is an object inside MQTT Namespace. This would fail to restart whenever there's a change in Spooler `StorageType`
Get Spooler StorageType from Spooler Namespace inside MQTT Namespace
Tested the behavior via manual deployment …

fix: restart on spooler config chage

---

src/main/java/com/aws/greengrass/mqttclient/spool/Spool.java
src/test/java/com/aws/greengrass/mqttclient/InMemorySpoolTest.java

Given spooler storageType "Disk", and `addMessage` fails for some reason, we add the message to Memory spooler as a fallback. When we call `removeMessageById` it will try to remove message from DiskSpooler with the given ID but message was never added to persistent spooler and instead added to Memory. Due to this, the message will actually never be removed from the memory spooler , which is bad. 
- Always remove message from Memory Spooler.
- Removed a check in `persistentQueueSync` which is never possible now that we moved `persistentQueueSync` back to spooler initialization. Earlier the check was added as we were calling queue sync from Disk Spooler implementation, in that case the condition would have occurred when we restarted the …

fix: always remove message from memory spooler

---

src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageDownloader.java
src/test/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageDownloaderTest.java

Fix the check in `ifImageUsedByOther` so that it _skips_ checking itself rather than _only_ checking itself (which would always be true).
Manually tested as well to ensure it works properly by @yitingb.

fix(docker): correct is image used by others check

---

pom.xml
src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
src/main/java/com/aws/greengrass/deployment/ShadowDeploymentListener.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java
src/test/java/com/aws/greengrass/testcommons/testutilities/ExceptionLogProtector.java

Builderprovider.get() can fail with MqttException which is a runtime exception. This was missed previously and means that it is possible for Greengrass to be in a state where it isn't subscribed to the jobs/shadow topics.
Validated with Kyle that this fully fixes the issue and Greengrass can now retry appropriately.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

fix(mqtt5): catch mqtt builder fails with mqtt exception

---

conf/recipe.yaml
pom.xml
src/test/greengrass-nucleus-benchmark/pom.xml

chore: bump to 2.12

---

src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
src/test/java/com/aws/greengrass/authorization/AuthorizationHandlerTest.java

The authorization policy ID is currently required to be unique within the device. This constraint has no purpose (we don't use the policy ID for anything at all except for logging), and it causes significant customer pain. Simply removing the duplicate check is safe and will positively impact the usability of Greengrass.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

fix(authZ): do not check for duplicate authZ policy IDs

---

src/main/java/com/aws/greengrass/deployment/DeploymentDirectoryManager.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelTest.java

1. If a bootstrap task fails, prepare rollback irrespective if deployment metadata is readable/writable or not
2. If rollback preparation fails, launch Nucleus as default
3. Safe delete deployment metadata from file system before modification
After a restart, if
1. deployment stage is determined to be bootstrap,
2. a pending bootstrap task fails, and
3. persisted deployment metadata file is either missing or corrupted
then Nucleus will end up being stuck in a bootloop, effectively bricking the core device.
Note that simply taking out the rollback preparation step from try block at
https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/main/src/main/java/com/aws/greengrass/lifecyclemanager/Kernel …

fix: do not bootloop if bootstrap fails and deployment metadata is corrupted

---

src/main/java/com/aws/greengrass/status/FleetStatusService.java

- Include New-state components in FSS deployment updates.
If an on-demand lambda component is deployed but not triggered during a deployment, it is kept at NEW state throughout the deployment. Before this change, FSS ignores this component in deployment status update and the component does not show up on console.

fix: report untriggered on-demand lambdas in fss deployment message

---

src/main/java/com/aws/greengrass/mqttclient/spool/Spool.java
src/test/java/com/aws/greengrass/mqttclient/InMemorySpoolTest.java

When GG is offline, or when spool storage is full, we check through all messages to see if i we can remove any QOS 0 message to accommodate the incoming message. This loop reads through all messages in spooler and is heavy as it reads through database, in case its a disk spooler. This was discovered as we saw high CPU usage in the Disk spooler performance tests which ran spooler tests with QOS 1 messages and at 100 TPS in an unstable network (online <-> offline every 5 mins)
1. Have a flag to see if we need to check for QOS 0 messages or not, when the removal method is called. We set the flag to true every time a new message is added to spooler queue, and set it to false at the end of removal method. Basically, a flag saying "do we …

fix: check if qos0 message check is required

---

pom.xml

Bump OSHI lib to 6.4.4 which includes the fix for [process group name queries](https://github.com/oshi/oshi/pull/2407)
In LDAP file systems with large number of users, Nucleus was unable to stop component processes due to a bug in the OSHI lib. OSHI was internally calling `getent passwd` when Nucleus queries [getDescendantProcesses](https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/b5bcec9b1c045da4566b1ae5bbb0cca89f342dc6/src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java#L544). …

chore: bump oshi version

---

assembly.xml
pom.xml

Fix assembly plugin error complaining that there's no id.

fix: maven assembly plugin error

---

src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DefaultDockerClient.java

https://repost.aws/questions/QUsff-SxHZTLe0RWRn1x6nvA

fix: retry docker on dial tcp failure

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqtt5ClientTest.java

#1510
Ignore disconnection when we are disconnecting on purpose.
When the MQTT client disconnects, we call registered callbacks and mark ourselves as offline so that interested people can know this information. When the MQTT client reconnects it will similarly call callbacks and then mark ourselves as online. In this case, we are disconnecting but we're doing so on purpose and therefore we are not actually offline.
By submitting this …

fix(mqtt): ignore user requested stops in mqtt 5 client

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java

When stopping Nucleus' MQTT5 client, use `NORMAL_DISCONNECTION` as disconnect reason.  
Without providing a disconnect reason, CRT will inform IoT Core that disconnect was due to `CONNECTION_LOST`.  This will also prevent onDisconnect callbacks from running during shutdown.
Manually deployed to my AWS account, stopped nucleus, and verified in IoT Core CloudWatch logs (AWSIotLogsV2) via the following query that Nucleus MQTT5 client disconnected with `CLIENT_INITIATED_DISCONNECT`. Also confirmed that without the fix, query returns `CONNECTION_LOST` instead.
```
filter @message like "disconnect"
| fields @timestamp, disconnectReason
``` …

fix: stop mqtt5 IoT core client with normal disconnection

---

scripts/greengrass.service.template

Setting [KillMode=mixed](https://www.freedesktop.org/software/systemd/man/systemd.kill.html#:~:text=If%20set%20to%20mixed%2C%20the%20SIGTERM%20signal%20(see%20below)%20is%20sent%20to%20the%20main%20process%20while%20the%20subsequent%20SIGKILL%20signal%20(see%20below)%20is%20sent%20to%20all%20remaining%20processes%20of%20the%20unit%27s%20control%20group.) to first signal the main Nucleus process to shutdown before killing all children. All child processes will still be killed if they are running, but this gives Nucleus a chance to better control the child lifecycles. …

fix(systemd): use killmode=mixed to signal nucleus first on shutdown

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/KernelShutdownTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/services_startup_with_hard_dep.yaml
src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
src/main/java/com/aws/greengrass/lifecyclemanager/GreengrassService.java
src/main/java/com/aws/greengrass/lifecyclemanager/Lifecycle.java

1. Do not mark dependency ready if it's stopping and previously it errored
2. Improvements to the order of lifecycle close
3. Added integ test.
To improve the accuracy of dependency waiting logic and kernel shutdown order

 fix: improvements to lifecycle transition and shutdown

---

src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java

fix(log): bump ALPN old Java log up to warning

---

pom.xml

The new version of OSHI that we took has a dependency on 5.13 for JNA, thus bumping our version to be compatible. This doesn't impact us negatively right now, but I want to avoid any future issues.

chore(deps): bump JNA version

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/PluginComponentTest.java
src/main/java/com/aws/greengrass/deployment/activator/KernelUpdateActivator.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelAlternatives.java
src/main/java/com/aws/greengrass/lifecyclemanager/exceptions/DirectoryValidationException.java
src/test/java/com/aws/greengrass/deployment/activator/KernelUpdateActivatorTest.java
src/test/java/com/aws/greengrass/deployment/errorcode/DeploymentErrorCodeUtilsTest.java
src/test/java/com/aws/greengrass/testcommons/testutilities/TestUtils.java

1. better error handling for launch directory corrupted error;
2. report a different error code if user is not allowed to change file permission of loader script
3. added unit test
To gain better visibility on why launch directory corrupted during a bootstrap deployment.

fix: better categorization of launch directory corruption error

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DynamicComponentConfigurationValidationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/SubGroupDeploymentIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCTestUtils.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java

Fix ping and keep alive validation logic to allow keep alive of zero.

fix: don't throw when keep alive is zero

---

pom.xml
src/main/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloaderFactory.java
src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
src/main/java/com/aws/greengrass/deployment/DeploymentDocumentDownloader.java
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/deployment/model/S3EndpointType.java
src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java
src/test/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloaderFactoryTest.java
src/test/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloaderTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentDocumentDownloaderTest.java
src/test/java/com/aws/greengrass/util/S3SdkClientFactoryTest.java

Enable s3 endpoint to be configurable, users could merge the s3 endpoint type from configuration to use"REGIONAL" or "GLOBAL". 
This change unblocks VPC users who can only use regional endpoints.

feat(s3Endpoint): enable configurable s3 endpoint as global or regional

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/BaseE2ETestCase.java

1. Run E2E Tests in gamma instead of prod.
https://github.com/aws-greengrass/aws-greengrass-nucleus/commit/63f26abe6e7a15c00fc7ec018ad3bfc423d508a2 is currently only available in gamma.

chore: switch to gamma for e2e test

---

src/main/java/com/aws/greengrass/builtin/services/lifecycle/LifecycleIPCEventStreamAgent.java

To allow plugins to subscribe to update events and defer update without needing to use an IPC client

chore: refactor component update event handlers

---

src/main/java/com/aws/greengrass/componentmanager/builtins/S3Downloader.java

Get a new S3 client during retries to prevent issues from using a possibly closed client.

fix(s3): always get a new S3 client for retries

---

src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java

fix: properly close S3 client

---

src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java

Change Cluster component name to `aws.greengrass.ClusterManager`

chore: change cluster component name

---

src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/main/java/com/aws/greengrass/util/RetryUtils.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

Spooler currently is immediately retrying to connect if the connection fails. This leads to log spam when PKCS11 provider is not ready yet, for example. This change backs off 2 minutes + 10 second random jitter which matches our other backoff strategies for MQTT.

fix(mqtt): backoff and retry spooler connection failure

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/BaseE2ETestCase.java

This reverts commit 07502bdbbcb6848b83581895ec3d8b0451576e34.
Since the S3 endpoint SDK change is available in prod, we no longer need to test in gamma.
Improve E2E test reliability.
Tested locally.

chore: switch back to prod for e2e test

---

src/main/java/com/aws/greengrass/deployment/KernelUpdateDeploymentTask.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelAlternatives.java

Determine if bootstrap on rollback is required when a component errors 3 times and transitions to broken state when activating kernel.
Tested using a UAT which makes 2 deployments
1. Deploys 3 components, all with working bootstrap steps. This deployment completes with success.
2. Deploys 2 components, one with a bootstrap step and the other with a broken startup lifecycle. The second component breaks during the kernel activation stage and triggers a rollback. Before rolling back, `KernelAlternatives` determines if bootstrap rollback is needed and persists rollback bootstrap file if necessary.
With this test setup, Nucleus enters rollback bootstrap deployment stage after preparing rollback and executes bootstrap steps of the …

fix: bootstrap on rollback when component breaks

---

src/main/java/com/aws/greengrass/deployment/bootstrap/BootstrapManager.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelAlternatives.java

Improves the logging in the bootstrap workflow. We should log the reason behind Nucleus determining if bootstrap is required for current/rollback deployment.
Current logging can be misleading.

chore: update logging for bootstrap on rollback

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java
src/test/java/com/aws/greengrass/mqttclient/AwsIotMqtt5ClientTest.java

When MQTT5 client purposefully reconnects, do so with cleanSession=false
To match behavior of MQTT3 client, and improve performance when reconnecting (subscriptions don't need to be made again).

feat(mqtt5): resume session on reconnect

---

src/main/java/com/aws/greengrass/ipc/AuthenticationHandler.java
src/test/java/com/aws/greengrass/lifecyclemanager/LifecycleTest.java

Use overrideValue just to avoid any possibility that the token is somehow outdated.

fix: set auth token using override to avoid any timing issues

---

pom.xml
src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java

This reverts commit ea517c64a7f96ea75085dd1a896abaf0bf005ed1.
We found that the new version of the logger was not causing log rotation problems on windows; rather it was our perf test log reader on windows which prevented the file from closing and thus rotating. That has now been remedied, so adding this back in.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Revert "Revert "chore: upgrade to greengrass logging 2.2.0 (#1509)"

---

.github/workflows/flakeFinder.yaml
src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java

Set AWS_REGION in flake finder so that tests can pass which would fail due to the unexpected missing region.

ci: set AWS_REGION in flaky test finder

---

src/main/java/com/aws/greengrass/builtin/services/mqttproxy/MqttProxyIPCAgent.java
src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java
src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java

In our upgrade from MQTT 3 to MQTT 5, we changed the interface to support MQTT 5 features. This required a layer of indirection and translation which resulted in making a wrapper lambda to translate message types. This wrapper lambda is not deduplicated even if the consumer is the same, a new wrapper would be created each time. This means that the consumer can end up getting called more than once if it calls subscribe more than once. As a solution, we will now deduplicate these wrappers so that only one callback exists for each subscription.
Manually tested by turning off internet while starting GG and observing that the hashcodes for lambdas are the same and that when back online, the consumer is only called one time.
**Why is this …

fix(mqtt3/5): deduplicate subscription callbacks using deprecated API

---

src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java

Read the role alias and thing name directly from config instead of getting it from the on-change event.

fix(tes): read role alias and thing name directly

---

pom.xml

- Bump Greengrass Logging to 2.3.0-SNAPSHOT
- Update to logback clean up behavior to delete old log files by last modified date instead of the expected file name

chore: upgrade greengrass logging to 2.3.0

---

src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/main/java/com/aws/greengrass/status/model/MessageType.java
src/main/java/com/aws/greengrass/status/model/Trigger.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

Combining the fss trigger type `ERRORED_COMPONENT` and `BROKEN_COMPONENT` to one type: `COMPONENT_STATUS_CHANGE` 
We currently only have ERROED and BROKEN trigger types, and it's not enough to cover all component lifecycle. 

feat(fss): update fss trigger type when component status change

---

.github/workflows/flakeFinder.yaml

Fix flake finder to use ubuntu 20 and run with sudo which should fix the failure on cgroups. Flake finder is not passing, but this is improved.
https://github.com/aws-greengrass/aws-greengrass-nucleus/actions/runs/8011866632/job/21886519075?pr=1579
> Running iteration 1 of 10
> Succeeded with no failure …

ci: flake finder use sudo and ubuntu 20

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java

Ignore error from identified flaky test: com.aws.greengrass.integrationtests.lifecyclemanager.GenericExternalServiceIntegTest.GIVEN_running_service_WHEN_run_config_changes_THEN_service_restarts

test: ignore interrupted exception in generic external integ test

---

src/main/java/com/aws/greengrass/componentmanager/builtins/S3Downloader.java

https://github.com/aws/aws-sdk-java-v2/issues/3408.
S3 may throw an error on expired credentials which the client does not handle correctly internally. We need to handle this special case ourselves, and unfortunately we need to check the error message to do it. This change rethrows the expired token error as a retryable exception which will make us get new credentials and then attempt the S3 call again.
By submitting this pull request, …

fix(s3): retry on token expired when downloading from s3

---

src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java
src/main/java/com/aws/greengrass/tes/HttpServerImpl.java
src/main/java/com/aws/greengrass/tes/TokenExchangeService.java
src/test/java/com/aws/greengrass/tes/HttpServerImplTest.java
src/test/java/com/aws/greengrass/tes/TokenExchangeServiceTest.java

Timeout credential requests after 30 seconds. Without this, we can end up with tons of threads all waiting for credentials since a new thread is created for each incoming request and those threads are not interrupted even if the client disconnects (due to a client disconnect).
Also avoiding thread creation entirely by using a single thread for all requests, if we do not have credentials to vend out anyway then blocking additional requests should be fine.
Refer to [Compatibility Guidelines](/COMPATIBILITY.md) …

fix: timeout http server connections when unable to retrieve credentials

---

src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
src/main/java/com/aws/greengrass/easysetup/README.md

…instead of em dash
replaced em dash in `—tes-role-name` with `--tes-role-name`

fix: parameter hyphens for --tes-role-name option

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/SubGroupDeploymentIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/ComponentStatusChangeFleetStatusServiceTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/FleetStatusServiceSetupTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/PeriodicFleetStatusServiceTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/fss_service_10s_recovery.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/fss_service_5s_recovery.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/fss_service_recovery.yaml
src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

1. Once Nucleus finished restarting process and all components are up and running, Nucleus sends an additional fss message to console with all components status
2. Once a component being recovered, Nucleus waits for all other components being recovered and send an additional message notifying all components has been recovered.
We would like to improve our customer experience on sending extra messages indicating when all components in Nucleus are up and running …

feat(fss): update component status for terminal states

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/ComponentStatusChangeFleetStatusServiceTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/FleetStatusServiceSetupTest.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java

…s change message
1. Decrease the wait time to 3s between messages
2. Only wait on component status change messages
Improve synchronization on component status between device and console

perf(fss): decrease wait time to 3s and only wait for component status change

---

pom.xml

Addresses
```
java.lang.IllegalAccessError: class com.aws.greengrass.security.provider.pkcs11.SingleKeyStore (in unnamed module @0x493ca8) cannot access class sun.security.jca.GetInstance (in module java.base) because module java.base does not export sun.security.jca to unnamed module @0x493ca8
```
Rebuilt nucleus and ran using java 17, observed error occurs without the change and error does not occur with the change.
By submitting …

chore: add opens for PCKS11 plugin

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/ComponentStatusChangeFleetStatusServiceTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/fss_service_10s_recovery.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/status/fss_service_5s_recovery.yaml

Change ping method to Start-Sleep for power shell for sleeping
Fix flaky windows integration tests

fix(fss): windows flaky integration test

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/SubGroupDeploymentIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/ComponentStatusChangeFleetStatusServiceTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/status/FleetStatusServiceSetupTest.java
src/main/java/com/aws/greengrass/status/FleetStatusService.java
src/test/java/com/aws/greengrass/status/FleetStatusServiceTest.java

Avoid publishing component status change message until FSS is set up and Nucleus launch message is published.
A deadlock situation can arise if FSS is being set up while a component status change wants to be published during Nucleus startup.

fix: avoid publish until fss is set up

---

src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java

Fix flaky test: https://github.com/aws-greengrass/aws-greengrass-nucleus/actions/runs/8526707392/job/23356528340.
Ran locally 20 times successfully.

test: fix flaky test which sometimes had 4 events instead of 3

---

src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java

New versions of java (or java on windows) has slightly different error messages. Push it down to debug to not worry customers.

fix: ignore client disconnected error message in TES

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java

Fix flake: https://github.com/aws-greengrass/aws-greengrass-nucleus/actions/runs/8635888684 by ignoring unknown user which is happening because the test is over and interrupting getting the user ID.

test: ignore unknown user error that happens after stopping test

---

pom.xml
src/main/java/com/aws/greengrass/builtin/services/telemetry/ComponentMetricIPCEventStreamAgent.java
src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageDownloader.java

Use fips version of aws-crt when possible. Also fixes some incorrect log formatting using %s.

build: use fips version of aws-crt when possible

---

pom.xml
src/main/java/com/aws/greengrass/mqttclient/WrapperMqttClientConnection.java

Immediately decrement the reference count to the WrapperMqttConnection class because it is not a native resource at all. It is just a Java resource which is wrapping the real MQTT client behind the scenes which is already being properly refcounted. This fixes an issue during repeated testing (such as running the FSS test 400+ times) where we would run out of file descriptors because each run allocated a new event loop group which was never able to close. This issue does not impact production because the wrapper MQTT connection is only ever created one time, so we are not leaking anything.
Updates the device SDK to 1.20.3 to get a fix for p521: https://github.com/aws/s2n-tls/pull/4496
**How was this …

fix: cleanup wrapper MQTT resources, update device sdk

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/DependencyDoNothing.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/DependencyRollback.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/EmptyDeployment.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/DependencyOnBreak-1.0.0.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/DependencyOnBreak-1.0.1.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/DependencyOnDependency-1.0.0.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/DependencyOnDependency-1.0.1.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/SoftDependencyOnBreak-1.0.0.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/SoftDependencyOnBreak-1.0.1.yaml
src/main/java/com/aws/greengrass/deployment/activator/DefaultActivator.java
src/main/java/com/aws/greengrass/lifecyclemanager/GreengrassService.java

Before: when there are 2 components, component A is broken and component B has a hard dependency on A, deployment gets stuck if failure handling policy is rollback. After deployment failed and rollback, component B will always waiting for component A to reach desired state. 
Resolve the issue where deployment rollback gets stuck and device can not receive any more new deployments
By submitting this pull request, I confirm that you can …

fix(deployment): do not track dependencies of broken components in rollback

---

src/main/java/com/aws/greengrass/config/Topic.java
src/main/java/com/aws/greengrass/config/Topics.java
src/test/java/com/aws/greengrass/config/TopicsTest.java
src/test/resources/com/aws/greengrass/config/topicsConfig.yaml

- Add function to compare two Topic objects by name and value
- Add function to compare two Topics objects by name and children
Needed to check if the deployment configuration has differences to the device configuration

feat: functions to compare the value of Topic and Topics

---

src/main/java/com/aws/greengrass/status/FleetStatusService.java

If device is initially offline (due to executing provisioning plugin), `isLaunchMessageSent` is never marked as true, which prevents any subsequent FSS updates when device is fully provisioned.
Make sure status updates are published correctly.

fix: set fss launch flag correctly when device is initially offline

---

src/main/java/com/aws/greengrass/deployment/DeploymentDocumentDownloader.java
src/main/java/com/aws/greengrass/deployment/exceptions/RetryableClientErrorException.java
src/main/java/com/aws/greengrass/util/RetryUtils.java
src/test/java/com/aws/greengrass/deployment/DeploymentDocumentDownloaderTest.java
src/test/java/com/aws/greengrass/util/RetryUtilsTest.java

Occasionally a deployment calling `GetDeploymentConfiguration` may receive a 404 because of DDB eventual consistency. Adding retry on 404s instead of failing directly.

fix: retry GetDeploymentConfiguration on 404

---

pom.xml

Remove fips classifier from aws-crt dependency
There is a bug that causes Greengrass to crash on some ARM architecture

fix: remove classifier for aws-crt

---

pom.xml

Revert aws-iot-device-sdk to use version 1.20.1, customer has confirmed Greengrass 2.12.4 is not crashing for them
https://github.com/aws-greengrass/aws-greengrass-nucleus/issues/1622
Fixes Nucleus crashing on Jetson Nano devices

fix: revert aws device sdk to 1.20.1

---

pom.xml

This reverts commit d7de10c06912c810e51f398d74832984ce3c975f.
Needed for secret manager component development.

Revert "fix: revert aws device sdk to 1.20.1 (#1625)"

---

src/main/java/com/aws/greengrass/deployment/DeploymentConfigMerger.java
src/main/java/com/aws/greengrass/deployment/activator/DeploymentActivator.java
src/main/java/com/aws/greengrass/lifecyclemanager/Lifecycle.java
src/test/java/com/aws/greengrass/deployment/DeploymentConfigMergerTest.java
src/test/java/com/aws/greengrass/deployment/activator/KernelUpdateActivatorTest.java

1. Use executor service to execute update action for deployment in a thread to prevent direct interruption
3. Before taking a config snapshot check if the deployment has been cancelled
4. Life Cycle should allow requests to restart / reinstall components that are closing
General changes needed to improve cancelling deployments …

chore: general changes for cancel deployment

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/FleetConfigWithComponentTakesLongToStartup.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/FleetConfigWithComponentTakesLongToStartupAndBrokenService.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/FleetConfigWithComponentTakesLongToStartupNoNotify.json
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/ComponentTakesLongToStartup-1.0.0.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/local_store_content/recipes/ComponentTakesLongToStartup-1.0.1.yaml
src/main/java/com/aws/greengrass/deployment/DeploymentConfigMerger.java
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/activator/DefaultActivator.java
src/test/java/com/aws/greengrass/deployment/DeploymentConfigMergerTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentServiceTest.java

1. Overload `waitForServicesToStart` to check if the Future has been cancelled and exit early
a. Finish removing on next PR for kernel update deployment changes
3. Extracted code from `waitForServicesToStart` to new function `isAllServiceInDesiredState` that checks if all services have reached a desired state
4. Deployment service will now attempt to cancel ongoing deployments
5. Updated log statements to reflect changes
Allows users to cancel their ongoing deployment if it gets stuck or takes longer than expected to complete.
Tested against local UATs
**Compatibility …

feat: allow deployments to cancel while waiting for services to start

---

src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java
src/test/java/com/aws/greengrass/deployment/DeploymentTaskTest.java

If `DefaultDeploymentTask` is interrupted while performing `listThingGroupsForDevice`, forward the interrupt, rather than marking the deployment as `FAILED_NO_STATE_CHANGE`
Customer logs show an `Error occurred while processing deployment` error for a deployment that was actually canceled in favor of a newer deployment.
```
2023-10-13T11:12:30.506Z [INFO] (pool-2-thread-17) com.aws.greengrass.deployment.ThingGroupHelper: get-thing-group-hierarchy. task failed and will be retried. {task-attempt=1}
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: No supported CertificateVerify signature algorithm for RSA  key
at …
```

fix(deployment): forward interrupt from list groups operation

---

src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/util/RootCAUtils.java
src/test/java/com/aws/greengrass/easysetup/DeviceProvisioningHelperTest.java

Refactoring download CA file to root path as a util class since it will be used other than provisioning step
Allowing download multiple CAs to rootCA file.
This change is required to enable fips endpoints, fips priorities CA3 for authentication.
No need integration test since this flow is the same as adding http certificate …

feat(fips): refactor CA downloader, allow downloading multiple CAs

---

src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
src/test/java/com/aws/greengrass/easysetup/DeviceProvisioningHelperTest.java
src/test/java/com/aws/greengrass/easysetup/GreengrassSetupTest.java

1. Get the endpoints from external config file before creating a thing
2. Assign endpoints accordingly
Currently, when customer uses auto provisioning and provide endpoints with init-config, the endpoints will be overwritten when creating thing info. We now check the external config first before creating endpoints for auto provisioning flow
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

feat(fips): accept endpoints from external config

---

src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java

- `sessionExpirySeconds` (nucleus config) - If this value is not configured, we use default time in seconds for the mqtt client session expiry with IoT Core. The default is the maximum time supported by AWS IoT Core which is 604800 seconds (7 days). 
- The value currently used is in minutes (10080 minutes is 7 days), so updating the code to reflect the expiry time in seconds.  
By submitting this pull request, I confirm that you can …

fix: use max session expiry sec supported by AWS IoT Core

---

src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/deployment/bootstrap/BootstrapManager.java
src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java
src/main/java/com/aws/greengrass/util/RootCAUtils.java
src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java
src/test/java/com/aws/greengrass/deployment/bootstrap/BootstrapManagerTest.java

1. Combined update device configuration based on existing system property
2. When fips mode is true, download root ca 3 to support iot endpoint
3. When fips is enabled, override the `GreengrassV2DataClient` endpoint with `endpointProvider` 
4. Refresh S3 cached client when `fipsMode` change
This is to support new config fipsMode and to ensure all clients in Nucleus supports fips endpoint
By submitting this pull request, I confirm that …

feat(fips): enable fips support deployment flow

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/PluginComponentTest.java

- Device SDK changes for secret manager are included in 1.21.0 version.
- Update zt-process-killer to patch [CVE-2021-29425](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-29425)

chore: update device sdk and process killer lib versions

---

pom.xml

Imported new crt version which fixes the jetson nano incompatible problem

chore: bump crt version

---

pom.xml
src/main/java/com/aws/greengrass/deployment/DeploymentDocumentDownloader.java

N/A.
Bump up the version of greengrass-data and bom.
Ran end-to-end tests to ensure no regression introduced in this dependency bump.

chore: bump up greengrassv2-data to 2.27.x and aws sdk bom to 2.27.x

---

scripts/loader
src/main/java/com/aws/greengrass/deployment/KernelUpdateDeploymentTask.java
src/main/java/com/aws/greengrass/deployment/activator/KernelUpdateActivator.java
src/test/java/com/aws/greengrass/deployment/KernelUpdateDeploymentTaskTest.java
src/test/java/com/aws/greengrass/deployment/activator/KernelUpdateActivatorTest.java

Nucleus returns 1 when it exits unexpectedly. 3 consecutive such exits during a deployment causes the loader to orchestrate a forced rollback. Nucleus, after rolling back, fails the ongoing deployment with a NUCLEUS_RESTART_FAILURE. A caveat here is if Nucleus is unable to persist stage details in deployment metadata during a normal rollback, Nucleus still fails a deployment with NUCLEUS_RESTART_FAILURE after rolling back, which is inaccurate.
In this change, the loader script touches a panic file before orchestrating a forced rollback. Nucleus looks for this panic file after starting up and fails a deployment with NUCLEUS_RESTART_FAILURE only if it finds this file. Any other reason for restart failure should come under device IO …

fix: separate nrf due to nucleus exit

---

src/main/java/com/aws/greengrass/deployment/model/S3EndpointType.java

Introduced new config parameter `DUALSTACK` to `s3EndpointType`
To fully enable dualstack endpoint, customer need to make a deployment to change the following configurations: 
1. Set `aws.useDualstackEndpoint` to `true` under `jvmOptions`. This setting would enable all the http calls made by aws client to point to dualstack endpoints.
2. Set the `s3EndpointType` to `DUALSTACK`. This configuration will ensure that the pre-signed URLs returned by the AWS Greengrass dataplane API (GetComponentVersionArtifact and GetDeploymentConfiguration APIs) points to dual-stack endpoints for Amazon S3.  …

feat: enable s3 dualstack endpoint with deployment

---

README.md

The markdown file originally contained incorrect spacing, so this PR fixes that

chore: fix spacing in `README`

---

scripts/loader
scripts/loader.cmd

Fixing when the loader touches the panic file in the local file system.
Earlier, loader would have touched a panic file at each closure of the loader process, including a planned or external restart of Greengrass via systemd or wincw. The panic script should only be touched when Nucleus exits unexpectedly.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

chore: fix panic file touch

---

scripts/greengrass.service.template
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/deployment/KernelUpdateDeploymentTask.java
src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelAlternatives.java
src/main/java/com/aws/greengrass/util/LoaderLogsSummarizer.java
src/main/java/com/aws/greengrass/util/NucleusPaths.java
src/main/java/com/aws/greengrass/util/orchestration/InitUtils.java
src/main/java/com/aws/greengrass/util/orchestration/ProcdUtils.java
src/main/java/com/aws/greengrass/util/orchestration/SystemServiceUtils.java
src/main/java/com/aws/greengrass/util/orchestration/SystemdUtils.java
src/main/java/com/aws/greengrass/util/orchestration/WinswUtils.java
src/main/java/com/aws/greengrass/util/platforms/Platform.java
src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java
src/main/java/com/aws/greengrass/util/platforms/windows/WindowsPlatform.java
src/test/java/com/aws/greengrass/componentmanager/ComponentStoreTest.java
src/test/java/com/aws/greengrass/deployment/KernelUpdateDeploymentTaskTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelAlternativesTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java

This modifies the loader script to dump its shell logs into `aws.greengrass.Nucleus.log` file. Nucleus reads this log file and summarizes loader logs as part of the deployment status FSS message in case a deployment finishes with a Nucleus Restart Failure. Nucleus also cleans up this log file while preparing for bootstrap to ensure a fresh set of loader logs for each bootstrap deployment.
Currently, we do not have any mechanism to understand deployment failures due to NRF except chasing customers for loader logs. With this change, a summarized version of loader logs will be published to FSS which we can use to debug NRF failures further. …

feat: pipe system logs to nucleus log path

---

src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/skipif_lifecycle.yaml
src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
src/test/java/com/aws/greengrass/easysetup/DeviceProvisioningHelperTest.java

Currently, when `skipif` evaluates to `true`, `RunStatus` is set to `OK` in the result. But, `RunStatus.OK` is currently not handled in by the Run handler. We could either add a case to handle `OK` or mark the skipif `RunStatus` to `NothingDone`.  
This doesn't impact INSTALL lifecycle as it only cares when `RunStatus` is `Errored`. SkipIf result is also not used in shutdown, recovery lifecycles. 
https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/fa01ab35e24390dfc64b08c26f5810783f091e6b/src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java#L523-L538 …

fix: mark run as done when skipif is true

---

src/main/java/com/aws/greengrass/componentmanager/exceptions/IncompatiblePlatformClaimByComponentException.java

Currently, if the component  is not supported on the core device platform, the FSS message seen on the console is as follows.
> The version of component requested does not claim platform compatibility. Check whether the platform constraints conflict and that the component platform mentioned in the recipe matches the platform constraints. If the platform constraints conflict, revise deployments to resolve the conflict. Component A claimed platform: os linux, architecture aarch64.
With this change, we include the nucleus runtime of the core device and reformat the existing message. 
> The version of component requested does not claim platform compatibility. Check whether the component platform specifications mentioned in its recipe …

refactor: add platform runtime and fix platform incompatible message

---

src/main/java/com/aws/greengrass/builtin/services/pubsub/SubscriptionTrie.java
src/test/java/com/aws/greengrass/builtin/services/pubsub/SubscriptionTrieTest.java
src/test/java/com/aws/greengrass/easysetup/DeviceProvisioningHelperTest.java

https://github.com/aws-greengrass/aws-greengrass-nucleus/issues/1670
----
**Background**
`PubSubIPCEventStreamAgent` handles all the IPC local pubsub requests. It implements the handlers for `SubscribeToTopicRequest` and `PublishToTopicRequest` where the topics are stored in a `SubscriptionTrie` trie. 
When a topic is subscribed to, it is added to the `SubscriptionTrie` trie where the topic levels as represented as nodes of the trie. When you subscribe to a topic with a handler, the handler is registered as a listener of that topic where the last topic level node of that topic increments its listeners count by 1. So, for a valid topic in a trie, the number of subscriptions count at the last topic level of that topic is greater than or …

fix: prune subscriptions trie when topics are unsubscribed

---

src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/ComponentStore.java
src/main/java/com/aws/greengrass/deployment/errorcode/DeploymentErrorCode.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelAlternatives.java
src/main/java/com/aws/greengrass/lifecyclemanager/exceptions/DirectoryValidationException.java
src/test/java/com/aws/greengrass/deployment/activator/KernelUpdateActivatorTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelAlternativesTest.java

Re create (if not present) and re link the current launch directory symbolic link with the Nucleus package which is currently being executed. This will only be executed if the current launch directory symbolic link does not exist.
If the current Nucleus package in execution does not have a loader file in its un-archived path, un-archive the the current Nucleus package artifact to re-populate the loader paths.
This change is necessary to mitigate deployment failures due to Launch Dir Corrupted.
Refer to …

fix: link launch dir with existing nucleus package if does not exist

---

src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java
src/main/java/com/aws/greengrass/componentmanager/ComponentStore.java
src/main/java/com/aws/greengrass/deployment/activator/KernelUpdateActivator.java
src/main/java/com/aws/greengrass/deployment/errorcode/DeploymentErrorCode.java
src/main/java/com/aws/greengrass/lifecyclemanager/KernelAlternatives.java
src/main/java/com/aws/greengrass/lifecyclemanager/exceptions/DirectoryValidationException.java
src/test/java/com/aws/greengrass/deployment/activator/KernelUpdateActivatorTest.java
src/test/java/com/aws/greengrass/lifecyclemanager/KernelAlternativesTest.java

Re create (if not present) and re link the current launch directory symbolic link with the Nucleus package which is currently being executed. This will only be executed if the current launch directory symbolic link does not exist.
If the current Nucleus package in execution does not have a loader file in its un-archived path, un-archive the the current Nucleus package artifact to re-populate the loader paths.
***Region Issue Fix***
As Device Configuration is getting initialized earlier than expected, Nucleus is picking up the region from env at each restart and committing that into its config with the latest timestamp. Correct region which is actually picked later on from `config.tlog` is discarded as its timestamp being older than …

feat: recover or replace launch dir link if missing 

---

.github/workflows/flakeFinder.yaml
.github/workflows/maven.yml
pom.xml

Add a white line in pom to test AAA for GitFarm.

chore: add white space in pom

---

scripts/greengrass.service.template

https://github.com/aws-greengrass/aws-greengrass-nucleus/issues/1685
`sh -c` creates a new shell process to execute the command which broke how GG systemd handles SIGTERM.
```
systemd
└── sh
└── sh -c
└── greengrass loader
```
Previously before v2.14.0, it was 
```
systemd
└── sh
└── greengrass loader
```
The change uses exec to remove the additional shell process.
Make sure the loader correctly propagates SIGTERM to the java process. …

fix: systemd template should not create child process

---

.github/workflows/flakeFinder.yaml
.github/workflows/maven.yml

Address https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

fix: github ci upload-artifact

---

conf/recipe.yaml

Bump to next minor version.
To fix OTF UAT.
OTF UAT deployments include nucleus by default with the version in the recipe.yaml. If a gamma cloud version of the nucleus also exists, then it will collide with the local version and fail the deployment.

chore: bump to 2.15.0

---

src/main/java/com/aws/greengrass/lifecyclemanager/ShellRunner.java
src/main/java/vendored/com/microsoft/alm/storage/windows/internal/WindowsCredUtils.java

We've seen customers confused when Greengrass fails to create a component process because the component user credentials are not available from windows. 
Part of this confusion is that the Greengrass lifecycle script process creation logs show up in the component log, making it look like an issue with the Component, when it is rather an issue with Greengrass setting up the environment for the component to run. The error log has been updated to clarify that it is coming from the component lifecycle script setup. This change is accurate because ShellRunner is only used in the context of lifecycle steps.
Another part of the confusion is that it is not obvious which credential can't be found. The error log has been updated to …

docs: clarify windows credential errors during lifecycle script process creation

---

src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/tes/TESTest.java
src/main/java/com/aws/greengrass/tes/TokenExchangeService.java
src/test/java/com/aws/greengrass/tes/TokenExchangeServiceTest.java

https://github.com/aws-greengrass/aws-greengrass-nucleus/issues/1690
- Allows TES restart on port changes. This was previously disabled due to https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/349#discussion_r465283877
- Only components with hard dependencies on TES will auto restart when TES port changes. After restart they will be able to access TES from the new port
- Components without hard dependencies on TES will not restart and will lose access to TES. Only after restart will they get the new port.
Allow TES restart in-place on port changes …

fix: allow TES restart on port changes

---

src/main/java/com/aws/greengrass/util/platforms/unix/UnixExec.java
src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java

See #1667 
This PR is a draft, still trying to get this tested on my device. 

Send SIGTERM to parent process

---

src/main/java/com/aws/greengrass/dependency/Context.java
src/main/java/com/aws/greengrass/lifecyclemanager/Kernel.java

When Nucleus is started, all the plugin/builtin Greengrass services are injected twice. These changes help 
**Current flow:**
When Greengrass is restarted, it starts all the auto-startable services in order after locating them from the context. When a service doesn't already exist in the Context, it is created and injected in to the context in the following way:
At a high-level, a new instance of the Service is created as the following:
1. If it exists in the config file under service topic dependencies, it is created after its dependencies are created. 
2. For an external plugin, it is loaded from the plugins path.
3. For a builtin/plugin service, if a constructor with `Topics` exists, an instance of it is created from the …

fix: prevent double injection of service class

---

src/main/java/com/aws/greengrass/deployment/activator/DefaultActivator.java

The method `retainAll` [here](https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/2870f12ff4ae20bc69b64ea409e5634290cf7077/src/main/java/com/aws/greengrass/deployment/activator/DefaultActivator.java#L84) compares objects of the GreengrassService class. If a service is broken from a previous deployment, an incoming deployment will attempt to replace the original and hence, create a new object for the same service. In this scenario, `retainAll` will exclude the broken service in its operations.
Instead of comparing GreengrassService objects directly, compare their names when performing the `retainAll` operation.
**Any additional information or context required …

fix: use service name for service set operations

---

.github/workflows/flakeFinder.yaml
.github/workflows/maven.yml
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCHibernateTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/ServiceDependencyLifecycleTest.java

chore: update ubuntu version
Update ubuntu version to latest due to ubuntu 20 version closing down soon https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/#ubuntu-20-image-is-closing-down
Deleted flaky unit test step where testing when shutting down Nucleus, soft dependency does not wait for customer app to close. The unit test itself is testing the shutdown order, which is not useful to this scenario.  …

chore: update ubuntu version

---

src/main/java/com/aws/greengrass/lifecyclemanager/KernelCommandLine.java

Adds a warning log when potentially
invalid characters are used in a username.
This change aims to raise awareness around invalid user names which can cause component failures.
For Linux [see this](https://systemd.io/USER_NAMES/#:~:text=On%20POSIX%20the%20set%20of,character%20of%20the%20user%20name.) (best doc I could find).
For Windows [see this](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-autologon-username#values). …

chore: add user name character warning

---

src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentConfigMergingTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DynamicComponentConfigurationValidationTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/PluginComponentTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/ServiceDependencyLifecycleTest.java
src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java
src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java
src/main/java/com/aws/greengrass/deployment/DeploymentConfigMerger.java
src/main/java/com/aws/greengrass/deployment/DeploymentService.java
src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
src/main/java/com/aws/greengrass/deployment/activator/DefaultActivator.java
src/main/java/com/aws/greengrass/deployment/activator/DeploymentActivator.java
src/main/java/com/aws/greengrass/deployment/activator/KernelUpdateActivator.java
src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentConfigMergerTest.java
src/test/java/com/aws/greengrass/deployment/DeploymentTaskTest.java
src/test/java/com/aws/greengrass/deployment/activator/KernelUpdateActivatorTest.java

P200769160
Introduce a new configuration for the nucleus component: deploymentConfigurationTimeSource with two possible values: 
* deploymentCreationTime - (Default, current behavior) - When a deployment is processed on a device, the configuration update uses the deployment creation timestamp to resolve conflicts on config keys existing on the device. This ensures a consistent config state when multiple deployments are applied to the same device at the same time. A config value from a deployment will not be overwritten by other deployments with older creation times while this behavior is selected, even if the deployment is processed on the device at a later (more recent) time.
* deploymentProcessingTime - When a deployment is …

feat: add deploymentConfigurationTimeSource configuration

---

src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java

Moved actual deployment config log from debug level to trace level
Printing logs would consume memory usage, in case the configuration is exceptionally large, printing the configuration would increase the memory allocation significantly.

fix: reduce memory footprint of large configuration logs

---

src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java

- SSL certificate errors (AWSIotException/TLSAuthException) now use UNKNOWN_ERROR_CACHE_IN_MIN (5 minutes) instead of immediate expiry
- Prevents excessive bandwidth usage from continuous retry loops when SSL handshake fails
- Maintains proper error caching behavior for connection failures
This resolves an issue where SSL certificate validation failures would bypass
the intended error caching mechanism, causing credential requests to retry
every ~2 seconds instead of respecting the configured 5-minute cache timeout.
any deprecated method or …

fix: Apply proper error caching for SSL certificate failures in TES
