- src/main/java/com/aws/greengrass/builtin/services/pubsub/PubSubIPCEventStreamAgent.java
Catching the case where the topic is null in a publish message so that we can return an appropriate error.
**Checklist:**
> fix: Catch null topic in publish

- src/main/java/com/aws/greengrass/util/S3SdkClientFactory.java
Use the user-provided region for our main S3 client instead of pulling from the region provider. That was initially done so that we could make cross-region S3 calls from EC2, however it seems that was unnecessary since we are now using `getBucketLocation`.
Verified on dev desktop in us-west-2 can pull artifacts when configured with us-east-1/us-east-2.
**Checklist:**
> Use configured region for default S3 client

- src/main/java/com/aws/greengrass/componentmanager/GreengrassComponentServiceClientFactory.java
- src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
Update the GG client when the port changes.
**Checklist:**
> fix: Dynamic reconfigure GG client when port changes

- .github/workflows/maven.yml
Adds commitlint validation to our CI so that it will reject any commits that do not conform to conventional commit format.
**Checklist:**
> ci(commitlint): Add commitlint to CI

- CHANGELOG.md
> chore(release): v2.0.4 release

- CHANGELOG.md
> chore(changelog): update changelog with note

- src/main/java/com/aws/greengrass/componentmanager/Unarchiver.java
Working around [JDK bug](https://bugs.openjdk.java.net/browse/JDK-8143613) which causes `java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor`. The workaround uses the `ZipFile` instead of `ZipInputStream`, but is otherwise the same.
This error can occur when using the AWS CDK to create lambda functions and then deploy the lambda function to a Greengrass device. As a workaround, it is possible to rezip the lambda in a way that Greengrass can read, however this fix is far preferred since it requires no additional customer action.
Manually verified that it is able to unzip zip files generate by the CDK for lambda which was the cause of the problem. …
> fix(unarchive): workaround JDK bug by using ZipFile

- pom.xml
Use a development version of the AWS IoT Device SDK so that we can consume non-public changes for further testing.
**Checklist:**
> chore: use dev snapshot of IPC SDK

- src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
Handle permission error in `iam::GetPolicy` operation during setup so that permissions narrowed down to specific policy work, also not failing on permissions error such that `iam:CreatePolicy` permissions might work even if `iam::GetPolicy` permissions are absent
**Checklist:**
> fix(setup): support iam getPolicy with specific policy permission

- .github/PULL_REQUEST_TEMPLATE.md
**Issue #, if available:** N/A
Adding reminder check for proxy support, if applicable
Contributors might not be aware that remote network calls should also work with a proxy
**How was this change tested:** N/A
**Checklist:**
> Update PR template with proxy item

- CHANGELOG.md
> chore(changelog): v2.0.5 release

- pom.xml
> chore: update snapshot version to 2.1.0

- pom.xml
> chore(sdk): update sdk version

- src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
- src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
Use the newly added MQTT protocol timeout. Also standardizing connection cleanup in the client connection class.
**Checklist:**
> fix(mqtt): use protocol timeout 

- src/main/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloaderFactory.java
- src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DockerApplicationManagerService.java
- src/test/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloaderFactoryTest.java
Changing the component name post internal discussion
**Checklist:**
> chore: rename docker plugin

- pom.xml
> chore(ipc): use release version of ipc

- pom.xml
> chore: update IoT SDK dependency for MQTT race condition fixes

- src/main/java/com/aws/greengrass/config/ConfigurationReader.java
- src/test/java/com/aws/greengrass/config/ConfigurationTest.java
- src/test/java/com/aws/greengrass/config/ConfigurationWriterTest.java
- src/test/java/com/aws/greengrass/ipc/IPCEventStreamServiceTest.java
- src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java
- src/test/java/com/aws/greengrass/util/platforms/windows/WindowsPlatformTest.java
Some of the unit tests are failing on Windows. This PR fixes some of these failures.
We need to enforce unit tests and integration tests on Windows.
This is a recent run on the main branch.
https://github.com/aws-greengrass/aws-greengrass-nucleus/runs/2357902623?check_suite_focus=true#step:6:6867
Compare to the CI run for this PR such as
https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/930/checks?check_run_id=2384727659#step:6:6228
some of the failures are fixed. Other failures will be addressed in later PRs.
**Checklist:** …
> fix(windows): fix some unit tests on Windows

- scripts/loader
> fix(loader): kill nucleus when signaled

- src/main/java/com/aws/greengrass/deployment/activator/DeploymentActivatorFactory.java
- src/main/java/com/aws/greengrass/util/orchestration/SystemServiceUtilsFactory.java
Constructor injection works more nicely as it requires less strong reflection (we're not setting final fields).
**Checklist:**
> refactor: use constructor injection instead of field injection

- src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/deployment/DeploymentE2ETest.java
update e2e model reference to new data plane SDK model
e2e two related test cases are failing because of model mismatch
**Checklist:**
> fix: update e2e model reference to new data plane SDK model

- src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/KernelTest.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/service_error_recovery_step_does_not_fix_service.yaml
These two tests fail on Windows. The PR fixes them.
The tests pass on Windows after this PR.
**Checklist:**
> fix(windows): fix some integration tests running on Windows

- CONTRIBUTING.md
- DEVELOPING.md
> docs: update contribution guidelines

- src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/PluginComponentTest.java
> fix(windows): fix PluginComponentTest

- src/main/java/com/aws/greengrass/util/RetryUtils.java
> fix: add jitter to RetryUtils

- src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
- src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
- src/main/java/com/aws/greengrass/lifecyclemanager/LogManagerHelper.java
- src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java
Cherry pick latest commit from main (#959), to prevent build errors in codebuild.
Description from #959. This is also necessary to prepare Nucleus release 2.2.x for release.
**Checklist:**
> chore: cherry pick commit 959 from main

- pom.xml
- src/main/java/com/aws/greengrass/componentmanager/ClientConfigurationUtils.java
- src/main/java/com/aws/greengrass/componentmanager/builtins/GreengrassRepositoryDownloader.java
- src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
- src/main/java/com/aws/greengrass/util/ProxyUtils.java
> build: remove .a files from jar (#969)

- src/main/java/com/aws/greengrass/util/platforms/unix/linux/LinuxSystemResourceController.java
> fix: flaky test in system limit feature

- src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageArtifactParser.java
- src/test/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageArtifactParserTest.java
Copying the fix that was checked in to main branch to 2.2 release branch  https://github.com/aws-greengrass/aws-greengrass-nucleus/commit/462109bded6ae2de3e722035524c5b1e4643f054 
So the fix can be out soon
Old and new tests
**Checklist:**
> fix(docker): simplify image specification parsing

- .github/PULL_REQUEST_TEMPLATE.md
-
Adding a new checklist item to remind authors and reviewers to ensure their changes are backwards compatible
See above
N/A
-
**Checklist:**
> chore: add backwards compatibility confirmation to PR checklist

- src/main/java/com/aws/greengrass/ipc/IPCEventStreamService.java
- src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
- src/main/java/com/aws/greengrass/mqttclient/spool/Spool.java
- src/main/java/com/aws/greengrass/util/Utils.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandler.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/ServiceOperationMappingContinuationHandler.java
> fix: fix LGTM warnings

- src/main/java/com/aws/greengrass/config/Topics.java
> fix: fix remaining LGTM alert

- src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java
- src/main/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverter.java
- src/main/java/com/aws/greengrass/deployment/model/RunWith.java
- src/main/java/com/aws/greengrass/deployment/model/SystemResourceLimits.java
- src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java
- src/test/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverterTest.java
- src/test/java/com/aws/greengrass/deployment/model/RunWithTest.java
Pass the resource limits from the local override request to the runwith config.
unit tests.
**Checklist:**
> feat(resource limits): pass resource limits from local cli

- src/integrationtests/java/com/aws/greengrass/integrationtests/provisioning/ProvisionFromTestPlugin.java
All tests pass on Windows:
https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/985/checks?check_run_id=2669200556#step:6:36964
**Checklist:**
> fix(windows): fix ProvisionFromTestPlugin to run on Windows

- src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/componentmanager/ComponentManagerE2ETest.java
Cleaned up e2e test. 
**Checklist:**
> fix: updated  e2e tests

- src/main/java/com/aws/greengrass/deployment/DefaultDeploymentTask.java
- src/test/java/com/aws/greengrass/deployment/DeploymentTaskTest.java
> fix(deployment): add missing error log for certain cases

- src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java
- src/test/java/com/aws/greengrass/tes/CredentialRequestHandlerTest.java
TES: prevent concurrent cloud credential requests by producing a future which represents the single caller (if any). If any more threads come in and try to get credentials before the request has completed, then they will block on the pending request and return whatever value it ultimately comes back with.
Existing tests passing. New test to verify the functionality by hitting TES with 3 requests at the same time and verifying that only one of them goes to the cloud.
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> perf(tes): prevent concurrent cloud credential requests through TES

- conf/recipe.yaml
- pom.xml
- src/test/greengrass-nucleus-benchmark/pom.xml
> build: bump to 2.4.0

- src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
> fix: coerce instead of casting

- pom.xml
- src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/FleetConfigWithResourceLimits.json
- src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/SampleJobDocumentWithUser_1.json
- src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/config_run_with_user.yaml
- src/main/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverter.java
- src/main/java/com/aws/greengrass/deployment/model/SystemResourceLimits.java
- src/main/java/com/aws/greengrass/util/platforms/unix/linux/LinuxSystemResourceController.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractDeleteThingShadowOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractGetThingShadowOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractListNamedShadowsForThingOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractPauseComponentOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractResumeComponentOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractUpdateThingShadowOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandler.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/ServiceOperationMappingContinuationHandler.java
- src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java
- src/test/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverterTest.java
- src/test/java/com/aws/greengrass/deployment/model/RunWithTest.java
- src/test/resources/com/aws/greengrass/deployment/converter/FcsDeploymentConfig_Full.json
> refactor: change resource limit property from cpu to cpus

- pom.xml
- src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentServiceIntegrationTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentTaskIntegrationTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/FleetConfigWithResourceLimits.json
- src/integrationtests/resources/com/aws/greengrass/integrationtests/deployment/SampleJobDocumentWithUser_1.json
- src/integrationtests/resources/com/aws/greengrass/integrationtests/lifecyclemanager/config_run_with_user.yaml
- src/main/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverter.java
- src/main/java/com/aws/greengrass/deployment/model/SystemResourceLimits.java
- src/main/java/com/aws/greengrass/util/platforms/unix/linux/LinuxSystemResourceController.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractDeleteThingShadowOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractGetThingShadowOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractListNamedShadowsForThingOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractPauseComponentOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractResumeComponentOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractUpdateThingShadowOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandler.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/ServiceOperationMappingContinuationHandler.java
- src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java
- src/test/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverterTest.java
- src/test/java/com/aws/greengrass/deployment/model/RunWithTest.java
- src/test/resources/com/aws/greengrass/deployment/converter/FcsDeploymentConfig_Full.json
> refactor: change resource limit property from cpu to cpus 

- pom.xml
- src/test/greengrass-nucleus-benchmark/pom.xml
> chore: bump to 2.5

- src/main/java/com/aws/greengrass/lifecyclemanager/Lifecycle.java
Reset lifecycle thread name when the thread quits. If the thread was recycled due to the caching thread pool, then some other task would end up using an improperly named thread which can be confusing.
**Checklist:**
> fix: reset lifecycle thread name back to default when thread quits

- src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java
> fix(tes): do not log credentials at debug level

- src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/deployment/DeploymentE2ETest.java
> test: fix e2e test case

- src/main/java/com/aws/greengrass/util/platforms/windows/WindowsGroupAttributes.java
- src/main/java/com/aws/greengrass/util/platforms/windows/WindowsPlatform.java
- src/test/java/com/aws/greengrass/util/platforms/windows/WindowsPlatformTest.java
Implement `lookupGroupByName` and `lookupGroupByIdentifier` for the Windows platform.
Add unit tests
**Checklist:**
> feat(windows): lookup windows group

- pom.xml
> build: use device sdk 1.4.3

- src/main/java/com/aws/greengrass/util/Exec.java
> fix(exec): revert binary incompatible change to Exec setenv signature

- .github/workflows/externalPR.yml
Fix the binary compatibility report generation which was failing due to missing the PR number and SHA hash.
**Checklist:**
> ci: fix binary compatibility checker

- pom.xml
> chore(deps): use windows snapshot version of IoT Device SDK

- pom.xml
- src/main/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverter.java
- src/test/java/com/aws/greengrass/deployment/converter/DeploymentDocumentConverterTest.java
- src/test/resources/com/aws/greengrass/deployment/converter/FcsDeploymentConfig_Full.json
Support windows user for local/cloud deployment
Unit tests
**Checklist:**
- [ X] Updated or added new unit tests
> feat(windows): add windowsUser

- src/main/java/com/aws/greengrass/util/platforms/windows/WindowsPlatform.java
Update the system name lookup to computerName$ so not any random username ending with $ will work.
**Checklist:**
> fix: tighten SYSTEM username lookup to only match computerName$ not just endsWith $

- src/main/java/com/aws/greengrass/tes/CredentialRequestHandler.java
Resolves NPE when trying to complete future which is already set to null. Ensuring that we validate that the future is non-null before trying to call a method on it. Also only changing the future within a synchronized block.
```
java.lang.NullPointerException
at com.aws.greengrass.tes.CredentialRequestHandler.getCredentialsBypassCache(CredentialRequestHandler.java:263)
```
**Checklist:**
> fix(tes): avoid NPE due to race condition when completing TES future

- .github/workflows/externalPR.yml
> chore: use a fixed version of 5monkeys/cobertura-action

- src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractCreateSharedLockOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractDeleteSharedPropertyOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractExtendSharedLockOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractPublishSharedPropertyOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractQuerySharedPropertiesOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractRetrieveSharedLockOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractRetrieveSharedPropertyOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractUnlockSharedPropertyOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java
Adding the service models to the nucleus to support cluster related operations.
**Checklist:**
> chore: adding more cluster related operations

- src/main/java/com/aws/greengrass/componentmanager/builtins/ArtifactDownloader.java
> chore: add clear log when artifact exists but digest doesn't match

- src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/UnloadableServiceIntegTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/provisioning/ProvisionFromTestPlugin.java
- src/main/java/com/aws/greengrass/util/DefaultConcurrentHashMap.java
> fix: fix containsKey on DefaultConcurrentHashMap

- pom.xml
- src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java
> chore(deps): update dependencies

- pom.xml
> fix(deps): downgrade AWS SDK to a compatible version

- .github/PULL_REQUEST_TEMPLATE.md
- COMPATIBILITY.md
Added compatibility guideline. Modified the PR template accordingly.
**Checklist:**
> docs: add compatibility guideline

- src/main/java/com/aws/greengrass/authorization/AuthorizationIPCAgent.java
Adding logging in AuthorizationIPCAgent for easier debugging
Needed for easier debugging
- [x ] If my code makes a remote network call, it was tested with a proxy.
- [ x] Updated the README if applicable.
- [x ] I confirm that the change is backwards compatible.
- [x ] Any modification or deletion of public interfaces does not impact other plugin components.
- [ x] For external library version updates, I have reviewed its change logs and Nucleus does not consume  …
> chore: adding logging in AuthorizationIPCAgent

- src/main/java/com/aws/greengrass/componentmanager/KernelConfigResolver.java
- src/test/java/com/aws/greengrass/componentmanager/KernelConfigResolverTest.java
Before, nucleus interpolates component config after aggregating config from recipe, deployment update and running config. Running config is dynamic which exposes the risk of attacker can manipulate the running config in a way to be interpolated in next deployment.
This change let nucleus only interpolate system parameter for component configuration, not configuration parameter. For example:
* `{configuration:/paramA}` won't be interpolated in configuration section
* `{iot:thingName}` will be interpolated
This makes the component configuration section interpolation behavior static.
Security risk: enabling interpolation for configuration parameter under configuration section can cause issue like
corrupted running config triggers …
> feat: only interpolate system parameter in component configuration section, not configuration parameter

- pom.xml
> chore(deps): update surefire

- src/integrationtests/java/com/aws/greengrass/integrationtests/deployment/DeploymentConfigMergingTest.java
- src/main/java/com/aws/greengrass/lifecyclemanager/UpdateSystemPolicyService.java
-
Set deployment id in PostComponentUpdateEvent so components subscribing to the events know if the deployment that they've been waiting for has finished.
Note - UpdateSystemPolicyService assumes there can be a queued batch of actions which it executes when components no longer defer updates, but there's only ever one action queued because deployment workflows do not execute in parallel. Because of this currently this code grabs the deployment id of the first item and sets it in pre and post component update events.
any deprecated method or …
> fix: set deployement id in PostComponentUpdateEvent

- src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/status/PeriodicFleetStatusServiceTest.java
- src/main/java/com/aws/greengrass/status/FleetStatusService.java
- src/main/java/com/aws/greengrass/status/model/FleetStatusDetails.java
Needed to resolve some merge conflicts.
> fix: resolve merge conflicts

- conf/recipe.yaml
- pom.xml
- src/test/greengrass-nucleus-benchmark/pom.xml
> chore: update to 2.8.0

- pom.xml
Updates to the latest device SDK which has important fixes to be released.
> chore(deps): update to latest device SDK

- src/test/resources/com/aws/greengrass/lifecyclemanager/config.yaml
> chore: fix typo, remove dead config

- src/integrationtests/java/com/aws/greengrass/integrationtests/BaseITCase.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCServicesTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/KernelTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/status/PeriodicFleetStatusServiceTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/telemetry/TelemetryAgentTest.java
- src/main/java/com/aws/greengrass/componentmanager/ComponentServiceHelper.java
- src/main/java/com/aws/greengrass/deployment/DeviceConfiguration.java
- src/main/java/com/aws/greengrass/deployment/IotJobsHelper.java
- src/main/java/com/aws/greengrass/mqttclient/AwsIotMqttClient.java
- src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
- src/test/java/com/aws/greengrass/componentmanager/ComponentServiceHelperTest.java
- src/test/java/com/aws/greengrass/deployment/DynamicComponentConfigurationValidatorTest.java
- src/test/java/com/aws/greengrass/deployment/IotJobsHelperTest.java
- src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java
- src/test/java/com/aws/greengrass/telemetry/TelemetryAgentTest.java
Speeds up tests by ~6 minutes. See each of the [commits](https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1303/commits) for more specific information.
> test: speed up tests by decreasing waits with TestFeatureParameters

- src/integrationtests/java/com/aws/greengrass/integrationtests/lifecyclemanager/GenericExternalServiceIntegTest.java
- src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java
This change calls `requestReinstall` when configuration changes the lifecycle of a component which is currently BROKEN. Today, broken components can only get un-broken by changing the install portion of lifecycle, or by changing the version of a component. This will allow more components to get unbroken more easily and in a more understandable way. …
> feat: allow component configuration changes to move out of BROKEN

- src/integrationtests/java/com/aws/greengrass/integrationtests/componentmanager/plugins/docker/DockerImageArtifactDownload01Test.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/componentmanager/plugins/docker/downloader/recipes/docker.image.from.ecr.private.registry01-1.0.0.yaml
- src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageDownloader.java
- src/main/java/com/aws/greengrass/componentmanager/plugins/docker/EcrAccessor.java
- src/test/java/com/aws/greengrass/componentmanager/plugins/docker/DockerImageDownloaderTest.java
- src/test/java/com/aws/greengrass/componentmanager/plugins/docker/EcrAccessorTest.java
> feat: allow access to private ECR repo in other regions than Greengrass Core region

- src/main/java/com/aws/greengrass/lifecyclemanager/KernelLifecycle.java
1. Add a 5-second timeout for executor service stopping during kernel shutdown on external signal.
Currently, when sigterm is received, executor shutdown and context shutdown happens instantly (within 1ms). Sometimes   threads under executor service are not interrupted properly because of such short timing.
Adding a 5-second timeout to interrupt threads properly.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> fix: increase timeout for executor service shutdown when sigterm is received

- src/main/java/com/aws/greengrass/componentmanager/builtins/S3Downloader.java
- src/main/java/com/aws/greengrass/deployment/errorcode/DeploymentErrorCode.java
fix typo in deployment error code
> fix: correct deployment error code typo

- src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
- src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java
Fix for MQTT client so that we will forward messages to our subscribers (if we have any) when the messages comes into Greengrass on the wrong client. This can happen for IoT Jobs, which sends the update/accepted response to the same client that sent the update request, rather than to the client which has subscribed to the update/accepted topic.
This is required to fix problems when running deployments when we have more than 50 subscriptions and thus more than 1 MQTT client is in use.
Tested by adding a regression test and verified that it fails without the change, but passes with the change.
@indougnito verified it also passes our reproduction in a UAT.
**Any additional …
> fix(mqtt): forward messages to subs when message comes from wrong client

- CHANGELOG.md
> chore: update changelog for Nucleus 2.8

- pom.xml
> chore(deps): bump jackson version

- CHANGELOG.md
- conf/recipe.yaml
- pom.xml
- src/test/greengrass-nucleus-benchmark/pom.xml
> chore: update versions and changelog

- .github/workflows/maven.yml
> ci: use ubuntu 20

- src/main/java/com/aws/greengrass/util/GreengrassServiceClientFactory.java
- always keep a cache of http client for ggv2 data client;
- reconfigure http client only when private key or cert or root ca path changes.
We made a recent change in https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1368 to cache http client for ggv2 data client. Before it, we never closed v2 data client properly. 
However, it exposed a new issue - if other plugins are still using the data client while we are trying to close the client, then their api calls would fail with `java.lang.IllegalStateException: Connection pool shut down`. 
Specifically, when we fetch data client for the first time, we update data plane port with the default port number (if not previously configured), which is …
> fix: cache http client for ggv2 data client properly

- src/main/java/com/aws/greengrass/mqttclient/MqttClient.java
Read `noProxyAddresses` from the device configuration and do not set the MQTT client to use the proxy if the endpoint is in that list.
> fix(mqtt): read and respect noProxyAddresses for mqtt connection

- src/main/java/com/aws/greengrass/mqttclient/AwsIotMqtt5Client.java
add the following options to MQTT 5:
- receiveMaximum
- sessionExpirySeconds
- minimumReconnectDelaySeconds
- maximumReconnectDelaySeconds
- minimumConnectedTimeBeforeRetryResetSeconds
These are the only new MQTT 5 specific settings and the client will be automatically stopped and recreated when any of these change due to the existing reconnect behavior on config changes. …
> fix(mqtt5): add mqtt5 config options

- src/main/java/com/aws/greengrass/authorization/AuthorizationHandler.java
- src/main/java/com/aws/greengrass/lifecyclemanager/Lifecycle.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/AuthenticationData.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/DebugLoggingOperationHandler.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/EventStreamRPCServiceHandler.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/InvalidServiceConfigurationException.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/IpcServer.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandler.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandlerContext.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandlerFactory.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/RpcServer.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/ServiceOperationMappingContinuationHandler.java
-
- Removed primary/standby changes
- Imported latest SDK snapshot and IPC server code for cluster operations
> chore: update cluster IPC server code

- src/main/java/com/aws/greengrass/deployment/model/LocalOverrideRequest.java
Add failure handling policy variable to LocalOverrideRequest model 
To update LocalOverrideRequest in cli project
> feat: Configurable failure handling policy

- conf/recipe.yaml
- pom.xml
- src/test/greengrass-nucleus-benchmark/pom.xml
> chore: bump to version 2.11

- src/main/java/com/aws/greengrass/mqttclient/v5/UserProperty.java
Needed so we can serialize and deserialize userProperties using Jackson in the disk spooler.
> feat: added constructors to userproperty

- src/main/java/com/aws/greengrass/mqttclient/spool/Spool.java
> chore: modify spooler logs

- pom.xml
- src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java
Upgrade to version 2.2.0 of https://github.com/aws-greengrass/aws-greengrass-logging-java
Pre-requisite: merge https://github.com/aws-greengrass/aws-greengrass-logging-java/pull/171
Newer versions of logback and slf4j-api.
> chore: upgrade to greengrass logging 2.2.0

- pom.xml
- src/test/java/com/aws/greengrass/lifecyclemanager/LogManagerHelperTest.java
This reverts commit 74e1f5fa85b035ead34d44613214e47b6d9437e0.
https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1509
We observed a Windows performance test failure due to inability to rotate log files.
> revert: "chore: upgrade to greengrass logging 2.2.0 (#1509)"

- README.md
> chore: fix status badge

- pom.xml
> chore(dep): bump sdk version to public version

- pom.xml
> chore(deps): bump device sdk version

- DEVELOPING.md
- pom.xml
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractCancelLocalDeploymentOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractPutComponentMetricOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GeneratedAbstractSubscribeToCertificateUpdatesOperationHandler.java
- src/main/java/software/amazon/awssdk/aws/greengrass/GreengrassCoreIPCService.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/AuthenticationData.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/Authorization.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/DebugLoggingOperationHandler.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/EventStreamRPCServiceHandler.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/InvalidServiceConfigurationException.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandler.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandlerContext.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandlerFactory.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/RpcServer.java
- src/main/java/software/amazon/awssdk/eventstreamrpc/ServiceOperationMappingContinuationHandler.java
GG-44743
Update the generated code from smithy-iot-device-sdk-greengrass-ipc, targeting aws-iot-device-sdk 1.19.1
We need this package up to date so we can build changes to the ipc apis on top of it.
> chore: update generated code from smithy-iot-device-sdk-greengrass-ipc targeting 1.19.1

- pom.xml
> chore(deps): update device sdk to 1.20.1

- src/main/java/com/aws/greengrass/dependency/Context.java
Removing unnecessary locking in `Context`
> fix: remove unnecessary synchronization in Context

- .github/workflows/codeql.yml
- .github/workflows/externalPR.yml
- .github/workflows/flakeFinder.yaml
- .github/workflows/maven.yml
- .github/workflows/otfUats.yaml
Upgrade all our github actions to their latest versions.
> ci: upgrade github actions

- src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/IPCPubSubRemovalTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
- src/test/java/com/aws/greengrass/builtin/services/configstore/ConfigStoreIPCEventStreamAgentTest.java
- src/test/java/com/aws/greengrass/componentmanager/ComponentServiceHelperTest.java
- src/test/java/com/aws/greengrass/mqttclient/MqttClientTest.java
- src/test/java/com/aws/greengrass/telemetry/TelemetryAgentTest.java
- src/test/java/com/aws/greengrass/testing/TestFeatureParametersTest.java
Fix flaky tests identified in the last few months from https://github.com/aws-greengrass/aws-greengrass-nucleus/actions/workflows/flakeFinder.yaml
> test: fix test flakiness seen in last 2 months

- src/integrationtests/java/com/aws/greengrass/integrationtests/status/EventFleetStatusServiceTest.java
Closes #1603.
Fix a flaky test #1603. Ran 400 times successfully locally.
> test: fix FSS test flakiness

- pom.xml
> chore: update device sdk for GetSecretValueRequest changes

- conf/recipe.yaml
- pom.xml
- src/test/greengrass-nucleus-benchmark/pom.xml
Bump Nucleus snapshot version since minor release is complete
> chore: bump version

- pom.xml
SIM [link](https://issues.amazon.com/JAVA-7885) from S3 team 
Include java sdk fix "Setting dualstack system property does not invoke s3 dualstack endpoint"
> chore: update sdk to include java fix

- pom.xml
> fix: update device sdk version to support latest TLS policy

- pom.xml
> chore: remove whitespace

- pom.xml
> chore: add white space

- README_SYSTEMD_GUIDANCE.md
> Create systemd fix document
